void exit(int status);
void free(void *ptr);
void re_init();
void make_pass();
int getaline();
int parse_line();
void initialize();
void process();
struct oper *mne_look();
void strip_ext(char *fname);
void localinit();
void do_op(int opcode,int class);
int bitop(int op,int mode,int class);
void do_gen(int op,int mode,int pnorm,int px,int py);
void do_indexed(int op);
void epage(int p);
char *skip_white(char* ptr);
void fatal(char* str);
void error(char* str);
void warn(char* str);
int delim(char c);
void eword(int wd);
int emit(int byte);
void f_record();
void print_line();
int any(char c,char* str);
char mapdn(char c);
char *alloc();
int lobyte(int i);
int hibyte(int i);
int head(char* str1,char* str2);
int alpha(char c);
int alphan(char c);
int white(char c);
char *alloc(int nbytes);
int eval();
int is_op(char c);
int get_term();
void fwdinit();
void fwdreinit();
void fwdmark();
void fwdnext();
void do_pseudo(int op);
int hash(char* s);
int install(char* str,int val);
struct nlist* lookup(char* name);
struct oper* mne_look(char* str);
void hexout(int byte);
void* malloc(int n);
