

TL_IDENT1:  fcb $01
            fcb $00
            fcb $56
            fcb $02
            fcb $88
byte_8005:  fcb $42
byte_8006:  fcb $A2
            fcb $56
            fcb $02
            fcb $88
            fcb $42
byte_800B:  fcb $A2
            fcb $5D
            fcb $4E
            fcb $18
byte_800F:  fcb $15
            fcb $88
byte_8011:  fcb $02
word_8012:  fdb $0182
byte_8014:  fcb $FF
TL_CONF01:  fcb $81
TL_ConfigurationFlags2:fcb $22
TL_Amount_MINTHR_IsIncreasedAtKeyOnOnly:fcb $03
byte_8018:  fcb $10
byte_8019:  fcb $02
byte_801A:  fcb $01
TL_ValueOf_MINTHR_WhenBatteryDisconnected:fcb $5C
byte_801C:  fcb $26
byte_801D:  fcb $4C
byte_801E:  fcb $04
byte_801F:  fcb $90
byte_8020:  fcb $D0
byte_8021:  fcb $00
word_8022:  fdb $0000
            fcb $05
            fcb $1F
            fcb $00
            fcb $00
            fcb $32
            fcb $3E
            fcb $06
            fcb $00
            fcb $42
            fcb $5D
            fcb $0E
            fcb $FF
            fcb $90
            fcb $7D
            fcb $00
            fcb $00
            fcb $29
            fcb $9C
            fcb $05
byte_8037:  fcb $90
byte_8038:  fcb $20
            fcb $0F
            fcb $A0
            fcb $14
            fcb $50
            fcb $17
            fcb $70
            fcb $20
            fcb $D0
            fcb $23
            fcb $F0
            fcb $2E
            fcb $E0
            fcb $3E
            fcb $80
            fcb $4E
            fcb $20
            fcb $5D
            fcb $C0
            fcb $6D
            fcb $60
            fcb $7D
            fcb $00
            fcb $8C
            fcb $A0
            fcb $9C
            fcb $40
            fcb $03
            fcb $13
            fcb $00
            fcb $05
            fcb $25
            fcb $2F
            fcb $90
            fcb $01
            fcb $05
            fcb $9C
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
word_8072:  fdb $0393
byte_8074:  fcb $87
            fcb $00
word_8076:  fdb $0003
byte_8078:  fcb $93
            fcb $87
word_807A:  fdb $53B5
word_807C:  fdb $7530
byte_807E:  fcb $00
byte_807F:  fcb $14
byte_8080:  fcb $02
byte_8081:  fcb $04
byte_8082:  fcb $05
            fcb $11
            fcb $09
            fcb $00
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $0E
            fcb $08
            fcb $08
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $0E
            fcb $0A
            fcb $0A
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $20
            fcb $20
            fcb $14
            fcb $0C
            fcb $0A
            fcb $1C
            fcb $1C
            fcb $1E
            fcb $20
            fcb $25
            fcb $25
            fcb $16
            fcb $0D
            fcb $0B
            fcb $1C
            fcb $1C
            fcb $1F
            fcb $31
            fcb $2D
            fcb $27
            fcb $17
            fcb $0E
            fcb $10
            fcb $1C
            fcb $1C
            fcb $20
            fcb $3C
            fcb $2B
            fcb $29
            fcb $1A
            fcb $10
            fcb $12
            fcb $1C
            fcb $1C
            fcb $26
            fcb $3D
            fcb $32
            fcb $2C
            fcb $1E
            fcb $10
            fcb $10
            fcb $1C
            fcb $2C
            fcb $36
            fcb $36
            fcb $34
            fcb $2F
            fcb $20
            fcb $19
            fcb $13
            fcb $1C
            fcb $2C
            fcb $36
            fcb $3B
            fcb $38
            fcb $30
            fcb $21
            fcb $1B
            fcb $16
            fcb $1C
            fcb $2C
            fcb $36
            fcb $43
            fcb $39
            fcb $33
            fcb $22
            fcb $1B
            fcb $16
            fcb $1C
            fcb $2C
            fcb $36
            fcb $47
            fcb $45
            fcb $42
            fcb $33
            fcb $22
            fcb $28
            fcb $1C
            fcb $2C
            fcb $3A
            fcb $55
            fcb $51
            fcb $49
            fcb $3F
            fcb $29
            fcb $29
            fcb $1C
            fcb $2C
            fcb $3A
            fcb $56
            fcb $52
            fcb $4A
            fcb $40
            fcb $23
            fcb $23
            fcb $1C
            fcb $2C
            fcb $3C
            fcb $58
            fcb $52
            fcb $4A
            fcb $3F
            fcb $31
            fcb $24
            fcb $1C
            fcb $2C
            fcb $40
            fcb $53
            fcb $55
            fcb $49
            fcb $46
            fcb $42
            fcb $3B
            fcb $1C
            fcb $2C
            fcb $3C
            fcb $4B
            fcb $47
            fcb $49
            fcb $48
            fcb $42
            fcb $3C
            fcb $1C
            fcb $2C
            fcb $3C
            fcb $58
            fcb $52
            fcb $4D
            fcb $48
            fcb $3F
            fcb $3A
            fcb $11
            fcb $09
            fcb $00
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $0E
            fcb $08
            fcb $08
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $0E
            fcb $0A
            fcb $0A
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $12
            fcb $0A
            fcb $0A
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $16
            fcb $0C
            fcb $0A
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $24
            fcb $18
            fcb $0C
            fcb $0A
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $2C
            fcb $1C
            fcb $12
            fcb $10
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $2A
            fcb $28
            fcb $18
            fcb $12
            fcb $10
            fcb $1C
            fcb $4C
            fcb $4A
            fcb $40
            fcb $36
            fcb $2C
            fcb $1C
            fcb $12
            fcb $10
            fcb $1C
            fcb $4C
            fcb $48
            fcb $4D
            fcb $36
            fcb $34
            fcb $24
            fcb $12
            fcb $10
            fcb $1C
            fcb $4C
            fcb $48
            fcb $4A
            fcb $48
            fcb $44
            fcb $2B
            fcb $12
            fcb $12
            fcb $1C
            fcb $4C
            fcb $48
            fcb $4E
            fcb $4D
            fcb $48
            fcb $33
            fcb $1F
            fcb $17
            fcb $1C
            fcb $4C
            fcb $48
            fcb $50
            fcb $4B
            fcb $44
            fcb $42
            fcb $32
            fcb $21
            fcb $1C
            fcb $4C
            fcb $54
            fcb $54
            fcb $56
            fcb $54
            fcb $42
            fcb $2A
            fcb $21
            fcb $1C
            fcb $4C
            fcb $5B
            fcb $58
            fcb $58
            fcb $54
            fcb $47
            fcb $28
            fcb $21
            fcb $1C
            fcb $4C
            fcb $4D
            fcb $50
            fcb $4D
            fcb $47
            fcb $32
            fcb $26
            fcb $23
            fcb $1C
            fcb $4C
            fcb $4D
            fcb $50
            fcb $4B
            fcb $3E
            fcb $2E
            fcb $28
            fcb $25
            fcb $1C
            fcb $4C
            fcb $4D
            fcb $50
            fcb $4B
            fcb $3E
            fcb $2E
            fcb $28
            fcb $25
byte_81BB:  fcb $03
            fcb $11
            fcb $09
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $98
            fcb $98
            fcb $98
            fcb $98
            fcb $98
            fcb $98
            fcb $98
            fcb $28
            fcb $26
            fcb $24
            fcb $20
            fcb $20
            fcb $20
            fcb $20
            fcb $20
            fcb $1A
            fcb $26
            fcb $24
            fcb $22
            fcb $20
            fcb $20
            fcb $1A
            fcb $14
            fcb $14
            fcb $14
byte_8278:  fcb $D0
byte_8279:  fcb $06
byte_827A:  fcb $14
byte_827B:  fcb $1C
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
word_828E:  fdb $01B3
            fcb $02
            fcb $00
            fcb $FF
            fcb $00
            fcb $00
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
word_82AF:  fdb $30D4

word_82B1:  fdb $7530
            fcb $11
            fcb $09
            fcb $00
            fcb $3E
            fcb $3E
            fcb $3E
            fcb $3E
            fcb $3E
            fcb $3E
            fcb $42
            fcb $52
            fcb $6C
            fcb $50
            fcb $50
            fcb $40
            fcb $40
            fcb $48
            fcb $50
            fcb $50
            fcb $60
            fcb $80
            fcb $50
            fcb $50
            fcb $40
            fcb $40
            fcb $50
            fcb $58
            fcb $5C
            fcb $69
            fcb $8D
            fcb $4A
            fcb $60
            fcb $5B
            fcb $64
            fcb $6A
            fcb $68
            fcb $68
            fcb $6B
            fcb $86
            fcb $7A
            fcb $7A
            fcb $8E
            fcb $7D
            fcb $73
            fcb $70
            fcb $70
            fcb $6D
            fcb $80
            fcb $8A
            fcb $8A
            fcb $95
            fcb $7E
            fcb $7B
            fcb $74
            fcb $72
            fcb $76
            fcb $7A
            fcb $90
            fcb $9A
            fcb $9D
            fcb $8C
            fcb $7F
            fcb $7A
            fcb $77
            fcb $77
            fcb $7A
            fcb $A0
            fcb $9A
            fcb $9D
            fcb $88
            fcb $7D
            fcb $7A
            fcb $79
            fcb $7A
            fcb $79
            fcb $A0
            fcb $A0
            fcb $9D
            fcb $91
            fcb $80
            fcb $7B
            fcb $7A
            fcb $7C
            fcb $78
            fcb $A0
            fcb $B0
            fcb $9D
            fcb $86
            fcb $7A
            fcb $7D
            fcb $7A
            fcb $7C
            fcb $7E
            fcb $A0
            fcb $B0
            fcb $9D
            fcb $88
            fcb $7C
            fcb $7F
            fcb $7B
            fcb $7C
            fcb $A0
            fcb $A0
            fcb $CC
            fcb $98
            fcb $84
            fcb $7D
            fcb $7F
            fcb $80
            fcb $8A
            fcb $E4
            fcb $A0
            fcb $E7
            fcb $99
            fcb $88
            fcb $7E
            fcb $7E
            fcb $A0
            fcb $E3
            fcb $E3
            fcb $A0
            fcb $D5
            fcb $A2
            fcb $91
            fcb $86
            fcb $87
            fcb $8E
            fcb $F9
            fcb $AC
            fcb $A0
            fcb $DC
            fcb $B2
            fcb $A2
            fcb $97
            fcb $99
            fcb $95
            fcb $95
            fcb $8F
            fcb $A0
            fcb $90
            fcb $D5
            fcb $C3
            fcb $B4
            fcb $A9
            fcb $A5
            fcb $C9
            fcb $9B
            fcb $A0
            fcb $90
            fcb $E1
            fcb $D1
            fcb $C6
            fcb $BE
            fcb $B7
            fcb $DA
            fcb $AA
            fcb $11
            fcb $09
            fcb $00
            fcb $38
            fcb $38
            fcb $38
            fcb $38
            fcb $38
            fcb $38
            fcb $38
            fcb $38
            fcb $38
            fcb $38
            fcb $38
            fcb $38
            fcb $38
            fcb $38
            fcb $38
            fcb $3F
            fcb $3F
            fcb $3F
            fcb $40
            fcb $40
            fcb $40
            fcb $40
            fcb $40
            fcb $40
            fcb $43
            fcb $43
            fcb $43
            fcb $46
            fcb $46
            fcb $46
            fcb $46
            fcb $46
            fcb $46
            fcb $46
            fcb $46
            fcb $46
            fcb $44
            fcb $44
            fcb $44
            fcb $57
            fcb $43
            fcb $42
            fcb $47
            fcb $47
            fcb $47
            fcb $48
            fcb $48
            fcb $4B
            fcb $58
            fcb $45
            fcb $42
            fcb $4A
            fcb $4A
            fcb $4A
            fcb $5F
            fcb $5F
            fcb $5F
            fcb $58
            fcb $32
            fcb $36
            fcb $3E
            fcb $5C
            fcb $4E
            fcb $62
            fcb $64
            fcb $6D
            fcb $31
            fcb $32
            fcb $36
            fcb $43
            fcb $5C
            fcb $5C
            fcb $65
            fcb $68
            fcb $46
            fcb $3C
            fcb $3C
            fcb $3E
            fcb $45
            fcb $62
            fcb $62
            fcb $6B
            fcb $6B
            fcb $50
            fcb $3A
            fcb $35
            fcb $39
            fcb $45
            fcb $5E
            fcb $60
            fcb $6B
            fcb $6B
            fcb $49
            fcb $45
            fcb $42
            fcb $4A
            fcb $53
            fcb $6B
            fcb $6B
            fcb $50
            fcb $50
            fcb $4D
            fcb $43
            fcb $49
            fcb $50
            fcb $55
            fcb $6C
            fcb $6C
            fcb $48
            fcb $48
            fcb $46
            fcb $48
            fcb $4C
            fcb $54
            fcb $5A
            fcb $6E
            fcb $6E
            fcb $4A
            fcb $4A
            fcb $49
            fcb $49
            fcb $4E
            fcb $55
            fcb $59
            fcb $67
            fcb $67
            fcb $4C
            fcb $4C
            fcb $4C
            fcb $4B
            fcb $51
            fcb $57
            fcb $59
            fcb $59
            fcb $59
            fcb $4D
            fcb $4D
            fcb $4D
            fcb $55
            fcb $5D
            fcb $60
            fcb $70
            fcb $70
            fcb $70
            fcb $4A
            fcb $4A
            fcb $4A
            fcb $55
            fcb $5F
            fcb $5E
            fcb $5F
            fcb $5F
            fcb $5F
            fcb $D0
            fcb $A4
            fcb $74
            fcb $13
            fcb $0C
            fcb $0A
            fcb $04
            fcb $04
            fcb $04
            fcb $14
            fcb $14
            fcb $14
            fcb $14
            fcb $10
            fcb $0A
            fcb $03
            fcb $03
            fcb $03
            fcb $CA
            fcb $88
            fcb $58
            fcb $2A
            fcb $23
            fcb $0F
            fcb $05
            fcb $00
            fcb $00
            fcb $50
            fcb $48
            fcb $34
            fcb $1E
            fcb $10
            fcb $08
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $40
            fcb $60
            fcb $60
            fcb $80
            fcb $80
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $40
            fcb $40
            fcb $30
            fcb $30
            fcb $28
            fcb $20
            fcb $1A
            fcb $08
            fcb $08
byte_842A:  fcb $00
            fcb $02
            fcb $58
            fcb $00
            fcb $00
            fcb $00
            fcb $FF
            fcb $00
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $08
            fcb $61
            fcb $80
            fcb $FF
            fcb $30
            fcb $71
            fcb $73
            fcb $FD
            fcb $60
            fcb $81
            fcb $49
            fcb $FE
            fcb $4B
            fcb $92
            fcb $2C
            fcb $FE
            fcb $C0
            fcb $A2
            fcb $18
            fcb $FF
            fcb $70
            fcb $C2
            fcb $06
            fcb $FF
            fcb $E9
            fcb $E3
            fcb $03
            fcb $FF
            fcb $E5
            fcb $FF
            fcb $00
            fcb $F8
            fcb $C0
            fcb $70
            fcb $2D
            fcb $28
            fcb $25
            fcb $14
            fcb $14
            fcb $14
            fcb $CC
            fcb $CC
            fcb $CC
            fcb $CC
            fcb $CC
            fcb $CC
            fcb $E6
            fcb $FF
            fcb $FF
            fcb $04
            fcb $0C
            fcb $00
            fcb $00
            fcb $AB
            fcb $30
            fcb $18
            fcb $00
            fcb $D5
            fcb $60
            fcb $40
            fcb $02
            fcb $00
            fcb $80
            fcb $80
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $02
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $FF
            fcb $00
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
TL_TL_8481: fdb $8000
TL_TL_8483: fcb $D0
TL_TL_8484: fcb $D0
TL_TL_8485: fcb $04
            fcb $10
            fcb $10
            fcb $10
            fcb $10
            fcb $12
            fcb $18
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $10
            fcb $10
            fcb $10
            fcb $0B
            fcb $08
            fcb $08
            fcb $04
            fcb $04
            fcb $04
            fcb $20
            fcb $20
            fcb $20
            fcb $18
            fcb $18
            fcb $18
            fcb $18
            fcb $18
            fcb $18
            fcb $CF
            fcb $A0
            fcb $7D
            fcb $32
            fcb $2A
            fcb $2A
            fcb $1C
            fcb $1C
            fcb $16
            fcb $60
            fcb $50
            fcb $40
            fcb $40
            fcb $30
            fcb $30
            fcb $10
            fcb $10
            fcb $10
            fcb $20
            fcb $20
            fcb $20
            fcb $20
            fcb $20
            fcb $40
            fcb $40
            fcb $40
            fcb $40
            fcb $80
            fcb $80
byte_84D2:  fcb $96
byte_84D3:  fcb $60
byte_84D4:  fcb $9F
            fcb $20
            fcb $20
word_84D7:  fdb $0001
word_84D9:  fdb $FFD6
word_84DB:  fdb $0219
byte_84DD:  fcb $99
byte_84DE:  fcb $99
            fcb $40
            fcb $40
byte_84E1:  fcb $F0
            fcb $28
            fcb $28
            fcb $24
            fcb $1D
            fcb $18
            fcb $18
            fcb $18
            fcb $18
            fcb $18
byte_84EB:  fcb $10
word_84EC:  fdb $024F
            fcb $05
            fcb $13
            fcb $00
            fcb $0A
            fcb $AB
            fcb $19
            fcb $40
            fcb $0A
            fcb $AB
            fcb $1F
            fcb $80
            fcb $02
            fcb $11
            fcb $3E
            fcb $C0
            fcb $01
            fcb $57
            fcb $6D
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $05
            fcb $09
            fcb $00
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $1C
            fcb $18
            fcb $18
            fcb $18
            fcb $18
            fcb $18
            fcb $18
            fcb $18
            fcb $18
            fcb $18
            fcb $18
            fcb $18
            fcb $18
            fcb $18
            fcb $18
            fcb $18
            fcb $18
            fcb $18
            fcb $18
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $05
            fcb $09
            fcb $00
            fcb $22
            fcb $22
            fcb $22
            fcb $22
            fcb $22
            fcb $22
            fcb $22
            fcb $22
            fcb $22
            fcb $22
            fcb $22
            fcb $22
            fcb $22
            fcb $22
            fcb $22
            fcb $22
            fcb $22
            fcb $22
            fcb $22
            fcb $22
            fcb $22
            fcb $22
            fcb $22
            fcb $22
            fcb $22
            fcb $22
            fcb $22
            fcb $20
            fcb $20
            fcb $20
            fcb $20
            fcb $20
            fcb $20
            fcb $20
            fcb $20
            fcb $20
            fcb $20
            fcb $20
            fcb $20
            fcb $20
            fcb $20
            fcb $20
            fcb $20
            fcb $20
            fcb $20
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
byte_8645:  fcb $0B
byte_8646:  fcb $10
byte_8647:  fcb $20
byte_8648:  fcb $20
byte_8649:  fcb $04
byte_864A:  fcb $02
byte_864B:  fcb $60
byte_864C:  fcb $01
byte_864D:  fcb $FE
byte_864E:  fcb $29
            fcb $40
byte_8650:  fcb $0B
byte_8651:  fcb $05
byte_8652:  fcb $8C
            fcb $C0
byte_8654:  fcb $0B
byte_8655:  fcb $15
            fcb $20
byte_8657:  fcb $26
byte_8658:  fcb $10
byte_8659:  fcb $A0
            fcb $C0
            fcb $C0
byte_865C:  fcb $D6
byte_865D:  fcb $08
byte_865E:  fcb $2C
byte_865F:  fcb $74
byte_8660:  fcb $FF
byte_8661:  fcb $01
byte_8662:  fcb $38
            fcb $10
            fcb $07
            fcb $A0
            fcb $00
            fcb $C0
            fcb $08
            fcb $03
            fcb $90
            fcb $00
            fcb $E0
byte_866D:  fcb $A8
byte_866E:  fcb $68
byte_866F:  fcb $10
byte_8670:  fcb $04
byte_8671:  fcb $58
byte_8672:  fcb $17
byte_8673:  fcb $85
byte_8674:  fcb $32
byte_8675:  fcb $24
byte_8676:  fcb $56
byte_8677:  fcb $F1
byte_8678:  fcb $17
word_8679:  fdb $0001
byte_867B:  fcb $6E
byte_867C:  fcb $A0
word_867D:  fdb $0384
byte_867F:  fcb $02
byte_8680:  fcb $C0
byte_8681:  fcb $F0
byte_8682:  fcb $03
byte_8683:  fcb $01
byte_8684:  fcb $08
byte_8685:  fcb $0A
byte_8686:  fcb $9A
word_8687:  fdb $0000
word_8689:  fdb $030A
byte_868B:  fcb $00
byte_868C:  fcb $02
word_868D:  fdb $02F0
word_868F:  fdb $9C40
word_8691:  fdb $0190
byte_8693:  fcb $E0
byte_8694:  fcb $06
word_8695:  fdb $B220
word_8697:  fdb $0190
byte_8699:  fcb $80
byte_869A:  fcb $01
word_869B:  fdb $00B6
byte_869D:  fcb $0F
byte_869E:  fcb $1C
byte_869F:  fcb $1C
            fcb $02
            fcb $05
            fcb $00
            fcb $01
            fcb $6E
            fcb $0C
            fcb $0A
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $02
            fcb $05
            fcb $00
            fcb $FF
            fcb $9A
            fcb $0F
            fcb $FC
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
byte_86B6:  fcb $71
            fcb $03
            fcb $D0
            fcb $D0
            fcb $00
            fcb $00
            fcb $D0
            fcb $D0
            fcb $00
            fcb $00
            fcb $D0
            fcb $D0
            fcb $05
            fcb $58
            fcb $E0
            fcb $FE
            fcb $66
            fcb $80
            fcb $A0
            fcb $FD
            fcb $CD
            fcb $A8
            fcb $48
            fcb $FF
            fcb $9A
            fcb $D0
            fcb $38
            fcb $00
            fcb $CD
            fcb $F8
            fcb $58
            fcb $03
            fcb $9A
            fcb $28
            fcb $FF
            fcb $7A
            fcb $C8
            fcb $10
            fcb $FF
            fcb $9A
            fcb $F0
            fcb $00
byte_86E0:  fcb $11
byte_86E1:  fcb $A0
byte_86E2:  fcb $20
byte_86E3:  fcb $D0
byte_86E4:  fcb $EE
            fcb $04
            fcb $14
            fcb $11
            fcb $00
            fcb $00
            fcb $3C
            fcb $11
            fcb $00
            fcb $00
            fcb $64
            fcb $11
            fcb $00
            fcb $3C
            fcb $82
            fcb $18
byte_86F4:  fcb $00
            fcb $04
            fcb $68
            fcb $50
            fcb $FF
            fcb $55
            fcb $80
            fcb $40
            fcb $FF
            fcb $6B
            fcb $B0
            fcb $24
            fcb $FF
            fcb $07
            fcb $D5
            fcb $00
            fcb $03
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $10
            fcb $00
            fcb $00
            fcb $00
            fcb $21
            fcb $00
            fcb $04
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $02
            fcb $00
            fcb $00
            fcb $00
            fcb $05
            fcb $00
            fcb $00
            fcb $00
            fcb $1E
            fcb $00
            fcb $04
            fcb $1C
            fcb $08
            fcb $00
            fcb $00
            fcb $2E
            fcb $08
            fcb $00
            fcb $00
            fcb $3F
            fcb $08
            fcb $00
            fcb $00
            fcb $FF
            fcb $08
            fcb $03
            fcb $9A
            fcb $50
            fcb $FF
            fcb $DF
            fcb $C8
            fcb $4A
            fcb $FF
            fcb $C0
            fcb $F0
            fcb $40
            fcb $05
            fcb $58
            fcb $96
            fcb $FF
            fcb $86
            fcb $A8
            fcb $70
            fcb $FF
            fcb $86
            fcb $D0
            fcb $5D
            fcb $00
            fcb $00
            fcb $E5
            fcb $5D
            fcb $04
            fcb $1C
            fcb $EE
            fcb $82
            fcb $05
            fcb $58
            fcb $96
            fcb $FF
            fcb $86
            fcb $A8
            fcb $70
            fcb $FF
            fcb $86
            fcb $D0
            fcb $5D
            fcb $00
            fcb $00
            fcb $E5
            fcb $5D
            fcb $04
            fcb $1C
            fcb $EE
            fcb $82
            fcb $03
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
byte_8769:  fcb $67
byte_876A:  fcb $5D
            fcb $05
            fcb $32
            fcb $01
            fcb $00
            fcb $00
            fcb $4B
            fcb $02
            fcb $00
            fcb $00
            fcb $5A
            fcb $03
            fcb $00
            fcb $00
            fcb $78
            fcb $05
            fcb $00
            fcb $00
            fcb $96
            fcb $08
            fcb $05
            fcb $40
            fcb $FF
            fcb $00
            fcb $00
            fcb $A0
            fcb $FF
            fcb $00
            fcb $00
            fcb $C8
            fcb $FF
            fcb $00
            fcb $00
            fcb $E6
            fcb $FF
            fcb $00
            fcb $00
            fcb $FF
            fcb $FF
byte_8791:  fcb $0A
byte_8792:  fcb $0A
byte_8793:  fcb $EB
            fcb $1A
            fcb $1A
            fcb $1A
            fcb $1A
            fcb $1A
            fcb $1A
            fcb $16
            fcb $14
            fcb $14
byte_879D:  fcb $25
            fcb $1A
            fcb $1A
            fcb $1A
            fcb $1A
            fcb $1A
            fcb $1A
            fcb $16
            fcb $14
            fcb $14
byte_87A7:  fcb $38
byte_87A8:  fcb $DB
            fcb $40
            fcb $50
byte_87AB:  fcb $7F
byte_87AC:  fcb $10
byte_87AD:  fcb $08
            fcb $03
            fcb $58
            fcb $F0
            fcb $00
            fcb $00
            fcb $A8
            fcb $F0
            fcb $00
            fcb $00
            fcb $F8
            fcb $F0
            fcb $03
            fcb $58
            fcb $10
            fcb $00
            fcb $00
            fcb $A8
            fcb $10
            fcb $00
            fcb $00
            fcb $F8
            fcb $10
            fcb $04
            fcb $9A
            fcb $E8
            fcb $00
            fcb $36
            fcb $AD
            fcb $EC
            fcb $00
            fcb $00
            fcb $C8
            fcb $EC
            fcb $00
            fcb $80
            fcb $F0
            fcb $00
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $02
            fcb $0B
            fcb $00
            fcb $00
            fcb $00
            fcb $1B
            fcb $00
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $04
            fcb $58
            fcb $30
            fcb $FF
            fcb $B3
            fcb $80
            fcb $24
            fcb $FF
            fcb $80
            fcb $A8
            fcb $10
            fcb $FF
            fcb $9A
            fcb $D0
            fcb $00
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $04
            fcb $1F
            fcb $00
            fcb $00
            fcb $00
            fcb $46
            fcb $00
            fcb $00
            fcb $00
            fcb $6D
            fcb $00
            fcb $00
            fcb $00
            fcb $BC
            fcb $00
            fcb $03
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $8F
            fcb $00
            fcb $00
            fcb $00
            fcb $FF
            fcb $00
            fcb $02
            fcb $90
            fcb $FF
            fcb $00
            fcb $00
            fcb $C7
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $04
            fcb $08
            fcb $00
            fcb $00
            fcb $80
            fcb $0C
            fcb $02
            fcb $00
            fcb $40
            fcb $10
            fcb $03
            fcb $00
            fcb $40
            fcb $18
            fcb $05
            fcb $04
            fcb $08
            fcb $00
            fcb $FF
            fcb $C0
            fcb $0C
            fcb $FF
            fcb $FF
            fcb $C0
            fcb $10
            fcb $FE
            fcb $FF
            fcb $E0
            fcb $18
            fcb $FD
byte_8838:  fcb $3F
byte_8839:  fcb $D6
byte_883A:  fcb $02
byte_883B:  fcb $12
byte_883C:  fcb $1E
byte_883D:  fcb $03
byte_883E:  fcb $0B
byte_883F:  fcb $7F
byte_8840:  fcb $00
byte_8841:  fcb $00
word_8842:  fdb $0FAD
byte_8844:  fcb $70
byte_8845:  fcb $8C
byte_8846:  fcb $70
byte_8847:  fcb $FF
word_8848:  fdb $FF00
word_884A:  fdb $FF00
byte_884C:  fcb $00
byte_884D:  fcb $B6
byte_884E:  fcb $07
byte_884F:  fcb $10
byte_8850:  fcb $FE
byte_8851:  fcb $FE
byte_8852:  fcb $10
byte_8853:  fcb $0A
byte_8854:  fcb $04
byte_8855:  fcb $70
byte_8856:  fcb $03
byte_8857:  fcb $58
byte_8858:  fcb $FF
byte_8859:  fcb $5A
byte_885A:  fcb $46
            fcb $E8
            fcb $E3
            fcb $E8
            fcb $E3
word_885F:  fdb $13E2
word_8861:  fdb $0100
byte_8863:  fcb $25
byte_8864:  fcb $C0
byte_8865:  fcb $92
byte_8866:  fcb $00
byte_8867:  fcb $20
byte_8868:  fcb $32
byte_8869:  fcb $00
byte_886A:  fcb $06
byte_886B:  fcb $40
            fcb $06
            fcb $1C
            fcb $24
            fcb $00
            fcb $E7
            fcb $3B
            fcb $40
            fcb $05
            fcb $C0
            fcb $3F
            fcb $57
            fcb $06
            fcb $AB
            fcb $42
            fcb $6B
            fcb $00
            fcb $00
            fcb $54
            fcb $6B
            fcb $00
            fcb $00
            fcb $54
            fcb $A8
            fcb $04
            fcb $1F
            fcb $0F
            fcb $00
            fcb $F7
            fcb $74
            fcb $61
            fcb $00
            fcb $00
            fcb $8A
            fcb $61
            fcb $00
            fcb $00
            fcb $8A
            fcb $A8
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $04
            fcb $1F
            fcb $0F
            fcb $00
            fcb $F7
            fcb $74
            fcb $61
            fcb $00
            fcb $00
            fcb $8A
            fcb $61
            fcb $00
            fcb $00
            fcb $8A
            fcb $A8
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
byte_88B1:  fcb $B8
byte_88B2:  fcb $07
byte_88B3:  fcb $7C
byte_88B4:  fcb $14
byte_88B5:  fcb $66
            fcb $81
            fcb $18
byte_88B8:  fcb $20
byte_88B9:  fcb $11
byte_88BA:  fcb $00
            fcb $04
            fcb $64
            fcb $0F
            fcb $00
            fcb $00
            fcb $64
            fcb $2E
            fcb $00
            fcb $AB
            fcb $82
            fcb $42
            fcb $00
            fcb $00
            fcb $82
            fcb $A8
            fcb $02
            fcb $64
            fcb $0F
            fcb $00
            fcb $00
            fcb $96
            fcb $0F
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $04
            fcb $5E
            fcb $05
            fcb $00
            fcb $00
            fcb $5E
            fcb $33
            fcb $00
            fcb $AB
            fcb $7C
            fcb $47
            fcb $00
            fcb $00
            fcb $7C
            fcb $A8
            fcb $02
            fcb $5E
            fcb $05
            fcb $00
            fcb $00
            fcb $96
            fcb $05
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
byte_88F7:  fcb $50
TL_TL_88E4: fcb $2D
byte_88F9:  fcb $28
byte_88FA:  fcb $0A
byte_88FB:  fcb $06
byte_88FC:  fcb $05
byte_88FD:  fcb $10
byte_88FE:  fcb $0F
byte_88FF:  fcb $50
byte_8900:  fcb $08
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $41
            fcb $41
            fcb $3F
            fcb $3C
            fcb $40
            fcb $40
byte_890A:  fcb $08
byte_890B:  fcb $0D
byte_890C:  fcb $80
byte_890D:  fcb $FE
byte_890E:  fcb $F0
byte_890F:  fcb $00
byte_8910:  fcb $40
byte_8911:  fcb $30
byte_8912:  fcb $00
byte_8913:  fcb $94
byte_8914:  fcb $AA
byte_8915:  fcb $46
byte_8916:  fcb $4F
byte_8917:  fcb $00
byte_8918:  fcb $3C
byte_8919:  fcb $9A
byte_891A:  fcb $08
            fcb $04
            fcb $2D
byte_891D:  fcb $20
byte_891E:  fcb $20
byte_891F:  fcb $02
byte_8920:  fcb $01
byte_8921:  fcb $01
byte_8922:  fcb $05
byte_8923:  fcb $05
byte_8924:  fcb $80
byte_8925:  fcb $06
byte_8926:  fcb $04
byte_8927:  fcb $18
byte_8928:  fcb $06
byte_8929:  fcb $74
byte_892A:  fcb $02
byte_892B:  fcb $04
byte_892C:  fcb $10
byte_892D:  fcb $F0
byte_892E:  fcb $04
byte_892F:  fcb $04
byte_8930:  fcb $28
byte_8931:  fcb $D8
byte_8932:  fcb $0B
byte_8933:  fcb $08
            fcb $04
            fcb $00
            fcb $00
            fcb $FF
            fcb $FB
            fcb $30
            fcb $FF
            fcb $FF
            fcb $F6
            fcb $80
            fcb $FC
            fcb $FF
            fcb $EC
            fcb $FF
            fcb $F2
            fcb $05
            fcb $00
            fcb $00
            fcb $00
            fcb $30
            fcb $10
            fcb $03
            fcb $00
            fcb $1B
            fcb $40
            fcb $08
            fcb $00
            fcb $20
            fcb $80
            fcb $10
            fcb $00
            fcb $0C
            fcb $FF
            fcb $16
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $04
            fcb $00
            fcb $00
            fcb $01
            fcb $00
            fcb $10
            fcb $10
            fcb $00
            fcb $C0
            fcb $30
            fcb $28
            fcb $00
            fcb $20
            fcb $70
            fcb $30
            fcb $04
            fcb $00
            fcb $00
            fcb $00
            fcb $B3
            fcb $3C
            fcb $2A
            fcb $00
            fcb $1A
            fcb $5A
            fcb $2D
            fcb $00
            fcb $26
            fcb $6E
            fcb $30
            fcb $05
            fcb $00
            fcb $C0
            fcb $FF
            fcb $55
            fcb $30
            fcb $A0
            fcb $FF
            fcb $9A
            fcb $80
            fcb $80
            fcb $FF
            fcb $55
            fcb $B0
            fcb $60
            fcb $FF
            fcb $00
            fcb $D0
            fcb $40
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $04
            fcb $80
            fcb $80
            fcb $01
            fcb $00
            fcb $84
            fcb $84
            fcb $00
            fcb $20
            fcb $94
            fcb $86
            fcb $00
            fcb $14
            fcb $C6
            fcb $8A
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $04
            fcb $46
            fcb $04
            fcb $FF
            fcb $F3
            fcb $5A
            fcb $03
            fcb $FF
            fcb $F3
            fcb $6E
            fcb $02
            fcb $FF
            fcb $E6
            fcb $82
            fcb $00
            fcb $04
            fcb $00
            fcb $06
            fcb $00
            fcb $E0
            fcb $10
            fcb $14
            fcb $00
            fcb $90
            fcb $20
            fcb $1D
            fcb $00
            fcb $30
            fcb $30
            fcb $20
            fcb $03
            fcb $02
            fcb $18
            fcb $10
            fcb $00
            fcb $04
            fcb $38
            fcb $08
            fcb $00
            fcb $06
            fcb $48
            fcb $02
            fcb $20
            fcb $E8
            fcb $FE
            fcb $80
            fcb $30
            fcb $D0
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $02
            fcb $A0
            fcb $03
            fcb $00
            fcb $18
            fcb $C0
            fcb $06
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $02
            fcb $A8
            fcb $80
            fcb $FE
            fcb $ED
            fcb $D0
            fcb $55
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $02
            fcb $60
            fcb $00
            fcb $00
            fcb $00
            fcb $40
            fcb $00
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $02
            fcb $A8
            fcb $00
            fcb $00
            fcb $00
            fcb $D0
            fcb $00
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
byte_8A12:  fcb $02
            fcb $20
            fcb $0D
word_8A15:  fdb $000C
word_8A17:  fdb $2000
byte_8A19:  fcb $02
byte_8A1A:  fcb $02
byte_8A1B:  fcb $80
byte_8A1C:  fcb $00
byte_8A1D:  fcb $00
            fcb $10
            fcb $10
            fcb $10
            fcb $10
            fcb $10
            fcb $10
            fcb $10
            fcb $10
            fcb $10
byte_8A27:  fcb $00
byte_8A28:  fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $26
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
byte_8A38:  fcb $04
byte_8A39:  fcb $11
byte_8A3A:  fcb $EB
byte_8A3B:  fcb $93
byte_8A3C:  fcb $7E
TL_TstatDiagnosticsMinTempToArmDiagnosticsAtStartup:fcb $63
TL_TstatDiagnosticsMaxTempToArmDiagnosticsAtStartup:fcb $E4
byte_8A3F:  fcb $CF
byte_8A40:  fcb $32
byte_8A41:  fcb $AA
byte_8A42:  fcb $04
byte_8A43:  fcb $BD
byte_8A44:  fcb $79
TL_CoolantTempOutOfRangeLow:fcb $1A
TL_CoolantTempOutOfRangeHigh:fcb $FD
TL_DefaultCoolantTempRaw:fcb $B1

TL_ChargeTempOutOfRangeLow:fcb $1A
TL_ChargeTempOutOfRangeHigh:fcb $FD

TL_DefaultChargeTemp_Limpin:fcb $B1

byte_8A4B:  fcb $10
word_8A4C:  fdb $2EE0
byte_8A4E:  fcb $8E
byte_8A4F:  fcb $7F
byte_8A50:  fcb $04
byte_8A51:  fcb $06
byte_8A52:  fcb $2E
byte_8A53:  fcb $22
byte_8A54:  fcb $14
byte_8A55:  fcb $0A
byte_8A56:  fcb $38
byte_8A57:  fcb $70
byte_8A58:  fcb $B0
byte_8A59:  fcb $08
byte_8A5A:  fcb $F0
byte_8A5B:  fcb $D1
byte_8A5C:  fcb $20
byte_8A5D:  fcb $28
byte_8A5E:  fcb $2F
byte_8A5F:  fcb $28
byte_8A60:  fcb $DC
byte_8A61:  fcb $8C
byte_8A62:  fcb $64
byte_8A63:  fcb $CE
TL_t3_0xfd: fcb $AB
byte_8A65:  fcb $02
byte_8A66:  fcb $FD
TL_MapSensorMiddleLimit:fcb $66
byte_8A68:  fcb $01
byte_8A69:  fcb $02
byte_8A6A:  fcb $05
            fcb $F0
            fcb $80
            fcb $50
            fcb $40
            fcb $30
            fcb $30
            fcb $20
            fcb $20
            fcb $20
            fcb $10
            fcb $10
            fcb $10
            fcb $10
            fcb $00
            fcb $00
            fcb $00
word_8A7B:  fdb $12C0
word_8A7D:  fdb $2EE0
byte_8A7F:  fcb $12
byte_8A80:  fcb $F7
word_8A81:  fdb $0200
byte_8A83:  fcb $CE
            fcb $21
            fcb $10
            fcb $05
            fcb $00
            fcb $00
            fcb $07
            fcb $92
            fcb $07
            fcb $35
            fcb $04
            fcb $64
            fcb $19
            fcb $84
            fcb $01
            fcb $66
            fcb $28
            fcb $99
            fcb $00
            fcb $95
            fcb $34
            fcb $A0
byte_8A99:  fcb $2E
byte_8A9A:  fcb $0B
byte_8A9B:  fcb $20
byte_8A9C:  fcb $03
byte_8A9D:  fcb $D2
byte_8A9E:  fcb $05
byte_8A9F:  fcb $20
byte_8AA0:  fcb $40
byte_8AA1:  fcb $10
byte_8AA2:  fcb $D0
byte_8AA3:  fcb $70
byte_8AA4:  fcb $60
byte_8AA5:  fcb $30
byte_8AA6:  fcb $C0
word_8AA7:  fdb $01B0
byte_8AA9:  fcb $44
byte_8AAA:  fcb $51
byte_8AAB:  fcb $22
byte_8AAC:  fcb $2E
byte_8AAD:  fcb $71
byte_8AAE:  fcb $B0
byte_8AAF:  fcb $80
byte_8AB0:  fcb $20
word_8AB1:  fdb $016C
byte_8AB3:  fcb $03
word_8AB4:  fdb $FFFF
byte_8AB6:  fcb $23
byte_8AB7:  fcb $FF
byte_8AB8:  fcb $C0
byte_8AB9:  fcb $DA
            fcb $05
            fcb $09
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $00
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
            fcb $FF
word_8B56:  fdb $0002

;------------------------------------------------------------------------------
;---0x8A8 bytes of padding removed---------------------------------------------
;------------------------------------------------------------------------------

