tl_ident1:
byte_8000:	fcb 1
		fcb   0
unk_8002:	fcb $56
		fcb   2
		fcb $88
byte_8005:	fcb $28
byte_8006:	fcb $A1
unk_8007:	fcb $56
		fcb   2
		fcb $88
		fcb $28
byte_800B:	fcb $A1
		fcb $8D
unk_800D:	fcb $4E
		fcb $18
byte_800F:	fcb $15
		fcb $88
byte_8011:	fcb 1
word_8012:	fdb $102
byte_8014:	fcb $FF
byte_8015:	fcb $81
byte_8016:	fcb $22
byte_8017:	fcb 3
byte_8018:	fcb $10
byte_8019:	fcb 2
byte_801A:	fcb 1
byte_801B:	fcb $5C
byte_801C:	fcb $26
byte_801D:	fcb $4C
byte_801E:	fcb 4
byte_801F:	fcb $90
byte_8020:	fcb $D0
byte_8021:	fcb 0
word_8022:	fdb 0
unk_8024:	fcb   5
		fcb $1F
		fcb   0
		fcb   0
		fcb $42
		fcb $3E
		fcb   8
		fcb   0
		fcb   8
		fcb $5E
		fcb   9
		fcb $FF
		fcb $B6
		fcb $7D
		fcb   0
		fcb   0
		fcb $53
		fcb $9C
		fcb  $A
byte_8037:	fcb $90
byte_8038:	fcb $20
		fcb  $F
		fcb $A0
		fcb $14
		fcb $50
		fcb $17
		fcb $70
		fcb $20
		fcb $D0
		fcb $23
		fcb $F0
		fcb $2E
		fcb $E0
		fcb $3E
		fcb $80
		fcb $4E
		fcb $20
		fcb $5D
		fcb $C0
		fcb $6D
		fcb $60
		fcb $7D
		fcb   0
		fcb $8C
		fcb $A0
		fcb $9C
		fcb $40
unk_8053:	fcb   3
		fcb $13
		fcb   0
		fcb   5
		fcb $25
		fcb $2F
		fcb $90
		fcb   1
		fcb   5
		fcb $9C
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
word_8072:	fdb $393
byte_8074:	fcb $87
		fcb   0
word_8076:	fdb 3
byte_8078:	fcb $93
		fcb $87
word_807A:	fdb $53B5
word_807C:	fdb $7530
byte_807E:	fcb 0
byte_807F:	fcb $14
byte_8080:	fcb 2
byte_8081:	fcb 4
byte_8082:	fcb 5
unk_8083:	fcb $11
		fcb   9
		fcb   0
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb  $E
		fcb   8
		fcb   8
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb  $E
		fcb  $A
		fcb  $A
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $20
		fcb $20
		fcb $14
		fcb  $C
		fcb  $A
		fcb $1C
		fcb $1C
		fcb $1E
		fcb $20
		fcb $25
		fcb $25
		fcb $16
		fcb  $D
		fcb  $B
		fcb $1C
		fcb $1C
		fcb $1F
		fcb $31
		fcb $2D
		fcb $27
		fcb $17
		fcb  $E
		fcb $10
		fcb $1C
		fcb $1C
		fcb $20
		fcb $3C
		fcb $2B
		fcb $29
		fcb $1A
		fcb $10
		fcb $12
		fcb $1C
		fcb $1C
		fcb $26
		fcb $3D
		fcb $32
		fcb $2C
		fcb $1E
		fcb $10
		fcb $10
		fcb $1C
		fcb $2C
		fcb $36
		fcb $36
		fcb $34
		fcb $2F
		fcb $20
		fcb $16
		fcb $13
		fcb $1C
		fcb $2C
		fcb $36
		fcb $3B
		fcb $38
		fcb $30
		fcb $21
		fcb $1B
		fcb $14
		fcb $1C
		fcb $2C
		fcb $36
		fcb $43
		fcb $39
		fcb $33
		fcb $22
		fcb $1B
		fcb $15
		fcb $1C
		fcb $2C
		fcb $36
		fcb $47
		fcb $45
		fcb $42
		fcb $2D
		fcb $24
		fcb $24
		fcb $1C
		fcb $2C
		fcb $3A
		fcb $55
		fcb $51
		fcb $49
		fcb $37
		fcb $23
		fcb $23
		fcb $1C
		fcb $2C
		fcb $3A
		fcb $56
		fcb $52
		fcb $4A
		fcb $3D
		fcb $23
		fcb $23
		fcb $1C
		fcb $2C
		fcb $3C
		fcb $58
		fcb $52
		fcb $4A
		fcb $3F
		fcb $31
		fcb $24
		fcb $1C
		fcb $2C
		fcb $40
		fcb $53
		fcb $55
		fcb $49
		fcb $46
		fcb $42
		fcb $3B
		fcb $1C
		fcb $2C
		fcb $3C
		fcb $4B
		fcb $47
		fcb $49
		fcb $48
		fcb $42
		fcb $3C
		fcb $1C
		fcb $2C
		fcb $3C
		fcb $58
		fcb $52
		fcb $4D
		fcb $48
		fcb $3F
		fcb $3A
unk_811F:	fcb $11
		fcb   9
		fcb   0
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb  $E
		fcb   8
		fcb   8
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb  $E
		fcb  $A
		fcb  $A
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $12
		fcb  $A
		fcb  $A
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $16
		fcb  $C
		fcb  $A
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $24
		fcb $18
		fcb  $C
		fcb  $A
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $2C
		fcb $1C
		fcb $12
		fcb $10
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $2A
		fcb $28
		fcb $18
		fcb $12
		fcb $10
		fcb $1C
		fcb $4C
		fcb $4A
		fcb $40
		fcb $36
		fcb $2C
		fcb $1C
		fcb $12
		fcb $10
		fcb $1C
		fcb $4C
		fcb $48
		fcb $4D
		fcb $36
		fcb $34
		fcb $24
		fcb $12
		fcb $10
		fcb $1C
		fcb $4C
		fcb $48
		fcb $4A
		fcb $48
		fcb $44
		fcb $2B
		fcb $12
		fcb $12
		fcb $1C
		fcb $4C
		fcb $48
		fcb $4E
		fcb $4D
		fcb $48
		fcb $33
		fcb $1F
		fcb $17
		fcb $1C
		fcb $4C
		fcb $48
		fcb $50
		fcb $4B
		fcb $44
		fcb $42
		fcb $32
		fcb $21
		fcb $1C
		fcb $4C
		fcb $54
		fcb $54
		fcb $56
		fcb $54
		fcb $42
		fcb $2A
		fcb $21
		fcb $1C
		fcb $4C
		fcb $5B
		fcb $58
		fcb $58
		fcb $54
		fcb $47
		fcb $28
		fcb $21
		fcb $1C
		fcb $4C
		fcb $4D
		fcb $50
		fcb $4D
		fcb $47
		fcb $32
		fcb $26
		fcb $23
		fcb $1C
		fcb $4C
		fcb $4D
		fcb $50
		fcb $4B
		fcb $3E
		fcb $2E
		fcb $28
		fcb $25
		fcb $1C
		fcb $4C
		fcb $4D
		fcb $50
		fcb $4B
		fcb $3E
		fcb $2E
		fcb $28
		fcb $25
byte_81BB:	fcb 3
unk_81BC:	fcb $11
		fcb   9
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
unk_8258:	fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $98
		fcb $98
		fcb $98
		fcb $98
		fcb $98
		fcb $98
		fcb $98
unk_8266:	fcb $28
		fcb $26
		fcb $24
		fcb $20
		fcb $20
		fcb $20
		fcb $20
		fcb $20
		fcb $1A
unk_826F:	fcb $26
		fcb $24
		fcb $22
		fcb $20
		fcb $20
		fcb $1A
		fcb $14
		fcb $14
		fcb $14
byte_8278:	fcb $D0
byte_8279:	fcb 6
byte_827A:	fcb $14
byte_827B:	fcb $1C
unk_827C:	fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
unk_8285:	fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
word_828E:	fdb $1B3
		fcb   2
		fcb   0
		fcb $FF
		fcb   0
		fcb   0
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
word_82AF:	fdb $30D4
word_82B1:	fdb $7530
unk_82B3:	fcb $11
		fcb   9
		fcb   0
		fcb $3E
		fcb $3E
		fcb $3E
		fcb $3E
		fcb $3E
		fcb $3E
		fcb $42
		fcb $52
		fcb $6C
		fcb $50
		fcb $50
		fcb $4A
		fcb $4A
		fcb $4A
		fcb $50
		fcb $50
		fcb $60
		fcb $80
		fcb $50
		fcb $50
		fcb $4A
		fcb $50
		fcb $57
		fcb $58
		fcb $5C
		fcb $69
		fcb $8D
		fcb $4A
		fcb $60
		fcb $5B
		fcb $64
		fcb $6A
		fcb $68
		fcb $68
		fcb $6B
		fcb $86
		fcb $7A
		fcb $7A
		fcb $8E
		fcb $7D
		fcb $73
		fcb $70
		fcb $70
		fcb $6D
		fcb $80
		fcb $8A
		fcb $8A
		fcb $95
		fcb $7E
		fcb $7B
		fcb $74
		fcb $72
		fcb $76
		fcb $7A
		fcb $90
		fcb $9A
		fcb $9D
		fcb $8C
		fcb $7F
		fcb $7A
		fcb $77
		fcb $77
		fcb $7A
		fcb $A0
		fcb $9A
		fcb $9D
		fcb $88
		fcb $7D
		fcb $7A
		fcb $79
		fcb $7A
		fcb $79
		fcb $A0
		fcb $A0
		fcb $9D
		fcb $91
		fcb $80
		fcb $7B
		fcb $7A
		fcb $7C
		fcb $78
		fcb $A0
		fcb $B0
		fcb $9D
		fcb $86
		fcb $7A
		fcb $7D
		fcb $7A
		fcb $7C
		fcb $7E
		fcb $A0
		fcb $B0
		fcb $9D
		fcb $88
		fcb $7C
		fcb $7F
		fcb $7B
		fcb $7C
		fcb $A0
		fcb $A0
		fcb $CC
		fcb $98
		fcb $84
		fcb $7D
		fcb $7F
		fcb $8A
		fcb $8A
		fcb $E4
		fcb $A0
		fcb $E7
		fcb $99
		fcb $88
		fcb $7E
		fcb $7E
		fcb $8A
		fcb $E3
		fcb $E3
		fcb $A0
		fcb $D5
		fcb $A2
		fcb $91
		fcb $86
		fcb $87
		fcb $8E
		fcb $F9
		fcb $AC
		fcb $A0
		fcb $DC
		fcb $B2
		fcb $A2
		fcb $97
		fcb $99
		fcb $95
		fcb $95
		fcb $8F
		fcb $A0
		fcb $90
		fcb $D5
		fcb $C3
		fcb $B4
		fcb $A9
		fcb $A5
		fcb $C9
		fcb $9B
		fcb $A0
		fcb $90
		fcb $E1
		fcb $D1
		fcb $C6
		fcb $BE
		fcb $B7
		fcb $DA
		fcb $AA
unk_834F:	fcb $11
		fcb   9
		fcb   0
		fcb $38
		fcb $38
		fcb $38
		fcb $38
		fcb $38
		fcb $38
		fcb $38
		fcb $38
		fcb $38
		fcb $38
		fcb $38
		fcb $38
		fcb $38
		fcb $38
		fcb $38
		fcb $3F
		fcb $3F
		fcb $3F
		fcb $40
		fcb $40
		fcb $40
		fcb $40
		fcb $40
		fcb $40
		fcb $43
		fcb $43
		fcb $43
		fcb $46
		fcb $46
		fcb $46
		fcb $46
		fcb $46
		fcb $46
		fcb $46
		fcb $46
		fcb $46
		fcb $44
		fcb $44
		fcb $44
		fcb $57
		fcb $43
		fcb $42
		fcb $47
		fcb $47
		fcb $47
		fcb $48
		fcb $48
		fcb $4B
		fcb $58
		fcb $45
		fcb $42
		fcb $4A
		fcb $4A
		fcb $4A
		fcb $5F
		fcb $5F
		fcb $5F
		fcb $58
		fcb $32
		fcb $36
		fcb $3E
		fcb $5C
		fcb $4E
		fcb $62
		fcb $64
		fcb $6D
		fcb $31
		fcb $32
		fcb $36
		fcb $43
		fcb $5C
		fcb $5C
		fcb $65
		fcb $68
		fcb $46
		fcb $3C
		fcb $3C
		fcb $3E
		fcb $45
		fcb $62
		fcb $62
		fcb $6B
		fcb $6B
		fcb $50
		fcb $3A
		fcb $35
		fcb $39
		fcb $45
		fcb $5E
		fcb $60
		fcb $6B
		fcb $6B
		fcb $49
		fcb $45
		fcb $42
		fcb $4A
		fcb $53
		fcb $6B
		fcb $6B
		fcb $50
		fcb $50
		fcb $4D
		fcb $43
		fcb $49
		fcb $50
		fcb $55
		fcb $6C
		fcb $6C
		fcb $48
		fcb $48
		fcb $46
		fcb $48
		fcb $4C
		fcb $54
		fcb $5A
		fcb $6E
		fcb $6E
		fcb $4A
		fcb $4A
		fcb $49
		fcb $49
		fcb $4E
		fcb $55
		fcb $59
		fcb $67
		fcb $67
		fcb $4C
		fcb $4C
		fcb $4C
		fcb $4B
		fcb $51
		fcb $57
		fcb $59
		fcb $59
		fcb $59
		fcb $4D
		fcb $4D
		fcb $4D
		fcb $55
		fcb $5D
		fcb $60
		fcb $70
		fcb $70
		fcb $70
		fcb $4A
		fcb $4A
		fcb $4A
		fcb $55
		fcb $5F
		fcb $5E
		fcb $5F
		fcb $5F
		fcb $5F
unk_83EB:	fcb $D0
		fcb $A4
		fcb $74
		fcb $13
		fcb  $C
		fcb  $A
		fcb   4
		fcb   4
		fcb   4
unk_83F4:	fcb $14
		fcb $14
		fcb $14
		fcb $14
		fcb $10
		fcb  $A
		fcb   3
		fcb   3
		fcb   3
unk_83FD:	fcb $CA
		fcb $88
		fcb $58
		fcb $2A
		fcb $23
		fcb  $F
		fcb   5
		fcb   0
		fcb   0
unk_8406:	fcb $50
		fcb $48
		fcb $34
		fcb $1E
		fcb $10
		fcb   8
		fcb   0
		fcb   0
		fcb   0
unk_840F:	fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb $40
		fcb $80
		fcb $80
		fcb $80
unk_8418:	fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
unk_8421:	fcb $40
		fcb $40
		fcb $30
		fcb $2E
		fcb $28
		fcb $20
		fcb $1A
		fcb   8
		fcb   8
byte_842A:	fcb 0
unk_842B:	fcb   2
		fcb $58
		fcb   0
		fcb   0
		fcb   0
		fcb $FF
		fcb   0
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
unk_843E:	fcb   8
		fcb $61
		fcb $80
		fcb $FF
		fcb $30
		fcb $71
		fcb $73
		fcb $FD
		fcb $60
		fcb $81
		fcb $49
		fcb $FE
		fcb $4B
		fcb $92
		fcb $2C
		fcb $FE
		fcb $C0
		fcb $A2
		fcb $18
		fcb $FF
		fcb $70
		fcb $C2
		fcb   6
		fcb $FF
		fcb $E9
		fcb $E3
		fcb   3
		fcb $FF
		fcb $E5
		fcb $FF
		fcb   0
unk_845D:	fcb $F8
		fcb $C0
		fcb $6A
		fcb $2D
		fcb $28
		fcb $25
		fcb $14
		fcb $14
		fcb $14
unk_8466:	fcb $CC
		fcb $CC
		fcb $CC
		fcb $CC
		fcb $CC
		fcb $CC
		fcb $E6
		fcb $FF
		fcb $FF
unk_846F:	fcb   4
		fcb  $C
		fcb   0
		fcb   0
		fcb $AB
		fcb $30
		fcb $18
		fcb   0
		fcb $D5
		fcb $60
		fcb $40
		fcb   2
		fcb   0
		fcb $80
		fcb $80
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
unk_8482:	fcb   2
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb $FF
		fcb   0
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
word_8495:	fdb $8000
byte_8497:	fcb $D0
byte_8498:	fcb $D0
byte_8499:	fcb 4
unk_849A:	fcb $10
		fcb $10
		fcb $10
		fcb $10
		fcb $12
		fcb $18
		fcb $1C
		fcb $1C
		fcb $1C
unk_84A3:	fcb $10
		fcb $10
		fcb $10
		fcb  $B
		fcb   8
		fcb   8
		fcb   4
		fcb   4
		fcb   4
unk_84AC:	fcb $20
		fcb $20
		fcb $20
		fcb $18
		fcb $18
		fcb $18
		fcb $18
		fcb $18
		fcb $18
unk_84B5:	fcb $CF
		fcb $A0
		fcb $7D
		fcb $32
		fcb $2A
		fcb $28
		fcb $1C
		fcb $1C
		fcb $16
unk_84BE:	fcb $60
		fcb $50
		fcb $40
		fcb $32
		fcb $2C
		fcb $28
		fcb $10
		fcb $10
		fcb $10
unk_84C7:	fcb $20
		fcb $20
		fcb $20
		fcb $20
		fcb $20
		fcb $40
		fcb $40
		fcb $40
		fcb $40
unk_84D0:	fcb $80
		fcb $80
byte_84D2:	fcb $96
byte_84D3:	fcb $60
byte_84D4:	fcb $9F
unk_84D5:	fcb $20
		fcb $20
word_84D7:	fdb 1
word_84D9:	fdb $FFD6
word_84DB:	fdb $219
byte_84DD:	fcb $99
byte_84DE:	fcb $99
unk_84DF:	fcb $40
		fcb $40
byte_84E1:	fcb $F0
unk_84E2:	fcb $28
		fcb $28
		fcb $24
		fcb $1D
		fcb $1B
		fcb $18
		fcb $18
		fcb $18
		fcb $18
byte_84EB:	fcb $10
word_84EC:	fdb $24F
unk_84EE:	fcb   4
		fcb $13
		fcb   0
		fcb  $A
		fcb $AB
		fcb $1F
		fcb $80
		fcb   2
		fcb $11
		fcb $3E
		fcb $C0
		fcb   1
		fcb $57
		fcb $6D
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
unk_850D:	fcb   5
		fcb   9
		fcb   0
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $1C
		fcb $18
		fcb $18
		fcb $18
		fcb $18
		fcb $18
		fcb $18
		fcb $18
		fcb $18
		fcb $18
		fcb $18
		fcb $18
		fcb $18
		fcb $18
		fcb $18
		fcb $18
		fcb $18
		fcb $18
		fcb $18
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
unk_85A9:	fcb   5
		fcb   9
		fcb   0
		fcb $22
		fcb $22
		fcb $22
		fcb $22
		fcb $22
		fcb $22
		fcb $22
		fcb $22
		fcb $22
		fcb $22
		fcb $22
		fcb $22
		fcb $22
		fcb $22
		fcb $22
		fcb $22
		fcb $22
		fcb $22
		fcb $22
		fcb $22
		fcb $22
		fcb $22
		fcb $22
		fcb $22
		fcb $22
		fcb $22
		fcb $22
		fcb $20
		fcb $20
		fcb $20
		fcb $20
		fcb $20
		fcb $20
		fcb $20
		fcb $20
		fcb $20
		fcb $20
		fcb $20
		fcb $20
		fcb $20
		fcb $20
		fcb $20
		fcb $20
		fcb $20
		fcb $20
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
byte_8645:	fcb $B
byte_8646:	fcb $10
byte_8647:	fcb $20
byte_8648:	fcb $20
byte_8649:	fcb 4
byte_864A:	fcb 2
byte_864B:	fcb $60
byte_864C:	fcb 1
byte_864D:	fcb $FE
byte_864E:	fcb $29
unk_864F:	fcb $40
byte_8650:	fcb $B
byte_8651:	fcb 5
byte_8652:	fcb $8C
unk_8653:	fcb $C0
byte_8654:	fcb $B
byte_8655:	fcb $15
		fcb $20
byte_8657:	fcb $26
byte_8658:	fcb $10
byte_8659:	fcb $A0
unk_865A:	fcb $C0
		fcb $C0
byte_865C:	fcb $D6
byte_865D:	fcb 8
byte_865E:	fcb $2C
byte_865F:	fcb $74
byte_8660:	fcb $FF
byte_8661:	fcb 1
byte_8662:	fcb $38
unk_8663:	fcb $10
		fcb   7
		fcb $A0
		fcb   0
		fcb $C0
unk_8668:	fcb   8
		fcb   3
		fcb $90
		fcb   0
		fcb $E0
byte_866D:	fcb $A8
byte_866E:	fcb $68
byte_866F:	fcb $10
byte_8670:	fcb 4
byte_8671:	fcb $58
byte_8672:	fcb $17
byte_8673:	fcb $85
byte_8674:	fcb $32
byte_8675:	fcb $24
byte_8676:	fcb $56
byte_8677:	fcb $F1
byte_8678:	fcb $17
word_8679:	fdb 1
byte_867B:	fcb $6E
byte_867C:	fcb $A0
word_867D:	fdb $384
byte_867F:	fcb 2
byte_8680:	fcb $C0
byte_8681:	fcb $F0
byte_8682:	fcb 3
byte_8683:	fcb 1
byte_8684:	fcb 8
byte_8685:	fcb $A
byte_8686:	fcb $9A
word_8687:	fdb 0
word_8689:	fdb $30A
byte_868B:	fcb 0
byte_868C:	fcb 2
word_868D:	fdb $2F0
word_868F:	fdb $9C40
word_8691:	fdb $190
byte_8693:	fcb $E0
byte_8694:	fcb 6
word_8695:	fdb $B220
word_8697:	fdb $190
byte_8699:	fcb $80
byte_869A:	fcb 1
word_869B:	fdb $B6
byte_869D:	fcb $F
byte_869E:	fcb $1C
byte_869F:	fcb $1C
unk_86A0:	fcb   2
		fcb   5
		fcb   0
		fcb   1
		fcb $6E
		fcb  $C
		fcb  $A
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
unk_86AB:	fcb   2
		fcb   5
		fcb   0
		fcb $FF
		fcb $9A
		fcb  $F
		fcb $FC
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
byte_86B6:	fcb $71
unk_86B7:	fcb   3
		fcb $D0
		fcb $D0
		fcb   0
		fcb   0
		fcb $D0
		fcb $D0
		fcb   0
		fcb   0
		fcb $D0
		fcb $D0
unk_86C2:	fcb   5
		fcb $58
		fcb $E0
		fcb $FE
		fcb $66
		fcb $80
		fcb $A0
		fcb $FD
		fcb $CD
		fcb $A8
		fcb $48
		fcb $FF
		fcb $9A
		fcb $D0
		fcb $38
		fcb   0
		fcb $CD
		fcb $F8
		fcb $58
unk_86D5:	fcb   3
		fcb $9A
		fcb $28
		fcb $FF
		fcb $7A
		fcb $C8
		fcb $10
		fcb $FF
		fcb $9A
		fcb $F0
		fcb   0
byte_86E0:	fcb $11
byte_86E1:	fcb $A0
byte_86E2:	fcb $20
byte_86E3:	fcb $D0
byte_86E4:	fcb $EE
unk_86E5:	fcb   4
		fcb $14
		fcb $14
		fcb $FF
		fcb $C0
		fcb $3C
		fcb  $A
		fcb $FF
		fcb $F3
		fcb $64
		fcb   8
		fcb $FF
		fcb $EF
		fcb $82
		fcb   6
byte_86F4:	fcb 0
unk_86F5:	fcb   4
		fcb $68
		fcb $50
		fcb $FF
		fcb $55
		fcb $80
		fcb $40
		fcb $FF
		fcb $33
		fcb $A8
		fcb $20
		fcb $FF
		fcb $33
		fcb $D0
		fcb   0
unk_8704:	fcb   3
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb $10
		fcb   0
		fcb   0
		fcb   0
		fcb $21
		fcb   0
unk_870F:	fcb   4
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   2
		fcb   0
		fcb   0
		fcb   0
		fcb   5
		fcb   0
		fcb   0
		fcb   0
		fcb $1E
		fcb   0
unk_871E:	fcb   4
		fcb $1C
		fcb   8
		fcb   0
		fcb   0
		fcb $2E
		fcb   8
		fcb   0
		fcb   0
		fcb $3F
		fcb   8
		fcb   0
		fcb   0
		fcb $FF
		fcb   8
unk_872D:	fcb   3
		fcb $9A
		fcb $50
		fcb $FF
		fcb $DF
		fcb $C8
		fcb $4A
		fcb $FF
		fcb $C0
		fcb $F0
		fcb $40
unk_8738:	fcb   5
		fcb $58
		fcb $96
		fcb $FF
		fcb $86
		fcb $A8
		fcb $70
		fcb $FF
		fcb $86
		fcb $D0
		fcb $5D
		fcb   0
		fcb   0
		fcb $E5
		fcb $5D
		fcb   4
		fcb $1C
		fcb $EE
		fcb $82
unk_874B:	fcb   5
		fcb $58
		fcb $96
		fcb $FF
		fcb $86
		fcb $A8
		fcb $70
		fcb $FF
		fcb $86
		fcb $D0
		fcb $5D
		fcb   0
		fcb   0
		fcb $E5
		fcb $5D
		fcb   4
		fcb $1C
		fcb $EE
		fcb $82
unk_875E:	fcb   3
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
byte_8769:	fcb $67
byte_876A:	fcb $5D
unk_876B:	fcb   5
		fcb $32
		fcb   1
		fcb   0
		fcb   0
		fcb $4B
		fcb   2
		fcb   0
		fcb   0
		fcb $5A
		fcb   3
		fcb   0
		fcb   0
		fcb $78
		fcb   5
		fcb   0
		fcb   0
		fcb $96
		fcb   8
unk_877E:	fcb   5
		fcb $40
		fcb $FF
		fcb   0
		fcb   0
		fcb $A0
		fcb $FF
		fcb   0
		fcb   0
		fcb $C8
		fcb $FF
		fcb   0
		fcb   0
		fcb $E6
		fcb $FF
		fcb   0
		fcb   0
		fcb $FF
		fcb $FF
byte_8791:	fcb $11
byte_8792:	fcb $11
byte_8793:	fcb $EE
unk_8794:	fcb $1A
		fcb $1A
		fcb $1A
		fcb $1A
		fcb $1A
		fcb $1A
		fcb $16
		fcb $14
		fcb $14
byte_879D:	fcb $1F
unk_879E:	fcb $1A
		fcb $1A
		fcb $1A
		fcb $1A
		fcb $1A
		fcb $1A
		fcb $16
		fcb $14
		fcb $14
byte_87A7:	fcb $38
byte_87A8:	fcb $DB
unk_87A9:	fcb $40
		fcb $50
byte_87AB:	fcb $7F
byte_87AC:	fcb $10
byte_87AD:	fcb 8
unk_87AE:	fcb   3
		fcb $58
		fcb $F0
		fcb   0
		fcb   0
		fcb $A8
		fcb $F0
		fcb   0
		fcb   0
		fcb $F8
		fcb $F0
unk_87B9:	fcb   3
		fcb $58
		fcb $10
		fcb   0
		fcb   0
		fcb $A8
		fcb $10
		fcb   0
		fcb   0
		fcb $F8
		fcb $10
unk_87C4:	fcb   4
		fcb $9A
		fcb $E8
		fcb   0
		fcb $36
		fcb $AD
		fcb $EC
		fcb   0
		fcb   0
		fcb $C8
		fcb $EC
		fcb   0
		fcb $80
		fcb $F0
		fcb   0
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
unk_87D7:	fcb   2
		fcb  $B
		fcb   0
		fcb   0
		fcb   0
		fcb $1B
		fcb   0
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
unk_87E2:	fcb   4
		fcb $58
		fcb $30
		fcb $FF
		fcb $B3
		fcb $80
		fcb $24
		fcb $FF
		fcb $80
		fcb $A8
		fcb $10
		fcb $FF
		fcb $9A
		fcb $D0
		fcb   0
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
unk_87F5:	fcb   4
		fcb $1F
		fcb   0
		fcb   0
		fcb   0
		fcb $46
		fcb   0
		fcb   0
		fcb   0
		fcb $6D
		fcb   0
		fcb   0
		fcb   0
		fcb $BC
		fcb   0
unk_8804:	fcb   3
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb $8F
		fcb   0
		fcb   0
		fcb   0
		fcb $FF
		fcb   0
unk_880F:	fcb   2
		fcb $90
		fcb $FF
		fcb   0
		fcb   0
		fcb $C7
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
unk_881A:	fcb   4
		fcb   8
		fcb   0
		fcb   0
		fcb $80
		fcb  $C
		fcb   2
		fcb   0
		fcb $40
		fcb $10
		fcb   3
		fcb   0
		fcb $40
		fcb $18
		fcb   5
unk_8829:	fcb   4
		fcb   8
		fcb   0
		fcb $FF
		fcb $C0
		fcb  $C
		fcb $FF
		fcb $FF
		fcb $C0
		fcb $10
		fcb $FE
		fcb $FF
		fcb $E0
		fcb $18
		fcb $FD
byte_8838:	fcb $3F
byte_8839:	fcb $D6
byte_883A:	fcb 2
byte_883B:	fcb $12
byte_883C:	fcb $1F
byte_883D:	fcb 0
byte_883E:	fcb $B
byte_883F:	fcb $7F
byte_8840:	fcb 0
byte_8841:	fcb 0
word_8842:	fdb $FAD
byte_8844:	fcb $70
byte_8845:	fcb $8C
byte_8846:	fcb $70
byte_8847:	fcb $FF
word_8848:	fdb $FF00
word_884A:	fdb $FF00
byte_884C:	fcb 4
byte_884D:	fcb $B6
byte_884E:	fcb 7
byte_884F:	fcb $10
byte_8850:	fcb $FE
byte_8851:	fcb $FE
byte_8852:	fcb $10
byte_8853:	fcb $A
byte_8854:	fcb 4
byte_8855:	fcb $70
byte_8856:	fcb 3
byte_8857:	fcb $58
byte_8858:	fcb $FF
byte_8859:	fcb $5A
byte_885A:	fcb $46
unk_885B:	fcb $E8
		fcb $E3
		fcb $E8
		fcb $E3
word_885F:	fdb $13E2
word_8861:	fdb $100
byte_8863:	fcb $25
byte_8864:	fcb $C0
byte_8865:	fcb $92
byte_8866:	fcb 0
byte_8867:	fcb $20
byte_8868:	fcb $32
byte_8869:	fcb 0
byte_886A:	fcb 6
byte_886B:	fcb $40
unk_886C:	fcb   6
		fcb $1C
		fcb $24
		fcb   0
		fcb $E7
		fcb $3B
		fcb $40
		fcb   5
		fcb $C0
		fcb $3F
		fcb $57
		fcb   6
		fcb $AB
		fcb $42
		fcb $6B
		fcb   0
		fcb   0
		fcb $54
		fcb $6B
		fcb   0
		fcb   0
		fcb $54
		fcb $A8
unk_8883:	fcb   4
		fcb $1F
		fcb  $F
		fcb   0
		fcb $F7
		fcb $74
		fcb $61
		fcb   0
		fcb   0
		fcb $8A
		fcb $61
		fcb   0
		fcb   0
		fcb $8A
		fcb $A8
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
unk_889A:	fcb   4
		fcb $1F
		fcb  $F
		fcb   0
		fcb $F7
		fcb $74
		fcb $61
		fcb   0
		fcb   0
		fcb $8A
		fcb $61
		fcb   0
		fcb   0
		fcb $8A
		fcb $A8
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
byte_88B1:	fcb $B8
byte_88B2:	fcb 7
byte_88B3:	fcb $7C
byte_88B4:	fcb $14
byte_88B5:	fcb $66
unk_88B6:	fcb $81
		fcb $18
byte_88B8:	fcb $20
byte_88B9:	fcb $11
byte_88BA:	fcb 0
unk_88BB:	fcb   4
		fcb $64
		fcb  $F
		fcb   0
		fcb   0
		fcb $64
		fcb $2E
		fcb   0
		fcb $AB
		fcb $82
		fcb $42
		fcb   0
		fcb   0
		fcb $82
		fcb $A8
		fcb   2
		fcb $64
		fcb  $F
		fcb   0
		fcb   0
		fcb $96
		fcb  $F
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
unk_88D9:	fcb   4
		fcb $5E
		fcb   5
		fcb   0
		fcb   0
		fcb $5E
		fcb $33
		fcb   0
		fcb $AB
		fcb $7C
		fcb $47
		fcb   0
		fcb   0
		fcb $7C
		fcb $A8
		fcb   2
		fcb $5E
		fcb   5
		fcb   0
		fcb   0
		fcb $96
		fcb   5
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
byte_88F7:	fcb $50
byte_88F8:	fcb $2D
byte_88F9:	fcb $28
byte_88FA:	fcb $A
byte_88FB:	fcb 6
byte_88FC:	fcb 5
byte_88FD:	fcb $10
byte_88FE:	fcb $F
byte_88FF:	fcb $50
byte_8900:	fcb 8
unk_8901:	fcb $FF
		fcb $FF
		fcb $FF
		fcb $41
		fcb $41
		fcb $3F
		fcb $3C
		fcb $40
		fcb $40
byte_890A:	fcb 8
byte_890B:	fcb $D
byte_890C:	fcb $80
byte_890D:	fcb $FE
byte_890E:	fcb $F0
byte_890F:	fcb 0
byte_8910:	fcb $40
byte_8911:	fcb $30
byte_8912:	fcb 0
byte_8913:	fcb $94
byte_8914:	fcb $AA
byte_8915:	fcb $46
byte_8916:	fcb $4F
byte_8917:	fcb 0
byte_8918:	fcb $3C
byte_8919:	fcb $9A
byte_891A:	fcb 8
		fcb   4
		fcb $2D
byte_891D:	fcb $20
byte_891E:	fcb $20
byte_891F:	fcb 2
byte_8920:	fcb 1
byte_8921:	fcb 1
byte_8922:	fcb 5
byte_8923:	fcb 5
byte_8924:	fcb $80
byte_8925:	fcb 6
byte_8926:	fcb 4
byte_8927:	fcb $18
byte_8928:	fcb 6
byte_8929:	fcb $5A
byte_892A:	fcb 4
byte_892B:	fcb $20
byte_892C:	fcb $10
byte_892D:	fcb $FC
byte_892E:	fcb 4
byte_892F:	fcb 8
byte_8930:	fcb $42
byte_8931:	fcb $CE
byte_8932:	fcb $B
byte_8933:	fcb 8
unk_8934:	fcb   4
		fcb   0
		fcb   0
		fcb $FF
		fcb $FB
		fcb $30
		fcb $FF
		fcb $FF
		fcb $F6
		fcb $80
		fcb $FC
		fcb $FF
		fcb $EC
		fcb $FF
		fcb $F2
unk_8943:	fcb   5
		fcb   0
		fcb   0
		fcb   0
		fcb $30
		fcb $10
		fcb   3
		fcb   0
		fcb $1B
		fcb $40
		fcb   8
		fcb   0
		fcb $20
		fcb $80
		fcb $10
		fcb   0
		fcb  $C
		fcb $FF
		fcb $16
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
unk_895A:	fcb   4
		fcb   0
		fcb   0
		fcb   1
		fcb   0
		fcb $10
		fcb $10
		fcb   0
		fcb $C0
		fcb $30
		fcb $28
		fcb   0
		fcb $20
		fcb $70
		fcb $30
unk_8969:	fcb   4
		fcb   0
		fcb   0
		fcb   0
		fcb $B3
		fcb $3C
		fcb $2A
		fcb   0
		fcb $1A
		fcb $5A
		fcb $2D
		fcb   0
		fcb $26
		fcb $6E
		fcb $30
unk_8978:	fcb   5
		fcb   0
		fcb $C0
		fcb $FF
		fcb $55
		fcb $30
		fcb $A0
		fcb $FF
		fcb $9A
		fcb $80
		fcb $80
		fcb $FF
		fcb $55
		fcb $B0
		fcb $60
		fcb $FF
		fcb   0
		fcb $D0
		fcb $40
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
unk_898F:	fcb   4
		fcb $80
		fcb $80
		fcb   1
		fcb   0
		fcb $84
		fcb $84
		fcb   0
		fcb $20
		fcb $94
		fcb $86
		fcb   0
		fcb $14
		fcb $C6
		fcb $8A
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
unk_89AE:	fcb   4
		fcb $46
		fcb   4
		fcb $FF
		fcb $F3
		fcb $5A
		fcb   3
		fcb $FF
		fcb $F3
		fcb $6E
		fcb   2
		fcb $FF
		fcb $E6
		fcb $82
		fcb   0
unk_89BD:	fcb   4
		fcb   0
		fcb   6
		fcb   0
		fcb $E0
		fcb $10
		fcb $14
		fcb   0
		fcb $90
		fcb $20
		fcb $1D
		fcb   0
		fcb $30
		fcb $30
		fcb $20
unk_89CC:	fcb   3
		fcb   2
		fcb $18
		fcb $10
		fcb   0
		fcb   4
		fcb $38
		fcb   8
		fcb   0
		fcb   6
		fcb $48
unk_89D7:	fcb   2
		fcb $20
		fcb $E8
		fcb $FE
		fcb $80
		fcb $30
		fcb $D0
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
unk_89E6:	fcb   2
		fcb $A0
		fcb   3
		fcb   0
		fcb $18
		fcb $C0
		fcb   6
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
unk_89F1:	fcb   2
		fcb $A8
		fcb $80
		fcb $FE
		fcb $ED
		fcb $D0
		fcb $55
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
unk_89FC:	fcb   2
		fcb $60
		fcb   0
		fcb   0
		fcb   0
		fcb $40
		fcb   0
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
unk_8A07:	fcb   2
		fcb $A8
		fcb   0
		fcb   0
		fcb   0
		fcb $D0
		fcb   0
		fcb $FF
		fcb $FF
		fcb $FF
		fcb $FF
byte_8A12:	fcb 2
unk_8A13:	fcb $20
		fcb  $D
word_8A15:	fdb $FF
word_8A17:	fdb $2000
byte_8A19:	fcb 2
byte_8A1A:	fcb 2
byte_8A1B:	fcb $80
byte_8A1C:	fcb 0
byte_8A1D:	fcb 0
unk_8A1E:	fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
byte_8A27:	fcb 0
byte_8A28:	fcb 0
unk_8A29:	fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
unk_8A32:	fcb $26
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
byte_8A38:	fcb 4
byte_8A39:	fcb $11
byte_8A3A:	fcb $EB
byte_8A3B:	fcb $93
byte_8A3C:	fcb $7E
byte_8A3D:	fcb $63
byte_8A3E:	fcb $E4
byte_8A3F:	fcb $CF
byte_8A40:	fcb $32
byte_8A41:	fcb $AA
byte_8A42:	fcb 4
byte_8A43:	fcb $BD
byte_8A44:	fcb $79
byte_8A45:	fcb $1A
byte_8A46:	fcb $FD
byte_8A47:	fcb $B1
byte_8A48:	fcb $1A
byte_8A49:	fcb $FD
byte_8A4A:	fcb $A8
byte_8A4B:	fcb $10
word_8A4C:	fdb $2EE0
byte_8A4E:	fcb $8E
byte_8A4F:	fcb $7F
byte_8A50:	fcb 4
byte_8A51:	fcb 6
byte_8A52:	fcb $2E
byte_8A53:	fcb $22
byte_8A54:	fcb $14
byte_8A55:	fcb $A
byte_8A56:	fcb $38
byte_8A57:	fcb $70
byte_8A58:	fcb $B0
byte_8A59:	fcb 8
byte_8A5A:	fcb $F0
byte_8A5B:	fcb $D1
byte_8A5C:	fcb $20
byte_8A5D:	fcb $28
byte_8A5E:	fcb $2F
byte_8A5F:	fcb $28
byte_8A60:	fcb $DC
byte_8A61:	fcb $8C
byte_8A62:	fcb $64
byte_8A63:	fcb $CE
byte_8A64:	fcb $AB
byte_8A65:	fcb 2
byte_8A66:	fcb $FD
byte_8A67:	fcb $66
byte_8A68:	fcb 1
byte_8A69:	fcb 2
byte_8A6A:	fcb 5
unk_8A6B:	fcb $F0
		fcb $80
		fcb $50
		fcb $40
		fcb $30
		fcb $30
		fcb $20
		fcb $20
		fcb $20
		fcb $10
		fcb $10
		fcb $10
		fcb $10
		fcb   0
		fcb   0
		fcb   0
word_8A7B:	fdb $12C0
word_8A7D:	fdb $2EE0
byte_8A7F:	fcb $12
byte_8A80:	fcb $F7
word_8A81:	fdb $200
byte_8A83:	fcb $CE
unk_8A84:	fcb $21
		fcb $10
unk_8A86:	fcb   5
		fcb   0
		fcb   0
		fcb   7
		fcb $92
		fcb   7
		fcb $35
		fcb   4
		fcb $64
		fcb $19
		fcb $84
		fcb   1
		fcb $66
		fcb $28
		fcb $99
		fcb   0
		fcb $95
		fcb $34
		fcb $A0
byte_8A99:	fcb $2E
byte_8A9A:	fcb $B
byte_8A9B:	fcb $20
byte_8A9C:	fcb 3
byte_8A9D:	fcb $D2
byte_8A9E:	fcb 5
byte_8A9F:	fcb $20
byte_8AA0:	fcb $40
byte_8AA1:	fcb $10
byte_8AA2:	fcb $D0
byte_8AA3:	fcb $70
byte_8AA4:	fcb $60
byte_8AA5:	fcb $30
byte_8AA6:	fcb $C0
word_8AA7:	fdb $1B0
byte_8AA9:	fcb $44
byte_8AAA:	fcb $51
byte_8AAB:	fcb $22
byte_8AAC:	fcb $2E
byte_8AAD:	fcb $71
byte_8AAE:	fcb $B0
byte_8AAF:	fcb $80
byte_8AB0:	fcb $20
word_8AB1:	fdb $16C
byte_8AB3:	fcb 3
word_8AB4:	fdb $FFFF
byte_8AB6:	fcb $23
byte_8AB7:	fcb $FF
byte_8AB8:	fcb $C0
byte_8AB9:	fcb $DA
unk_8ABA:	fcb   5
		fcb   9
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0
		fcb   0

 DCB.B $6C, $FF ; 108 bytes of 0xFF
word_8B56:	fdb 0002