

byte_8000:      db 1                    
                db 0
byte_8002:      db $56                  
                db 2
                db $73
byte_8005:      db $82                  
byte_8006:      db $B1                  
byte_8007:      db $56                  
                db 2
                db $74
                db 4
byte_800B:      db $B1                  
                db $2A
byte_800D:      db $2E                  
                db $18
                db $12
                db $88
                db $FF
byte_8012:      db 1                    
                db $82
byte_8014:      db $FF                  
byte_8015:      db $81                  
byte_8016:      db $20                  
byte_8017:      db 3                    
byte_8018:      db $10                  
byte_8019:      db 2                    
byte_801A:      db 1                    
byte_801B:      db $5C                  
byte_801C:      db $26                  
byte_801D:      db $4C                  
byte_801E:      db 4                    
byte_801F:      db $90                  
byte_8020:      db $D0                  
                                        
byte_8021:      db 0                    
byte_8022:      db 0                    
                db 0
byte_8024:      db 5                    
                db $1F, 0, 0, $42
                db $3E, 8, 0, 8
                db $5E, 9, $FF, $B6
                db $7D, 0, 0, $53
                db $9C, $A
byte_8037:      db $90                  
byte_8038:      db $20                  
                db $F
                db $A0
                db $14
                db $50
                db $17
                db $70
                db $20
                db $D0
                db $23
                db $F0
                db $2E
                db $E0
                db $3E
                db $80
                db $4E
                db $20
                db $5D
                db $C0
                db $6D
                db $60
                db $7D
                db 0
                db $8C
                db $A0
                db $9C
                db $40
byte_8053:      db 3                    
                db $13, 0, 5, $25
                db $2F, $90, 1, 5
                db $9C, $FF
                db $FF, $FF, $FF, $FF
                db $FF, $FF, $FF, $FF
                db $FF, $FF, $FF, $FF
                db $FF, $FF, $FF, $FF
                db $FF, $FF, $FF, $FF
byte_8072:      db 3                    
                db $93
byte_8074:      db $87                  
                db 0
byte_8076:      db 0                    
                db 3
byte_8078:      db $93                  
                db $87
byte_807A:      db $53                  
                db $B5
byte_807C:      db $75                  
                db $30
byte_807E:      db 0                    
byte_807F:      db $14                  
byte_8080:      db 2                    
byte_8081:      db 4                    
byte_8082:      db 5                    
byte_8083:      db $11                  
                db 9
                db 0
                db $1C, $1C, $1C, $1C, $1C, $1C, $E, 8, 8
                db $1C, $1C, $1C, $1C, $1C, $1C, $E, $A, $A
                db $1C, $1C, $1C, $1C, $20, $20, $14, $C, $A
                db $1C, $1C, $1E, $20, $25, $25, $16, $D, $B
                db $1C, $1C, $1F, $31, $2D, $27, $17, $E, $10
                db $1C, $1C, $20, $3C, $2B, $29, $1A, $10, $12
                db $1C, $1C, $26, $3D, $32, $2C, $1E, $10, $10
                db $1C, $2C, $36, $36, $34, $2F, $20, $16, $13
                db $1C, $2C, $36, $3B, $38, $30, $21, $1B, $14
                db $1C, $2C, $36, $43, $39, $33, $22, $1B, $15
                db $1C, $2C, $36, $47, $45, $42, $2D, $24, $24
                db $1C, $2C, $3A, $55, $51, $49, $37, $23, $23
                db $1C, $2C, $3A, $56, $52, $4A, $3D, $23, $23
                db $1C, $2C, $3C, $58, $52, $4A, $3F, $31, $24
                db $1C, $2C, $40, $53, $55, $49, $46, $42, $3B
                db $1C, $2C, $3C, $4B, $47, $49, $48, $42, $3C
                db $1C, $2C, $3C, $58, $52, $4D, $48, $3F, $3A
byte_811F:      db $11                  
                db 9
                db 0
                db $1C, $1C, $1C, $1C, $1C, $1C, $E, 8, 8
                db $1C, $1C, $1C, $1C, $1C, $1C, $E, $A, $A
                db $1C, $1C, $1C, $1C, $1C, $1C, $12, $A, $A
                db $1C, $1C, $1C, $1C, $1C, $1C, $16, $C, $A
                db $1C, $1C, $1C, $1C, $1C, $24, $18, $C, $A
                db $1C, $1C, $1C, $1C, $1C, $2C, $1C, $12, $10
                db $1C, $1C, $1C, $1C, $2A, $28, $18, $12, $10
                db $1C, $4C, $4A, $40, $36, $2C, $1C, $12, $10
                db $1C, $4C, $48, $4D, $36, $34, $24, $12, $10
                db $1C, $4C, $48, $4A, $48, $44, $2B, $12, $12
                db $1C, $4C, $48, $4E, $4D, $48, $33, $1F, $17
                db $1C, $4C, $48, $50, $4B, $44, $42, $32, $21
                db $1C, $4C, $54, $54, $56, $54, $42, $2A, $21
                db $1C, $4C, $5B, $58, $58, $54, $47, $28, $21
                db $1C, $4C, $4D, $50, $4D, $47, $32, $26, $23
                db $1C, $4C, $4D, $50, $4B, $3E, $2E, $28, $25
                db $1C, $4C, $4D, $50, $4B, $3E, $2E, $28, $25
byte_81BB:      db 3                    
byte_81BC:      db $11                  
                db 9
                db 0
                db 0, 0, 0, 0, 0, 0, 0, 0, 0
                db 0, 0, 0, 0, 0, 0, 0, 0, 0
                db 0, 0, 0, 0, 0, 0, 0, 0, 0
                db 0, 0, 0, 0, 0, 0, 0, 0, 0
                db 0, 0, 0, 0, 0, 0, 0, 0, 0
                db 0, 0, 0, 0, 0, 0, 0, 0, 0
                db 0, 0, 0, 0, 0, 0, 0, 0, 0
                db 0, 0, 0, 0, 0, 0, 0, 0, 0
                db 0, 0, 0, 0, 0, 0, 0, 0, 0
                db 0, 0, 0, 0, 0, 0, 0, 0, 0
                db 0, 0, 0, 0, 0, 0, 0, 0, 0
                db 0, 0, 0, 0, 0, 0, 0, 0, 0
                db 0, 0, 0, 0, 0, 0, 0, 0, 0
                db 0, 0, 0, 0, 0, 0, 0, 0, 0
                db 0, 0, 0, 0, 0, 0, 0, 0, 0
                db 0, 0, 0, 0, 0, 0, 0, 0, 0
                db 0, 0, 0, 0, 0, 0, 0, 0, 0
byte_8258:      db $FF, $FF, $FF, $FF, $FF, $FF, $FF
                                        
                db $98, $98, $98, $98, $98, $98, $98
byte_8266:      db $28, $26, $24, $20, $20, $20, $20, $20, $1A
                                        
byte_826F:      db $26, $24, $22, $20, $20, $1A, $14, $14, $14
                                        
byte_8278:      db $D0                  
byte_8279:      db 6                    
byte_827A:      db $14                  
                                        
byte_827B:      db $1C                  
byte_827C:      db 0, 0, 0, 0, 0, 0, 0, 0, 0 
byte_8285:      db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
                                        
byte_828E:      db 1                    
                db $B3
                db $FF
                db $FF
                db $FF
                db $FF
                db $FF
                db $FF
                db $FF
                db $FF
                db $FF
                db $FF
                db $FF
                db $FF
                db $FF
                db $FF
                db $FF
                db $FF
                db $FF
                db $FF
                db $FF
                db 0
                db 0
                db 0
                db 0
                db 0
                db 0
                db 0
                db 0
                db 0
                db 0
                db 0
                db 0
byte_82AF:      db $53                  
                db $F0
byte_82B1:      db $75                  
                db $30
byte_82B3:      db $11                  
                db 9
                db 0
                db $3E, $3E, $3E, $3E, $3E, $3E, $42, $52, $6C
                db $50, $50, $4A, $4A, $4A, $50, $50, $60, $80
                db $50, $50, $4A, $50, $57, $58, $5C, $69, $8D
                db $4A, $60, $5B, $64, $6A, $68, $68, $6B, $86
                db $7A, $7A, $8E, $7D, $73, $70, $70, $6D, $80
                db $8A, $8A, $95, $7E, $7B, $74, $72, $76, $7A
                db $90, $9A, $9D, $8C, $7F, $7A, $77, $77, $7A
                db $A0, $9A, $9D, $88, $7D, $7A, $79, $7A, $79
                db $A0, $A0, $9D, $91, $80, $7B, $7A, $7C, $78
                db $A0, $B0, $9D, $86, $7A, $7D, $7A, $7C, $7E
                db $A0, $B0, $9D, $88, $7C, $7F, $7B, $7C, $A0
                db $A0, $CC, $98, $84, $7D, $7F, $8A, $8A, $E4
                db $A0, $E7, $99, $88, $7E, $7E, $E3, $E3, $E3
                db $A0, $D5, $A2, $91, $86, $87, $8E, $F9, $AC
                db $A0, $DC, $B2, $A2, $97, $99, $95, $95, $8F
                db $A0, $90, $D5, $C3, $B4, $A9, $A5, $C9, $9B
                db $A0, $90, $E1, $D1, $C6, $BE, $B7, $DA, $AA
byte_834F:      db $11                  
                db 9
                db 0
                db $38, $38, $38, $38, $38, $38, $38, $38, $38
                db $38, $38, $38, $38, $38, $38, $3F, $3F, $3F
                db $40, $40, $40, $40, $40, $40, $43, $43, $43
                db $46, $46, $46, $46, $46, $46, $46, $46, $46
                db $44, $44, $44, $57, $43, $42, $47, $47, $47
                db $48, $48, $4B, $58, $45, $42, $4A, $4A, $4A
                db $5F, $5F, $5F, $58, $32, $36, $3E, $5C, $4E
                db $62, $64, $6D, $31, $32, $36, $43, $5C, $5C
                db $65, $68, $46, $3C, $3C, $3E, $45, $62, $62
                db $6B, $6B, $50, $3A, $35, $39, $45, $5E, $60
                db $6B, $6B, $49, $45, $42, $4A, $53, $6B, $6B
                db $50, $50, $4D, $43, $49, $50, $55, $6C, $6C
                db $48, $48, $46, $48, $4C, $54, $5A, $6E, $6E
                db $4A, $4A, $49, $49, $4E, $55, $59, $67, $67
                db $4C, $4C, $4C, $4B, $51, $57, $59, $59, $59
                db $4D, $4D, $4D, $55, $5D, $60, $70, $70, $70
                db $4A, $4A, $4A, $55, $5F, $5E, $5F, $5F, $5F
byte_83EB:      db $D0, $A4, $74, $13, $C, $A, 4, 4, 4 
byte_83F4:      db $14, $14, $14, $14, $10, $A, 3, 3, 3 
byte_83FD:      db $CA, $88, $58, $2A, $23, $F, 5, 0, 0 
byte_8406:      db $50, $48, $34, $1E, $10, 5, 0, 0, 0
                                        
byte_840F:      db 0, 0, 0, 0, $40, $80, $80, $80, $80 
byte_8418:      db 0, 0, 0, 0, 0, 0, 0, 0, 0 
byte_8421:      db $40, $40, $30, $30, $28, $20, $1A, 8, 8
                                        
byte_842A:      db 8                    
                db $61, $FF, $FE, $70
                db $71, $E6, $FA, $C0
                db $81, $92, $FC, $88
                db $92, $57, $FD, $80
                db $A2, $2F, $FE, $E0
                db $C2, $B, $FF, $D9
                db $E3, 6, $FF, $C9
                db $FF, 0
byte_8449:      db $F8, $C0, $6A, $2D, $28, $25, $14, $14, $14
                                        
byte_8452:      db $CC, $CC, $CC, $CC, $CC, $CC, $E6, $FF, $FF
                                        
word_845B:      dw $BB8                 
byte_845D:      db $D0                  
byte_845E:      db $D0                  
byte_845F:      db 4                    
byte_8460:      db $10, $10, $10, $10, $12, $18, $1C, $1C, $1C
                                        
byte_8469:      db $10, $10, $10, $B, 8, 8, 4, 4, 4 
byte_8472:      db $20, $20, $20, $18, $18, $18, $18, $18, $18
                                        
byte_847B:      db $FA, $D0, $B0, $32, $32, $32, $32, $1C, $1C
                                        
byte_8484:      db $60, $50, $40, $40, $30, $30, $10, $10, $10
                                        
byte_848D:      db $20, $20, $20, $20, $20, $40, $40, $40, $40
                                        
byte_8496:      db $80                  
                db $80
byte_8498:      db $96                  
byte_8499:      db $60                  
byte_849A:      db $9F                  
byte_849B:      db $20                  
                db $20
byte_849D:      db 0                    
                db 1
byte_849F:      db $FF                  
                db $D6
byte_84A1:      db 2                    
                                        
                db $19
byte_84A3:      db $99                  
byte_84A4:      db $99                  
                                        
byte_84A5:      db $40                  
                db $40
byte_84A7:      db $F0                  
byte_84A8:      db $28, $28, $24, $20, $18, $18, $18, $18, $18
                                        
byte_84B1:      db $10                  
byte_84B2:      db 2                    
                db $4F
byte_84B4:      db 4                    
                db $13, 0, $A, $AB
                db $1F, $80, 2, $11
                db $3E, $C0, 1, $57
                db $6D, $FF
                db $FF, $FF, $FF, $FF
                db $FF, $FF, $FF, $FF
                db $FF, $FF, $FF, $FF
                db $FF, $FF, $FF, $FF
byte_84D3:      db 5                    
                db 9
                db 0
                db $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C
                db $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C
                db $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C
                db $18, $18, $18, $18, $18, $18, $18, $18, $18
                db $18, $18, $18, $18, $18, $18, $18, $18, $18
                db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
                db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
                db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
                db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
                db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
                db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
                db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
                db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
                db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
                db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
                db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
                db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
byte_856F:      db 5                    
                db 9
                db 0
                db $22, $22, $22, $22, $22, $22, $22, $22, $22
                db $22, $22, $22, $22, $22, $22, $22, $22, $22
                db $22, $22, $22, $22, $22, $22, $22, $22, $22
                db $20, $20, $20, $20, $20, $20, $20, $20, $20
                db $20, $20, $20, $20, $20, $20, $20, $20, $20
                db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
                db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
                db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
                db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
                db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
                db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
                db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
                db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
                db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
                db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
                db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
                db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
byte_860B:      db $B                   
byte_860C:      db $10                  
byte_860D:      db $20                  
byte_860E:      db $20                  
byte_860F:      db 4                    
byte_8610:      db 2                    
byte_8611:      db $60                  
byte_8612:      db 1                    
byte_8613:      db $FE                  
byte_8614:      db $29                  
byte_8615:      db $40                  
byte_8616:      db $B                   
byte_8617:      db 5                    
byte_8618:      db $8C                  
byte_8619:      db $C0                  
byte_861A:      db $B                   
byte_861B:      db $15                  
                db $20
byte_861D:      db $26                  
byte_861E:      db $10                  
byte_861F:      db $A0                  
byte_8620:      db $C0                  
                db $C0
byte_8622:      db $D6                  
byte_8623:      db 8                    
byte_8624:      db $B                   
byte_8625:      db $1D                  
byte_8626:      db $FF                  
byte_8627:      db 1                    
byte_8628:      db $38                  
byte_8629:      db $10                  
                db 7
                db $A0
                db   0
                db $C0
byte_862E:      db 8                    
                db 3
                db $90
                db 0
                db $E0
byte_8633:      db $A8                  
byte_8634:      db $68                  
byte_8635:      db $10                  
                                        
byte_8636:      db 4                    
byte_8637:      db 1                    
byte_8638:      db $17                  
byte_8639:      db $85                  
byte_863A:      db $32                  
                                        
byte_863B:      db $24                  
                                        
byte_863C:      db $56                  
byte_863D:      db $F1                  
byte_863E:      db $17                  
byte_863F:      db 0                    
                db 1
byte_8641:      db $6E                  
byte_8642:      db $A0                  
byte_8643:      db 3                    
                db $84
byte_8645:      db 2                    
byte_8646:      db $C0                  
byte_8647:      db $F0                  
byte_8648:      db 3                    
byte_8649:      db 1                    
byte_864A:      db 8                    
byte_864B:      db $A                   
byte_864C:      db $9A                  
byte_864D:      db 0                    
                db 0
byte_864F:      db 3                    
                db $A
byte_8651:      db 0                    
byte_8652:      db 2                    
byte_8653:      db 2                    
                db $F0
byte_8655:      db $9C                  
                db $40
byte_8657:      db 1                    
                db $90
byte_8659:      db $E0                  
byte_865A:      db 8                    
byte_865B:      db $B2                  
                db $20
byte_865D:      db 1                    
                db $90
byte_865F:      db $80                  
byte_8660:      db 1                    
byte_8661:      db 0                    
                db $B6
byte_8663:      db $F                   
byte_8664:      db $1C                  
byte_8665:      db $1C                  
byte_8666:      db 2                    
                db 5, 0, 1, $6E
                db $C, $A
                db $FF, $FF, $FF, $FF
byte_8671:      db 2                    
                db 5, 0, $FF, $9A
                db $F, $FC
                db $FF, $FF, $FF, $FF
byte_867C:      db $71                  
byte_867D:      db 3                    
                db $D0, $D0, 0, 0
                db $D0, $D0, 0, 0
                db $D0, $D0
byte_8688:      db 5                    
                db $58, $E0, $FE, $66
                db $80, $A0, $FD, $CD
                db $A8, $48, $FF, $9A
                db $D0, $38, 0, $CD
                db $F8, $58
byte_869B:      db 3                    
                db $9A, $28, $FF, $7A
                db $C8, $10, $FF, $9A
                db $F0, 0
byte_86A6:      db $14                  
byte_86A7:      db $A0                  
byte_86A8:      db $20                  
byte_86A9:      db $D0                  
byte_86AA:      db $E8                  
byte_86AB:      db 4                    
                                        
                db $14, $14, $FF, $C0
                db $3C, $A, $FF, $F3
                db $64, 8, $FF, $EF
                db $82, 6
byte_86BA:      db 0                    
byte_86BB:      db 4                    
                db $68, $50, $FF, $55
                db $80, $40, $FF, $33
                db $A8, $20, $FF, $33
                db $D0, 0
byte_86CA:      db 3                    
                db 0, 0, 0, 0
                db $10, 0, 0, 0
                db $21, 0
byte_86D5:      db 4                    
                db 0, 0, 0, 0
                db 2, 0, 0, 0
                db 5, 0, 0, 0
                db $1E, 0
byte_86E4:      db 4                    
                db $1C, 5, 0, $72
                db $2E, $D, 0, 0
                db $3F, $D, 0, 0
                db $FF, $D
byte_86F3:      db 3                    
                db $9A, $50, $FF, $DF
                db $C8, $4A, $FF, $C0
                db $F0, $40
byte_86FE:      db 5                    
                db $58, $96, $FF, $86
                db $A8, $70, $FF, $86
                db $D0, $5D, 0, 0
                db $E5, $5D, 4, $1C
                db $EE, $82
byte_8711:      db 5                    
                db $58, $96, $FF, $86
                db $A8, $70, $FF, $86
                db $D0, $5D, 0, 0
                db $E5, $5D, 4, $1C
                db $EE, $82
byte_8724:      db 3                    
                db 0, 0, 0, 0
                db 0, 0, 0, 0
                db 0, 0
byte_872F:      db $6A                  
byte_8730:      db $64                  
byte_8731:      db 5                    
                db $32, 1, 0, 0
                db $4B, 2, 0, 0
                db $5A, 3, 0, 0
                db $78, 5, 0, 0
                db $96, 8
byte_8744:      db 5                    
                db $40, $FF, 0, 0
                db $A0, $FE, 0, 0
                db $C8, $FB, 0, 0
                db $E6, $FA, 0, 0
                db $FF, $F8
byte_8757:      db $11                  
byte_8758:      db $11                  
byte_8759:      db $EE                  
byte_875A:      db $1A                  
                db $1A
                db $1A
                db $1A
                db $1A
                db $1A
                db $16
                db 8
                db 8
byte_8763:      db $1F                  
byte_8764:      db $1A                  
                db $1A
                db $1A
                db $1A
                db $1A
                db $1A
                db $16
                db 8
                db 8
byte_876D:      db $38                  
                                        
byte_876E:      db $DB                  
                                        
byte_876F:      db $40                  
                db $50
byte_8771:      db $7F                  
byte_8772:      db $10                  
byte_8773:      db 3                    
                db $58, $F0, 0, 0
                db $A8, $F0, 0, 0
                db $F8, $F0
byte_877E:      db 3                    
                db $58, $10, 0, 0
                db $A8, $10, 0, 0
                db $F8, $10
byte_8789:      db 4                    
                db $9A, $98, $FF, $CA
                db $AD, $94, 0, 0
                db $C8, $94, $FF, $80
                db $F0, $80
                db $FF, $FF, $FF, $FF
byte_879C:      db 2                    
                db $B, 0, 0, 0
                db $1B, 0
                db $FF, $FF, $FF, $FF
byte_87A7:      db 4                    
                db $58, $30, $FF, $B3
                db $80, $24, $FF, $80
                db $A8, $10, $FF, $9A
                db $D0, 0
                db $FF, $FF, $FF, $FF
byte_87BA:      db 4                    
                db $1F, 0, 0, 0
                db $46, 0, 0, 0
                db $6D, 0, 0, 0
                db $BC, 0
byte_87C9:      db 3                    
                db 0, 0, 0, 0
                db $8F, 0, 0, 0
                db $FF, 0
byte_87D4:      db 2                    
                db $90, $FF, 0, 0
                db $C7, $FF
                db $FF, $FF, $FF, $FF
byte_87DF:      db 4                    
                db 8, 0, 0, $80
                db $C, 2, 0, $40
                db $10, 3, 0, $40
                db $18, 5
byte_87EE:      db 4                    
                db 8, 0, $FF, $C0
                db $C, $FF, $FF, $C0
                db $10, $FE, $FF, $E0
                db $18, $FD
byte_87FD:      db $3F                  
byte_87FE:      db $D4                  
byte_87FF:      db 2                    
byte_8800:      db $12                  
byte_8801:      db $1F                  
byte_8802:      db $B                   
byte_8803:      db $7F                  
word_8804:      dw $FAD                 
byte_8806:      db $70                  
byte_8807:      db $8C                  
byte_8808:      db $70                  
byte_8809:      db $FF                  
word_880A:      dw $7D00                
word_880C:      dw $7D00                
byte_880E:      db 4                    
byte_880F:      db $B6                  
byte_8810:      db 7                    
byte_8811:      db $10                  
byte_8812:      db $FE                  
byte_8813:      db $FE                  
byte_8814:      db $10                  
byte_8815:      db $A                   
                                        
byte_8816:      db 4                    
byte_8817:      db $70                  
byte_8818:      db 3                    
byte_8819:      db $58                  
byte_881A:      db $FF                  
byte_881B:      db $5A                  
byte_881C:      db $46                  
word_881D:      dw $E8E3                
                dw $E8E3
word_8821:      dw 0                    
word_8823:      dw 0                    
byte_8825:      db 0                    
byte_8826:      db 0                    
byte_8827:      db $92                  
byte_8828:      db 0                    
byte_8829:      db $20                  
byte_882A:      db $32                  
byte_882B:      db 0                    
byte_882C:      db 6                    
byte_882D:      db $40                  
byte_882E:      db 6                    
                db $1C, $24, 0, $E7
                db $3B, $40, 5, $C0
                db $3F, $57, 6, $AB
                db $42, $6B, 0, 0
                db $54, $6B, 0, 0
                db $54, $A8
byte_8845:      db 4                    
                db $1F, $F, 0, $F7
                db $74, $61, 0, 0
                db $8A, $61, 0, 0
                db $8A, $A8
                db $FF, $FF, $FF, $FF
                db $FF, $FF, $FF, $FF
byte_885C:      db 4                    
                db $1F, $F, 0, $F7
                db $74, $61, 0, 0
                db $8A, $61, 0, 0
                db $8A, $A8
                db $FF, $FF, $FF, $FF
                db $FF, $FF, $FF, $FF
byte_8873:      db $B8                  
byte_8874:      db 7                    
byte_8875:      db $7C                  
byte_8876:      db $14                  
byte_8877:      db $66                  
word_8878:      dw $8118                
byte_887A:      db $20                  
byte_887B:      db $11                  
byte_887C:      db 0                    
byte_887D:      db 4                    
                db $64, $F, 0, 0
                db $64, $2E, 0, $AB
                db $82, $42, 0, 0
                db $82, $A8
                db 2
                db $64, $F, 0, 0
                db $96, $F, $FF, $FF
                db $FF, $FF
                db $FF, $FF, $FF, $FF
byte_889B:      db 4                    
                db $5E, 5, 0, 0
                db $5E, $33, 0, $AB
                db $7C, $47, 0, 0
                db $7C, $A8
                db 5
                db $5E
                db 5
                db 0
                db 0
                db $96
                db 5
                db 2
                db $62
                db $FF
                db $FF
                db 0
                db 0
                db $FF
                db $FF
byte_88B9:      db $50                  
byte_88BA:      db $2D                  
byte_88BB:      db $24                  
byte_88BC:      db 2                    
byte_88BD:      db 8                    
byte_88BE:      db 5                    
byte_88BF:      db $10                  
byte_88C0:      db $F                   
byte_88C1:      db $50                  
byte_88C2:      db 8                    
byte_88C3:      db $FF, $FF, $FF, $41, $41, $3F, $3C, $40, $40
                                        
byte_88CC:      db 8                    
byte_88CD:      db $D                   
byte_88CE:      db $80                  
byte_88CF:      db $FE                  
byte_88D0:      db $F0                  
byte_88D1:      db 0                    
byte_88D2:      db $40                  
byte_88D3:      db $30                  
byte_88D4:      db 0                    
byte_88D5:      db $94                  
byte_88D6:      db $AA                  
                                        
byte_88D7:      db $46                  
byte_88D8:      db $4F                  
byte_88D9:      db 0                    
byte_88DA:      db $3C                  
byte_88DB:      db $7D                  
byte_88DC:      db 8                    
                db 4
                db $2D
byte_88DF:      db $20                  
byte_88E0:      db $20                  
byte_88E1:      db 2                    
byte_88E2:      db 1                    
byte_88E3:      db 1                    
byte_88E4:      db 5                    
byte_88E5:      db 5                    
byte_88E6:      db $80                  
byte_88E7:      db 6                    
byte_88E8:      db 4                    
byte_88E9:      db $18                  
byte_88EA:      db 6                    
byte_88EB:      db $5A                  
byte_88EC:      db 4                    
byte_88ED:      db $20                  
byte_88EE:      db $10                  
byte_88EF:      db $FC                  
byte_88F0:      db 4                    
byte_88F1:      db 8                    
byte_88F2:      db $42                  
                                        
byte_88F3:      db $CE                  
                                        
byte_88F4:      db $B                   
byte_88F5:      db 8                    
byte_88F6:      db 4                    
                db 0, 0, $FF, $FB
                db $30, $FF, $FF, $F6
                db $80, $FC, $FF, $EC
                db $FF, $F2
byte_8905:      db 5                    
                db 0, 0, 0, $30
                db $10, 3, 0, $1B
                db $40, 8, 0, $20
                db $80, $10, 0, $C
                db $FF, $16
                db $FF, $FF, $FF, $FF
byte_891C:      db 4                    
                db 0, 0, 1, 0
                db $10, $10, 0, $C0
                db $30, $28, 0, $20
                db $70, $30
byte_892B:      db 4                    
                db 0, 0, 0, $B3
                db $3C, $2A, 0, $1A
                db $5A, $2D, 0, $26
                db $6E, $30
byte_893A:      db 5                    
                db 0, $C0, $FF, $55
                db $30, $A0, $FF, $9A
                db $80, $80, $FF, $55
                db $B0, $60, $FF, 0
                db $D0, $40
                db $FF, $FF, $FF, $FF
byte_8951:      db 4                    
                db $80, $80, 1, 0
                db $84, $84, 0, $20
                db $94, $86, 0, $14
                db $C6, $8A
                db $FF, $FF, $FF, $FF
                db $FF, $FF, $FF, $FF
                db $FF, $FF, $FF, $FF
                db $FF, $FF, $FF, $FF
byte_8970:      db 4                    
                db $46, 4, $FF, $F3
                db $5A, 3, $FF, $F3
                db $6E, 2, $FF, $E6
                db $82, 0
byte_897F:      db 4                    
                db 0, 6, 0, $E0
                db $10, $14, 0, $90
                db $20, $1D, 0, $30
                db $30, $20
byte_898E:      db 3                    
                db 2, $18, $10, 0
                db 4, $38, 8, 0
                db 6, $48
byte_8999:      db 2                    
                db $20, $E8, $FE, $80
                db $30, $D0
                db $FF, $FF, $FF, $FF
                db $FF, $FF, $FF, $FF
byte_89A8:      db 2                    
                db $A0, 3, 0, $18
                db $C0, 6
                db $FF, $FF, $FF, $FF
byte_89B3:      db 2                    
                db $A8, $80, $FE, $ED
                db $D0, $55
                db $FF, $FF, $FF, $FF
byte_89BE:      db 2                    
                db $A0, 3, 0, $18
                db $C0, 6
                db $FF, $FF, $FF, $FF
byte_89C9:      db 2                    
                db $A8, $80, $FE, $ED
                db $D0, $55
                db $FF, $FF, $FF, $FF
TL_ErrorBitsMask1:db 0                  
                db 0
                db 0
                db 0
                db 0
                db 0
byte_89DA:      db 4                    
byte_89DB:      db $11                  
byte_89DC:      db $EB                  
byte_89DD:      db $93                  
byte_89DE:      db $3E                  
byte_89DF:      db $63                  
byte_89E0:      db $E4                  
byte_89E1:      db $CF                  
byte_89E2:      db $32                  
byte_89E3:      db $AA                  
byte_89E4:      db 4                    
byte_89E5:      db $BD                  
byte_89E6:      db $79                  
byte_89E7:      db $1A                  
byte_89E8:      db $FD                  
byte_89E9:      db $B1                  
                                        
byte_89EA:      db $1A                  
byte_89EB:      db $FD                  
                                        
byte_89EC:      db $A8                  
                                        
byte_89ED:      db $10                  
byte_89EE:      db $2E                  
                db $E0
byte_89F0:      db $8E                  
byte_89F1:      db $7F                  
byte_89F2:      db 4                    
byte_89F3:      db 6                    
byte_89F4:      db $2E                  
byte_89F5:      db $22                  
byte_89F6:      db $14                  
byte_89F7:      db $A                   
byte_89F8:      db $38                  
byte_89F9:      db $70                  
byte_89FA:      db $B0                  
byte_89FB:      db 8                    
byte_89FC:      db $F0                  
byte_89FD:      db $D1                  
byte_89FE:      db $20                  
byte_89FF:      db $28                  
byte_8A00:      db $2F                  
byte_8A01:      db $28                  
byte_8A02:      db $DC                  
byte_8A03:      db $8C                  
byte_8A04:      db $64                  
byte_8A05:      db $CE                  
byte_8A06:      db $AB                  
byte_8A07:      db 2                    
byte_8A08:      db $FD                  
byte_8A09:      db $66                  
byte_8A0A:      db 1                    
byte_8A0B:      db 2                    
byte_8A0C:      db 5                    
                                        
byte_8A0D:      db $F0, $80, $50, $40, $30, $30, $20, $20, $20, $10, $10
                                        
                db $10, $10, 0, 0, 0
byte_8A1D:      db $12                  
                db $C0
byte_8A1F:      db $2E                  
                db $E0
byte_8A21:      db $12                  
byte_8A22:      db $F7                  
byte_8A23:      db 2                    
                                        
                db 0
byte_8A25:      db $CE                  
byte_8A26:      db $21                  
                db $10
byte_8A28:      db 5                    
                db 0, 0, 7, $92
                db 7, $35, 4, $64
                db $19, $84, 1, $66
                db $28, $99, 0, $95
                db $34, $A0
byte_8A3B:      db $2E                  
byte_8A3C:      db $B                   
byte_8A3D:      db $20                  
byte_8A3E:      db 3                    
byte_8A3F:      db $D2                  
byte_8A40:      db 5                    
byte_8A41:      db $20                  
byte_8A42:      db $40                  
byte_8A43:      db $10                  
byte_8A44:      db $D0                  
byte_8A45:      db $70                  
byte_8A46:      db $60                  
byte_8A47:      db $30                  
byte_8A48:      db $C0                  
word_8A49:      dw $1B0                 
byte_8A4B:      db $44                  
byte_8A4C:      db $51                  
byte_8A4D:      db $22                  
byte_8A4E:      db $2E                  
byte_8A4F:      db $71                  
byte_8A50:      db $B0                  
byte_8A51:      db $80                  
byte_8A52:      db $20                  
word_8A53:      dw $16C                 
byte_8A55:      db 3                    
byte_8A56:      db 8                    
byte_8A57:      db 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

