                fcb $11
                fcb   0
byte_8002:      fcb $56                 ; DATA XREF: RESERVED:loc_9D14↓o
                fcb 2
                fcb $93
byte_8005:      fcb 2                   ; DATA XREF: sub_A266+2B↓r
byte_8006:      fcb $A0                 ; DATA XREF: RESERVED:9D47↓r
byte_8007:      fcb $56                 ; DATA XREF: RESERVED:9D1B↓o
                fcb 2
                fcb $81
                fcb $13
byte_800B:      fcb $A0                 ; DATA XREF: RESERVED:9D4E↓r
                fcb $D1
byte_800D:      fcb $4A                 ; DATA XREF: RESERVED:loc_9D3F↓o
                fcb $18
                fcb $54
                fcb $C8
byte_8011:      fcb 0                   ; DATA XREF: sub_E88B+5↓r
byte_8012:      fcb 8                   ; DATA XREF: RESERVED:B3B5↓r
                fcb $A2
byte_8014:      fcb 0                   ; DATA XREF: sub_B22F+67↓r
                fcb $93
                fcb 0
byte_8017:      fcb $10                 ; DATA XREF: __RESET+36↓r
                                        ; __RESET+105↓r ...
byte_8018:      fcb $C1                 ; DATA XREF: __RESET+343↓r
                                        ; __RESET+4BE↓r ...
byte_8019:      fcb $4A                 ; DATA XREF: __RESET+70A↓r
                                        ; __RESET:loc_9856↓r ...
byte_801A:      fcb 2                   ; DATA XREF: __RESET+48E↓r
byte_801B:      fcb $10                 ; DATA XREF: sub_EBC9:loc_ECDF↓r
byte_801C:      fcb 2                   ; DATA XREF: sub_EBC9+11C↓r
byte_801D:      fcb 0                   ; DATA XREF: sub_EBC9+123↓r
byte_801E:      fcb $5C                 ; DATA XREF: __RESET+491↓r
                                        ; __RESET+498↓r ...
byte_801F:      fcb $2F                 ; DATA XREF: sub_EBC9+178↓r
byte_8020:      fcb $6E                 ; DATA XREF: sub_EBC9+17F↓r
byte_8021:      fcb 8                   ; DATA XREF: sub_EBC9+159↓r
                                        ; sub_EEA7+1C↓r ...
byte_8022:      fcb $75                 ; DATA XREF: sub_EBC9+C6↓r
                                        ; sub_ED72↓r
byte_8023:      fcb $FF                 ; DATA XREF: sub_ED72+7↓r
                                        ; sub_ED72:loc_ED7E↓r
byte_8024:      fcb $F4                 ; DATA XREF: sub_F2EC↓r
byte_8025:      fcb $15                 ; DATA XREF: sub_F2EC:loc_F2F2↓r
                fcb $DC
byte_8027:      fcb 5                   ; DATA XREF: sub_E9A1+C↓o
                fcb $15, 0, 0, $F
                fcb $37, 2, 0, $17
                fcb $58, 5, 0, $48
                fcb $71, $C, 0, $1C
                fcb $96, $10
byte_803A:      fcb $75                 ; DATA XREF: sub_E9A1+24↓r
byte_803B:      fcb $17                 ; DATA XREF: sub_E9A1+2C↓r
byte_803C:      fcb 3                   ; DATA XREF: sub_BB94+6↓o
                                        ; sub_E9A1+5A↓r
byte_803D:      fcb 2                   ; DATA XREF: sub_E9A1+72↓r
                fcb $F
                fcb $A0
                fcb $14
                fcb $50
                fcb $17
                fcb $70
                fcb $20
                fcb $D0
                fcb $23
                fcb $F0
                fcb $2E
                fcb $E0
                fcb $3E
                fcb $80
                fcb $4E
                fcb $20
                fcb $5D
                fcb $C0
                fcb $6D
                fcb $60
                fcb $7D
                fcb 0
                fcb $8C
                fcb $A0
                fcb $9C
                fcb $40
byte_8058:      fcb 4                   ; DATA XREF: sub_F2FA↓o
                fcb $13, 0, 5, $55
                fcb $1F, $40, 2, $80
                fcb $3F, $90, 1, $47
                fcb $96, $FF
                fcb $FF, $FF, $FF, $FF
byte_806B:      fcb 4                   ; DATA XREF: sub_B800+F1↓o
                fcb $80, 0, 1, $9A
                fcb $D0, $80, 3, $33
                fcb $DA, $A0, 3, $2B
                fcb $F8, $FF
                fcb $FF, $FF, $FF, $FF
byte_807E:      fcb 4                   ; DATA XREF: sub_B800+B9↓o
                fcb $13, 0, 5, $1F
                fcb $2C, $80, 3, $5E
                fcb $3F, $C0, 5, $40
                fcb $4B, $FF
byte_808D:      fcb 4                   ; DATA XREF: sub_B800+DE↓o
                fcb $80, 0, 1, $9A
                fcb $D0, $80, 3, $33
                fcb $DA, $A0, 3, $2B
                fcb $F8, $FF
                fcb $FF, $FF, $FF, $FF
word_80A0:      fdb $1C9                ; DATA XREF: sub_F211:loc_F224↓r
byte_80A2:      fcb $C3                 ; DATA XREF: sub_F211+16↓r
                fcb $80
word_80A4:      fdb 1                   ; DATA XREF: sub_F211+B↓r
byte_80A6:      fcb $C9                 ; DATA XREF: sub_F211+E↓r
                fcb $C4
word_80A8:      fdb $208D               ; DATA XREF: IC1I+191↓r
word_80AA:      fdb $493E               ; DATA XREF: IC1I+184↓r
byte_80AC:      fcb 4                   ; DATA XREF: IC1I+19E↓r
byte_80AD:      fcb 2                   ; DATA XREF: IC1I+1BF↓r
byte_80AE:      fcb $14                 ; DATA XREF: sub_B800+342↓r
byte_80AF:      fcb 2                   ; DATA XREF: sub_B800+33A↓r
byte_80B0:      fcb 8                   ; DATA XREF: sub_B800+330↓r
byte_80B1:      fcb $11                 ; DATA XREF: sub_B800+3↓o
                fcb 9
                fcb 0
                fcb $28, $28, $28, $28, $28, $28, $28, $19, $10
                fcb $28, $28, $28, $28, $28, $28, $28, $19, $10
                fcb $28, $28, $28, $28, $28, $28, $28, $19, $10
                fcb $30, $30, $30, $30, $30, $2C, $28, $19, $10
                fcb $38, $38, $38, $38, $36, $31, $29, $19, $10
                fcb $47, $47, $43, $47, $40, $3B, $2D, $1C, $10
                fcb $46, $46, $46, $46, $40, $38, $2E, $21, $12
                fcb $42, $42, $42, $42, $43, $40, $35, $28, $1C
                fcb $48, $48, $48, $48, $44, $43, $3A, $2D, $20
                fcb $43, $43, $43, $43, $4A, $41, $3C, $2C, $28
                fcb $4F, $4F, $4F, $4F, $4C, $49, $3F, $32, $2E
                fcb $51, $51, $51, $51, $4F, $50, $41, $32, $2E
                fcb $4D, $4D, $4D, $4D, $51, $45, $39, $30, $2C
                fcb $46, $46, $46, $46, $4E, $3B, $36, $2B, $33
                fcb $53, $53, $53, $53, $4B, $3D, $33, $30, $30
                fcb $53, $53, $53, $53, $46, $3D, $35, $2E, $2E
                fcb $5A, $5A, $5A, $5A, $4B, $3A, $38, $32, $32
byte_814D:      fcb $11                 ; DATA XREF: sub_B800+14↓o
                                        ; sub_B800+23↓o ...
                fcb 9
                fcb 0
                fcb $28, $28, $28, $28, $28, $28, $28, $19, $10
                fcb $28, $28, $28, $28, $28, $28, $28, $19, $10
                fcb $28, $28, $28, $28, $28, $28, $28, $19, $10
                fcb $30, $30, $30, $30, $30, $30, $28, $19, $10
                fcb $38, $38, $38, $38, $38, $3C, $2A, $19, $10
                fcb $51, $51, $51, $51, $47, $39, $2F, $1C, $10
                fcb $4A, $4A, $4A, $4A, $48, $3D, $35, $21, $12
                fcb $48, $48, $48, $48, $47, $46, $3D, $28, $1C
                fcb $4E, $4E, $4E, $4E, $4B, $49, $42, $2D, $20
                fcb $45, $45, $45, $45, $4C, $45, $42, $2C, $28
                fcb $50, $50, $50, $50, $50, $4C, $42, $32, $2E
                fcb $52, $52, $52, $52, $55, $4E, $42, $31, $2E
                fcb $47, $47, $47, $47, $52, $42, $3A, $30, $2C
                fcb $47, $47, $47, $47, $48, $3F, $3A, $2B, $33
                fcb $53, $53, $53, $53, $4B, $3D, $33, $30, $30
                fcb $53, $53, $53, $53, $46, $3D, $35, $2E, $2E
                fcb $5A, $5A, $5A, $5A, $4B, $3A, $38, $32, $32
byte_81E9:      fcb 8                   ; DATA XREF: IC1I+2D3↓r
byte_81EA:      fcb $11                 ; DATA XREF: sub_B800+57↓o
                fcb 9
                fcb 0
                fcb 0, 0, 0, 0, 0, 0, 0, 0, 0
                fcb 0, 0, 0, 0, 0, 0, 0, 0, 0
                fcb 0, 0, 0, 0, 0, 0, 0, 0, 0
                fcb 0, 0, 0, 0, 0, 0, 0, 0, 0
                fcb 0, 0, 0, 0, 0, 0, 0, 0, 0
                fcb 0, 0, 0, 0, 0, 0, 0, 0, 0
                fcb 0, 0, 0, 0, 0, 0, 0, 0, 0
                fcb 0, 0, 0, 0, 0, 0, 0, 0, 0
                fcb 0, 0, 0, 0, 0, 0, 0, 0, 0
                fcb 0, 0, 0, 0, 0, 0, 0, 0, 0
                fcb 0, 0, 0, 0, 0, 0, 0, 0, 0
                fcb 0, 0, 0, 0, 0, 0, 0, 0, 0
                fcb 0, 0, 0, 0, 0, 0, 0, 0, 0
                fcb 0, 0, 0, 0, 0, 0, 0, 0, 0
                fcb 0, 0, 0, 0, 0, 0, 0, 0, 0
                fcb 0, 0, 0, 0, 0, 0, 0, 0, 0
                fcb 0, 0, 0, 0, 0, 0, 0, 0, 0
byte_8286:      fcb $40                 ; DATA XREF: sub_B800+D1↓o
                fcb $40
                fcb $40
                fcb $40
                fcb $80
                fcb $80
                fcb $80
                fcb $80
                fcb $80
                fcb $80
                fcb $80
                fcb $80
                fcb $80
                fcb $80
byte_8294:      fcb 9                   ; DATA XREF: sub_B800+E8↓o
                fcb 9
                fcb $FF
                fcb 0, 0, 0, 0, 0, 0, 0, 0, 0
                fcb 0, 0, 0, 0, 0, 0, 0, 0, 0
                fcb 0, 0, 0, 0, 0, 0, 0, 0, 0
                fcb 0, 0, 0, 0, 0, 0, 0, 0, 0
                fcb 0, 0, 0, 0, 0, 0, 0, 0, 0
                fcb 0, 0, 0, 0, 0, 0, 0, 0, 0
                fcb 0, 0, 0, 0, $FF, $FF, $FE, $FF, 0
                fcb 0, 0, 0, 0, $FE, $FC, $F9, $FB, 0
                fcb 0, 0, 0, 0, $FD, $FA, $F5, $F9, $FF
byte_82E8:      fcb 9                   ; DATA XREF: sub_B800+FB↓o
                fcb 9
                fcb $FF
                fcb 0, 0, 0, 0, 0, 0, 0, 0, 0
                fcb 0, 0, 0, 0, 0, 0, 0, 0, 0
                fcb 0, 0, 0, 0, 0, 0, 0, 0, 0
                fcb 0, 0, 0, 0, 0, 0, 0, 0, 0
                fcb 0, 0, 0, 0, 0, $FF, $FF, $FF, 0
                fcb 0, 0, 0, 0, 0, $FF, $FF, $FF, 0
                fcb 0, 0, 0, 0, $FF, $FF, $FF, $FB, $FF
                fcb 0, 0, 0, 0, $FF, $FF, $FF, $FB, $FF
                fcb 0, 0, 0, 0, $FF, $FF, $FE, $FB, $FF
byte_833C:      fcb 5                   ; DATA XREF: sub_B800+C6↓o
                fcb 9
                fcb $FF
                fcb 0, 0, 0, 0, 0, 0, 0, 0, 0
                fcb 0, 0, 0, 0, $EC, $F5, $F8, 0, 0
                fcb 0, 0, 0, $F4, $EC, $EC, $F1, 0, 0
                fcb 0, 0, 0, $EC, $E6, $ED, $F6, 0, 0
                fcb 0, 0, 0, 0, $EF, $E1, $F0, 0, 0
byte_836C:      fcb $E3                 ; DATA XREF: sub_B800+114↓r
byte_836D:      fcb 6                   ; DATA XREF: sub_B800+119↓r
byte_836E:      fcb $A3                 ; DATA XREF: sub_B800+7B↓r
byte_836F:      fcb $93                 ; DATA XREF: sub_B800+76↓r
byte_8370:      fcb 0                   ; DATA XREF: sub_B800+83↓r
byte_8371:      fcb $50                 ; DATA XREF: IC1I+2B3↓r
byte_8372:      fcb 8                   ; DATA XREF: sub_B800+21D↓r
byte_8373:      fcb 0                   ; DATA XREF: sub_B800+93↓r
byte_8374:      fcb $FF                 ; DATA XREF: sub_B800:loc_B88B↓r
byte_8375:      fcb $FF                 ; DATA XREF: sub_B800+27F↓r
byte_8376:      fcb 8                   ; DATA XREF: sub_B800+287↓r
                                        ; sub_B800+2A2↓r ...
byte_8377:      fcb 4                   ; DATA XREF: IC1I+332↓r
byte_8378:      fcb 2                   ; DATA XREF: IC1I+33A↓r
byte_8379:      fcb $7F                 ; DATA XREF: sub_B800+132↓r
                                        ; sub_B800:loc_BA33↓r
byte_837A:      fcb $28                 ; DATA XREF: sub_B800+143↓r
byte_837B:      fcb 2, $58, 0, 0, 0, $92, 0 ; DATA XREF: sub_B800+137↓o
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
byte_839E:      fcb 2, 0, 0, 0, 0, $FF, 0 ; DATA XREF: sub_B800+15B↓o
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
byte_83B5:      fcb $18                 ; DATA XREF: sub_CEF4+5↓r
                                        ; IC1I+14C↓r
                fcb $6A
byte_83B7:      fcb $49                 ; DATA XREF: IC1I+13F↓r
                fcb $3E
byte_83B9:      fcb $11                 ; DATA XREF: sub_CFA0+18↓o
                fcb 9
                fcb 0
                fcb $4F, $4F, $48, $44, $3A, $72, $73, $73, $73
                fcb $4E, $4E, $44, $40, $5F, $71, $73, $73, $73
                fcb $4E, $4E, $42, $3E, $59, $70, $73, $73, $73
                fcb $58, $58, $57, $52, $60, $71, $73, $7A, $7A
                fcb $6A, $6A, $65, $7A, $7C, $78, $73, $73, $84
                fcb $E0, $E0, $7D, $70, $7B, $7E, $7E, $7C, $83
                fcb $FF, $FF, $94, $9A, $99, $95, $90, $90, $89
                fcb $FF, $FF, $98, $8C, $8B, $8B, $8B, $8F, $89
                fcb $FF, $FF, $A0, $9C, $94, $92, $92, $90, $8B
                fcb $FF, $FF, $A8, $B0, $A4, $A1, $94, $9B, $9A
                fcb $FF, $FF, $C0, $B4, $A8, $AC, $A0, $A0, $A5
                fcb $FF, $FF, $D8, $C5, $BC, $B2, $A8, $A7, $AC
                fcb $FF, $FF, $FF, $F4, $DC, $DA, $CF, $CA, $C0
                fcb $FF, $FF, $FF, $FF, $FC, $EF, $DE, $DE, $D4
                fcb $FF, $FF, $FF, $FF, $FF, $F6, $E8, $E4, $E4
                fcb $FF, $FF, $FF, $FF, $FF, $F6, $EA, $E4, $E4
                fcb $FF, $FF, $FF, $E7, $E2, $DC, $CC, $CC, $CC
byte_8455:      fcb $11                 ; DATA XREF: sub_CFA0+10↓o
                fcb 9
                fcb 0
                fcb $5A, $5A, $5A, $5D, $5D, $64, $6E, $73, $73
                fcb $58, $58, $58, $5B, $5C, $64, $6E, $73, $73
                fcb $5B, $75, $5A, $5E, $66, $70, $7D, $7F, $7F
                fcb $77, $77, $74, $68, $70, $7E, $83, $8B, $8B
                fcb $8A, $70, $75, $68, $76, $72, $79, $8E, $84
                fcb $84, $70, $70, $80, $78, $76, $78, $94, $83
                fcb $85, $85, $89, $88, $84, $80, $84, $96, $89
                fcb $86, $86, $89, $7A, $7C, $7E, $82, $94, $89
                fcb $89, $89, $80, $82, $83, $80, $84, $98, $8B
                fcb $8C, $8C, $9A, $A8, $98, $90, $93, $9F, $9A
                fcb $9A, $9A, $A6, $A4, $A4, $9B, $98, $AC, $A5
                fcb $AE, $AE, $BA, $AC, $AA, $A4, $9C, $B4, $AC
                fcb $C2, $C2, $C8, $D7, $C8, $C5, $BC, $D2, $C0
                fcb $D0, $D0, $D1, $F2, $E4, $D8, $D0, $E4, $D4
                fcb $D0, $D0, $D3, $FF, $FF, $F6, $E8, $E4, $E4
                fcb $D0, $D0, $D7, $FF, $FF, $F6, $EA, $E4, $E4
                fcb $D0, $D0, $DA, $E7, $E2, $DC, $CC, $CC, $CC
byte_84F1:      fcb 2, $80, $C2, 0, 0, $E4, $C2
                                        ; DATA XREF: sub_CE79+70↓o
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
byte_850C:      fcb 2, $80, $61, 0, 0, $E4, $61
                                        ; DATA XREF: sub_CE79:loc_CEAA↓o
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
byte_8527:      fcb 7                   ; DATA XREF: sub_CE79:loc_CECF↓o
                fcb $58, $7A, $FF, $80
                fcb $6C, $70, $FF, $66
                fcb $80, $64, $FE, $26
                fcb $94, $3F, $FF, $40
                fcb $A8, $30, $FE, $C0
                fcb $BC, $17, $FF, $4D
                fcb $D0, 9
byte_8542:      fcb 4                   ; DATA XREF: sub_CDF1+2B↓o
                fcb 0, $40, 0, 0
                fcb $1F, $40, 0, 0
                fcb $3F, $40, 0, 0
                fcb $5E, $40
byte_8551:      fcb 7                   ; DATA XREF: sub_CE79+4B↓o
                fcb $58, $A4, $FF, 0
                fcb $6C, $90, $FD, $CD
                fcb $80, $64, $FE, $26
                fcb $94, $3F, $FF, $D
                fcb $A8, $2C, $FF, $D
                fcb $BC, $19, $FF, $5E
                fcb $DA, 6
byte_856C:      fcb 7                   ; DATA XREF: sub_CD65+39↓o
                fcb $58, $3E, $FF, $9A
                fcb $6C, $36, $FF, $1A
                fcb $80, $24, $FF, $5A
                fcb $94, $17, $FF, $73
                fcb $A8, $C, $FF, $C0
                fcb $BC, 7, $FF, $CD
                fcb $D0, 3
byte_8587:      fcb 3                   ; DATA XREF: sub_CD65+80↓o
                fcb $6C, $61, 0, 0
                fcb $94, $61, 0, 0
                fcb $D0, $61
byte_8592:      fcb 5                   ; DATA XREF: sub_CD65+25↓o
                fcb $6C, $37, $FF, $66
                fcb $80, $2B, $FF, 0
                fcb $94, $17, $FF, $A0
                fcb $BC, 8, $FF, $B3
                fcb $D0, 2
byte_85A5:      fcb $80                 ; DATA XREF: sub_D0D2:loc_D0E6↓r
byte_85A6:      fcb 8                   ; DATA XREF: sub_CD65+13↓o
                fcb $58, $40, $FF, $D
                fcb $6C, $2D, $FF, $5A
                fcb $80, $20, $FF, $5A
                fcb $94, $13, 0, 0
                fcb $A8, $13, $FF, $73
                fcb $BC, 8, $FF, $CD
                fcb $D0, 4, 0, 0
                fcb $E4, 4, $FF, $FF
                fcb $FF, $FF
byte_85C9:      fcb 5                   ; DATA XREF: sub_CE39+32↓o
                fcb $62, $1A, $FF, $BD
                fcb $94, $D, $FF, $E6
                fcb $A8, $B, $FF, $DA
                fcb $BC, 8, $FF, $CD
                fcb $D0, 4
byte_85DC:      fcb 2                   ; DATA XREF: sub_CD65:loc_CD80↓o
                fcb $58, 0, 1, $98
                fcb $F8, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
byte_85EF:      fcb 4                   ; DATA XREF: RESERVED:CFF3↓o
                fcb $E, $80, $F3, $33
                fcb $13, $40, $F8, 0
                fcb $19, $10, $FD, $55
                fcb $1F, 0, $FF, $FF
                fcb $FF, $FF
byte_8602:      fcb 9                   ; DATA XREF: RESERVED:CFCA↓o
                fcb 9
                fcb 0
                fcb $4D, $4D, $4D, $52, $52, $6A, $6C, $72, $72
                fcb $3A, $3A, $3A, $36, $34, $40, $44, $4C, $50
                fcb $3A, $3A, $3A, $2C, $30, $34, $38, $40, $44
                fcb $1E, $1A, $1A, $1A, $13, $15, $17, $19, $19
                fcb $E, $E, $E, $E, $E, $10, $10, $11, $11
                fcb $C, $C, $C, 8, 8, 6, 5, 5, 5
                fcb 0, 0, 0, 0, 0, 0, 0, 0, 0
                fcb 0, 0, 0, 0, 0, 0, 0, 0, 1
                fcb 0, 0, 0, 0, 0, 0, 1, 2, 3
byte_8656:      fcb 2                   ; DATA XREF: sub_D14D+128↓o
                fcb $20, 0, 0, 0
                fcb $FF, 0
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
byte_8679:      fcb 9                   ; DATA XREF: sub_CDF1+2↓o
                fcb $58, $51, $FF, $2D
                fcb $6F, $3E, $FF, $3C
                fcb $80, $31, $FF, $3C
                fcb $91, $24, $FA, 0
                fcb $92, $1E, $FF, $39
                fcb $A4, $10, $FF, $EB
                fcb $B0, $F, $FF, $72
                fcb $CB, 0, 0, 0
                fcb $DA, 0
byte_869C:      fcb 8                   ; DATA XREF: sub_CDF1+C↓o
                fcb $69, $FF, $F8, $C0
                fcb $71, $C5, $FB, $F1
                fcb $82, $80, $FD, $E0
                fcb $92, $5E, $FE, $70
                fcb $A2, $45, $FF, 8
                fcb $C2, $26, $FF, $6D
                fcb $E3, $13, $FF, $52
                fcb $FF, 0
byte_86BB:      fcb $44                 ; DATA XREF: __RESET+2F1↓r
                                        ; sub_CA13+B↓r
byte_86BC:      fcb 5                   ; DATA XREF: sub_CA13+13↓o
                fcb $65, $F4, $FC, $B
                fcb $94, $3A, $FF, $44
                fcb $B2, $24, $FF, $55
                fcb $D0, $10, 0, 0
                fcb $E4, $10
byte_86CF:      fcb 9                   ; DATA XREF: sub_C97D+3A↓o
                fcb $65, $FF, $FD, $5A
                fcb $76, $D2, $F9, $9A
                fcb $80, $92, $FC, $5A
                fcb $94, $49, $FE, $4D
                fcb $A8, $27, $FF, $40
                fcb $BC, $18, $FF, $C0
                fcb $D0, $13, $FF, $DA
                fcb $E4, $10, $FF, $E6
                fcb $F8, $E
byte_86F2:      fcb 3                   ; DATA XREF: sub_C97D+43↓o
                fcb $B2, $E4, 0, $76
                fcb $CC, $F0, 0, $A7
                fcb $E3, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF
byte_8705:      fcb 6                   ; DATA XREF: sub_C97D+50↓o
                fcb $1C, 0, 3, $2B
                fcb $28, $26, 1, $A0
                fcb $38, $40, 2, $60
                fcb $48, $66, 0, 0
                fcb $60, $66, $FF, $65
                fcb $B4, $33
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
byte_8728:      fcb 5                   ; DATA XREF: sub_C97D+6C↓o
                fcb 6, 0, 8, $AB
                fcb 9, $1A, 4, 0
                fcb $C, $26, 6, $80
                fcb $E, $33, 6, $80
                fcb $10, $40
byte_873B:      fcb $F                  ; DATA XREF: sub_D14D+1FF↓r
                fcb $A0
byte_873D:      fcb $FF                 ; DATA XREF: sub_D14D+1D0↓r
byte_873E:      fcb $FF                 ; DATA XREF: sub_D14D+1D7↓r
byte_873F:      fcb 0                   ; DATA XREF: sub_D14D+1E5↓r
byte_8740:      fcb 7                   ; DATA XREF: sub_CD65+43↓o
                fcb $6C, $14, $FF, $73
                fcb $80, 9, $FF, $E6
                fcb $94, 7, 0, 0
                fcb $A8, 7, 0, 0
                fcb $BC, 7, $FF, $CD
                fcb $D0, 3, 0, 6
                fcb $F8, 4
byte_875B:      fcb 2                   ; DATA XREF: sub_CD65+61↓o
                fcb $80, $33, 0, 0
                fcb $E4, $33
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
byte_8776:      fcb 7                   ; DATA XREF: sub_CE79+60↓o
                fcb $58, $14, $FF, $C6
                fcb $80, $B, $FF, $C0
                fcb $94, 6, $FF, $E6
                fcb $A8, 4, 0, 0
                fcb $BC, 4, $FF, $F3
                fcb $D0, 3, 0, 0
                fcb $DA, 3
byte_8791:      fcb 7                   ; DATA XREF: sub_CE79+41↓o
                fcb $62, $A, $FF, $EF
                fcb $80, 8, $FF, $F3
                fcb $94, 7, $FF, $F3
                fcb $A8, 6, 0, 0
                fcb $BC, 6, 0, $D
                fcb $D0, 7, 0, 0
                fcb $DA, 7
byte_87AC:      fcb 7                   ; DATA XREF: sub_CD65+4D↓o
                fcb $62, $1A, 0, $33
                fcb $80, $20, 2, $C0
                fcb $94, $57, 0, $66
                fcb $A8, $5F, 0, $73
                fcb $BC, $68, $FF, $E6
                fcb $D0, $66, 0, $80
                fcb $E4, $70
byte_87C7:      fcb 4                   ; DATA XREF: sub_CD65+6B↓o
                fcb $80, $80, $FD, $73
                fcb $94, $4D, $FF, $5A
                fcb $A8, $40, $FF, $AD
                fcb $D0, $33
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
byte_87E2:      fcb 7                   ; DATA XREF: sub_CD65+2F↓o
                fcb $58, $FE, 0, 0
                fcb $6C, $FE, 0, 0
                fcb $80, $FE, $FF, $D
                fcb $94, $EB, 0, $F3
                fcb $A8, $FE, $FC, $CD
                fcb $BC, $BE, $FB, $B3
                fcb $D0, $68
byte_87FD:      fcb 4                   ; DATA XREF: sub_CA82+11↓r
byte_87FE:      fcb $3F                 ; DATA XREF: sub_CA82+2D↓r
byte_87FF:      fcb 9                   ; DATA XREF: sub_CA82:loc_CADD↓o
                fcb 9
                fcb 0
                fcb 5, $15, $D0, $D0, $D0, $D0, $D0, $D0, $F0
                fcb 5, $15, $A0, $A0, $A0, $A0, $A0, $A0, $F0
                fcb 5, 5, $A0, $A0, $A0, $A0, $A0, $A0, $F0
                fcb 0, 0, $A0, $A0, $A0, $A0, $A0, $A0, $F0
                fcb 0, 0, 0, $A0, $A0, $A0, $A0, $A0, $F0
                fcb 0, 0, 0, $A0, $A0, $A0, $A0, $A0, $F0
                fcb 0, 0, 0, 0, $A0, $A0, $A0, $A0, $F0
                fcb 0, 0, 0, 0, $A0, $A0, $A0, $A0, $F0
                fcb 0, 0, 0, 0, 0, $A0, $A0, $A0, $F0
byte_8853:      fcb 3                   ; DATA XREF: sub_CA82+32↓o
                fcb 4, 0, 8, 0
                fcb 8, $20, 3, $D8
                fcb $42, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
byte_8872:      fcb 3                   ; DATA XREF: sub_CA82+84↓o
                fcb $80, $FE, $FC, $E6
                fcb $94, $C0, $FB, $33
                fcb $BC, 0, $FF, $FF
                fcb $FF, $FF
byte_8881:      fcb 7                   ; DATA XREF: sub_CD65+57↓o
                fcb $6C, $44, 0, 0
                fcb $80, $44, 0, 0
                fcb $94, $44, 0, 0
                fcb $A8, $44, $FE, $33
                fcb $BC, $20, $FF, $B3
                fcb $D0, $1A, $FF, $80
                fcb $E4, $10
byte_889C:      fcb 3                   ; DATA XREF: sub_CD65+75↓o
                fcb $6C, $99, 0, 0
                fcb $94, $99, 0, 0
                fcb $D0, $99
byte_88A7:      fcb $20                 ; DATA XREF: sub_CEF4:loc_CF3F↓o
                fcb $20
byte_88A9:      fcb $FF                 ; DATA XREF: sub_D14D+98↓r
                                        ; sub_D14D+9D↓r ...
                fcb $B1
byte_88AB:      fcb 0                   ; DATA XREF: sub_CA82+AA↓r
                                        ; sub_CA82+AF↓r ...
                fcb $60
byte_88AD:      fcb 1                   ; DATA XREF: sub_D381:loc_D3F4↓r
                                        ; sub_D381:loc_D411↓r
                fcb $C2
byte_88AF:      fcb 1                   ; DATA XREF: sub_BE83+2↓r
                                        ; sub_C574+2↓r
                fcb $F4
byte_88B1:      fcb 0                   ; DATA XREF: sub_BE83+B↓r
                                        ; sub_C574+B↓r
byte_88B2:      fcb $9D                 ; DATA XREF: sub_CFA0:loc_CFAD↓r
byte_88B3:      fcb $A0                 ; DATA XREF: sub_CFA0:loc_CFB5↓r
                                        ; sub_D14D+6B↓o ...
byte_88B4:      fcb $FF                 ; DATA XREF: sub_D14D:loc_D1AF↓o
                                        ; sub_D14D+1A9↓o
                fcb $FF
byte_88B6:      fcb $CD                 ; DATA XREF: RESERVED:CFDC↓r
byte_88B7:      fcb 9                   ; DATA XREF: sub_CD20+2E↓o
                                        ; sub_CD65+9↓o
                fcb $58, $8C, $FF, 0
                fcb $6C, $78, $FE, $C0
                fcb $80, $5F, $FE, $4D
                fcb $94, $3D, 0, 0
                fcb $A0, $3D, 9, $80
                fcb $A8, $89, 0, 0
                fcb $BC, $89, 4, $8D
                fcb $D0, $E4, 0, 0
                fcb $E4, $E4
byte_88DA:      fcb 3                   ; DATA XREF: sub_CE39+10↓r
byte_88DB:      fcb $19                 ; DATA XREF: sub_CE39+24↓r
byte_88DC:      fcb 6                   ; DATA XREF: sub_CDF1+21↓o
                fcb $92, $1F, $FF, $70
                fcb $A2, $16, $FF, $90
                fcb $B2, $F, $FF, $B0
                fcb $C2, $A, $FF, $E6
                fcb $CC, 9, $FF, $9C
                fcb $E3, 0
                fcb $FF, $FF, $FF, $FF
byte_88F7:      fcb $80                 ; DATA XREF: sub_CF6B↓o
byte_88F8:      fcb 5                   ; DATA XREF: sub_CE79+6A↓r
byte_88F9:      fcb 4                   ; DATA XREF: sub_CE79+3B↓r
byte_88FA:      fcb 0                   ; DATA XREF: sub_CE79+2↓r
byte_88FB:      fcb $2D                 ; DATA XREF: sub_CE79+19↓r
byte_88FC:      fcb 4                   ; DATA XREF: sub_D019+49↓r
byte_88FD:      fcb $FE                 ; DATA XREF: sub_D019+37↓r
byte_88FE:      fcb $80                 ; DATA XREF: sub_CF6B+16↓o
byte_88FF:      fcb $FA                 ; DATA XREF: IC1I+178↓r
byte_8900:      fcb $10                 ; DATA XREF: sub_CEF4+3A↓o
                                        ; sub_D074+19↓r
                fcb $20
byte_8902:      fcb $1E                 ; DATA XREF: sub_D074+E↓r
byte_8903:      fcb 5                   ; DATA XREF: sub_D074+47↓r
byte_8904:      fcb $80                 ; DATA XREF: sub_CEF4+61↓o
                                        ; sub_D074+38↓r
                fcb $33
byte_8906:      fcb 2                   ; DATA XREF: sub_BBA6↓o
                                        ; sub_C28F↓o
                fcb $13, 0, 1, $6C
                fcb $6D, $80
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
byte_8919:      fcb 4                   ; DATA XREF: sub_C97D+1B↓o
                fcb $8D, $30, $FD, $B7
                fcb $94, $20, 0, 0
                fcb $A3, $20, $FF, $89
                fcb $D0, $B
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
byte_893C:      fcb $92                 ; DATA XREF: sub_BE83+54↓r
                                        ; sub_C574+54↓r
byte_893D:      fcb 5                   ; DATA XREF: sub_BBA6+10↓o
                fcb 9
                fcb 0
                fcb $17, $17, $17, $17, $17, $17, $17, $17, $17
                fcb $17, $17, $17, $17, $17, $17, $17, $17, $17
                fcb $17, $17, $17, $17, $17, $17, $17, $17, $17
                fcb $17, $17, $17, $17, $17, $17, $17, $17, $17
                fcb $17, $17, $17, $17, $17, $17, $17, $17, $17
byte_896D:      fcb 5                   ; DATA XREF: sub_BBA6+1E↓o
                fcb 9
                fcb 0
                fcb $16, $16, $16, $16, $16, $16, $16, $16, $16
                fcb $16, $16, $16, $16, $16, $16, $16, $16, $16
                fcb $16, $16, $16, $16, $16, $16, $16, $16, $16
                fcb $16, $16, $16, $16, $16, $16, $16, $16, $16
                fcb $16, $16, $16, $16, $16, $16, $16, $16, $16
byte_899D:      fcb $22                 ; DATA XREF: sub_BE83+6A↓r
                                        ; sub_BE83+A7↓r
byte_899E:      fcb $14                 ; DATA XREF: sub_BE83+6F↓r
                                        ; sub_BE83+AC↓r
byte_899F:      fcb $24                 ; DATA XREF: sub_C0E4:loc_C10E↓o
                fcb $2D
                fcb $71
                fcb $A2
byte_89A3:      fcb 2                   ; DATA XREF: sub_C0E4+46↓r
byte_89A4:      fcb 8                   ; DATA XREF: sub_C0E4+64↓r
byte_89A5:      fcb 2                   ; DATA XREF: sub_C0E4+6↓r
byte_89A6:      fcb 3                   ; DATA XREF: sub_C0E4+F↓r
byte_89A7:      fcb $7F                 ; DATA XREF: sub_C23C↓r
byte_89A8:      fcb $81                 ; DATA XREF: sub_C23C+B↓r
                                        ; sub_C23C+12↓r
byte_89A9:      fcb 0                   ; DATA XREF: sub_BE83+18F↓r
                                        ; sub_C574+18C↓r
unk_89AA:       fcb   5                 ; DATA XREF: sub_BE83+19D↓o
                fcb   5
                fcb   5
                fcb   5
                fcb   5
                fcb   5
                fcb   5
                fcb   5
                fcb   5
                fcb   5
                fcb   5
                fcb   5
                fcb   5
                fcb   5
                fcb   5
                fcb   5
                fcb   5
                fcb   5
                fcb   1
                fcb   1
                fcb   1
                fcb   1
                fcb  $E
                fcb $11
                fcb  $E
                fcb $10
                fcb $10
                fcb $18
                fcb $10
                fcb $15
                fcb  $F
                fcb $10
                fcb $11
                fcb $12
                fcb $11
                fcb $13
                fcb $11
                fcb $13
                fcb $12
                fcb $12
                fcb   3
                fcb   2
                fcb   3
                fcb   2
byte_89D6:      fcb $FD                 ; DATA XREF: sub_BE83+1EA↓r
byte_89D7:      fcb 0                   ; DATA XREF: sub_BE83+1F4↓r
byte_89D8:      fcb 1                   ; DATA XREF: sub_C1F5:loc_C224↓o
                fcb $FF
                fcb 1
                fcb $FF
                fcb 1
                fcb $FF
                fcb 1
                fcb $FF
                fcb 1
                fcb $FF
                fcb 1
                fcb $FF
                fcb 1
                fcb $FF
                fcb 1
                fcb $FF
                fcb 1
                fcb $FF
                fcb 2
                fcb $FE
                fcb 2
                fcb $FE
                fcb   4
                fcb   4
                fcb   4
                fcb   4
                fcb   2
                fcb   4
                fcb   4
                fcb   6
                fcb   4
                fcb   4
                fcb   4
                fcb   4
                fcb   4
                fcb   4
                fcb   4
                fcb   4
                fcb   3
                fcb   4
                fcb $10
                fcb $10
                fcb $10
                fcb $10
byte_8A04:      fcb 0                   ; DATA XREF: sub_BE83+14F↓r
                                        ; sub_C1F5:loc_C200↓r ...
byte_8A05:      fcb 4                   ; DATA XREF: sub_C1F5+14↓o
                fcb 2
                fcb 4
                fcb $FE
byte_8A09:      fcb 0                   ; DATA XREF: sub_C23C+37↓r
                                        ; sub_C23C:loc_C278↓r
byte_8A0A:      fcb 5                   ; DATA XREF: sub_C28F+10↓o
                fcb 9
                fcb 0
                fcb $17, $17, $17, $17, $17, $17, $17, $17, $17
                fcb $17, $17, $17, $17, $17, $17, $17, $17, $17
                fcb $17, $17, $17, $17, $17, $17, $17, $17, $17
                fcb $17, $17, $17, $17, $17, $17, $17, $17, $17
                fcb $17, $17, $17, $17, $17, $17, $17, $17, $17
byte_8A3A:      fcb 5                   ; DATA XREF: sub_C28F+1E↓o
                fcb 9
                fcb 0
                fcb $16, $16, $16, $16, $16, $16, $16, $16, $16
                fcb $16, $16, $16, $16, $16, $16, $16, $16, $16
                fcb $16, $16, $16, $16, $16, $16, $16, $16, $16
                fcb $16, $16, $16, $16, $16, $16, $16, $16, $16
                fcb $16, $16, $16, $16, $16, $16, $16, $16, $16
byte_8A6A:      fcb $22                 ; DATA XREF: sub_C574+6A↓r
                                        ; sub_C574+A4↓r
byte_8A6B:      fcb $14                 ; DATA XREF: sub_C574+6F↓r
                                        ; sub_C574+A9↓r
byte_8A6C:      fcb $24                 ; DATA XREF: sub_C7D2:loc_C7FC↓o
                fcb $2D
                fcb $71
                fcb $A2
byte_8A70:      fcb 2                   ; DATA XREF: sub_C7D2+46↓r
byte_8A71:      fcb 8                   ; DATA XREF: sub_C7D2+64↓r
byte_8A72:      fcb 2                   ; DATA XREF: sub_C7D2+6↓r
byte_8A73:      fcb 3                   ; DATA XREF: sub_C7D2+F↓r
byte_8A74:      fcb $7F                 ; DATA XREF: sub_C92A↓r
byte_8A75:      fcb $81                 ; DATA XREF: sub_C92A+B↓r
                                        ; sub_C92A+12↓r
unk_8A76:       fcb   5                 ; DATA XREF: sub_C574+19A↓o
                fcb   5
                fcb   5
                fcb   5
                fcb   5
                fcb   5
                fcb   5
                fcb   5
                fcb   5
                fcb   5
                fcb   5
                fcb   5
                fcb   5
                fcb   5
                fcb   5
                fcb   5
                fcb   5
                fcb   5
                fcb   1
                fcb   1
                fcb   5
                fcb   5
                fcb $10
                fcb $11
                fcb  $E
                fcb $10
                fcb $10
                fcb $18
                fcb $10
                fcb $15
                fcb  $E
                fcb $10
                fcb $11
                fcb $11
                fcb $12
                fcb $10
                fcb $12
                fcb $12
                fcb $12
                fcb $13
                fcb   3
                fcb   2
                fcb   6
                fcb   5
byte_8AA2:      fcb $FD                 ; DATA XREF: sub_C574+1E7↓r
byte_8AA3:      fcb 0                   ; DATA XREF: sub_C574+1F1↓r
unk_8AA4:       fcb   1                 ; DATA XREF: sub_C8E3:loc_C912↓o
                fcb $FF
                fcb   1
                fcb $FF
                fcb   1
                fcb $FF
                fcb   1
                fcb $FF
                fcb   1
                fcb $FF
                fcb   1
                fcb $FF
                fcb   1
                fcb $FF
                fcb   1
                fcb $FF
                fcb   1
                fcb $FF
                fcb   2
                fcb $FE
                fcb   2
                fcb $FE
                fcb   4
                fcb   4
                fcb   4
                fcb   4
                fcb   2
                fcb   4
                fcb   4
                fcb   6
                fcb   4
                fcb   4
                fcb   4
                fcb   4
                fcb   4
                fcb   4
                fcb   4
                fcb   4
                fcb   3
                fcb   4
                fcb $10
                fcb $10
                fcb   8
                fcb   8
byte_8AD0:      fcb 4                   ; DATA XREF: sub_C8E3+14↓o
                fcb 2
                fcb 4
                fcb $FE
byte_8AD4:      fcb 0                   ; DATA XREF: sub_C92A+37↓r
                                        ; sub_C92A:loc_C966↓r
byte_8AD5:      fcb $CD                 ; DATA XREF: sub_C97D+C↓r
byte_8AD6:      fcb 4                   ; DATA XREF: sub_C97D+11↓r
byte_8AD7:      fcb $15                 ; DATA XREF: sub_BE83+39↓r
                                        ; sub_C574+39↓r ...
byte_8AD8:      fcb $CD                 ; DATA XREF: sub_BE83+29↓r
                                        ; sub_C574+29↓r
byte_8AD9:      fcb $E4                 ; DATA XREF: sub_BD64+3↓r
                                        ; sub_C455+3↓r
byte_8ADA:      fcb $94                 ; DATA XREF: sub_BD64+A↓r
                                        ; sub_C455+A↓r
byte_8ADB:      fcb 0                   ; DATA XREF: sub_BD64+112↓r
                                        ; sub_C455+112↓r
byte_8ADC:      fcb $92                 ; DATA XREF: sub_BD64+57↓r
                                        ; sub_C455+57↓r
byte_8ADD:      fcb $B6                 ; DATA XREF: sub_C164:loc_C190↓r
                                        ; sub_C852:loc_C87E↓r
byte_8ADE:      fcb 4                   ; DATA XREF: sub_C164+5B↓r
                                        ; sub_C852+5B↓r ...
byte_8ADF:      fcb $B6                 ; DATA XREF: sub_C164:loc_C178↓r
                                        ; sub_C852:loc_C866↓r
byte_8AE0:      fcb 4                   ; DATA XREF: sub_BD64:loc_BD7A↓r
                                        ; sub_C455:loc_C46B↓r
byte_8AE1:      fcb 3                   ; DATA XREF: sub_BD64+29↓r
                                        ; sub_C455+29↓r
byte_8AE2:      fcb 8                   ; DATA XREF: sub_BD64+30↓r
                                        ; sub_BD64+88↓r ...
byte_8AE3:      fcb $2E                 ; DATA XREF: sub_BD64+7F↓r
                                        ; sub_C455+7F↓r
byte_8AE4:      fcb $64                 ; DATA XREF: sub_BD64+46↓o
                                        ; sub_C455+46↓o
                fcb $81
                fcb $9B
                fcb $B5
                fcb $D2
byte_8AE9:      fcb $2C                 ; DATA XREF: sub_BD64+AC↓o
                                        ; sub_BD64:loc_BE15↓r ...
byte_8AEA:      fcb 4                   ; DATA XREF: sub_BD64+B7↓r
                                        ; sub_C455+B7↓r
byte_8AEB:      fcb 8                   ; DATA XREF: sub_BD64+99↓r
                                        ; sub_C455+99↓r
byte_8AEC:      fcb $14                 ; DATA XREF: sub_BE83:loc_BF69↓r
                                        ; sub_C574:loc_C657↓r
byte_8AED:      fcb $E3                 ; DATA XREF: sub_BE83+FA↓r
                                        ; sub_C574+F7↓r
byte_8AEE:      fcb 8                   ; DATA XREF: sub_C164+45↓r
                                        ; sub_C852+45↓r
byte_8AEF:      fcb $5E                 ; DATA XREF: sub_BE83+105↓r
                                        ; sub_C574+102↓r
byte_8AF0:      fcb $26                 ; DATA XREF: sub_BBCE+4D↓r
                                        ; sub_C2B7+4D↓r
byte_8AF1:      fcb $10                 ; DATA XREF: sub_BBCE:loc_BC2F↓r
                                        ; sub_C2B7:loc_C318↓r
byte_8AF2:      fcb $7E                 ; DATA XREF: sub_BBCE+48↓o
                                        ; sub_C2B7+48↓o
                fcb $81
                fcb 1
byte_8AF5:      fcb $40                 ; DATA XREF: sub_BBCE+94↓r
                                        ; sub_C2B7+94↓r
byte_8AF6:      fcb $4B                 ; DATA XREF: sub_BBCE+7D↓r
                                        ; sub_BBCE+90↓o ...
byte_8AF7:      fcb $B5                 ; DATA XREF: sub_BBCE+84↓r
                                        ; sub_C2B7+84↓r
                fcb 1
byte_8AF9:      fcb 2                   ; DATA XREF: sub_C164+38↓o
                                        ; sub_C852+38↓o
                fcb $CC, $31, 0, $64
                fcb $E3, $3A
                fcb $FF, $FF, $FF, $FF
byte_8B04:      fcb $E                  ; DATA XREF: __RESET:loc_94C1↓r
                                        ; __RESET+3B7↓r ...
byte_8B05:      fcb 2                   ; DATA XREF: __RESET+398↓r
                                        ; __RESET+3BF↓r ...
byte_8B06:      fcb 4                   ; DATA XREF: __RESET+39D↓r
                                        ; __RESET+3C7↓r ...
byte_8B07:      fcb 5                   ; DATA XREF: __RESET+3A2↓r
                                        ; __RESET+3CF↓r ...
byte_8B08:      fcb $1E                 ; DATA XREF: sub_BCC3:loc_BCE7↓r
                                        ; sub_C3AC:loc_C3D0↓r
byte_8B09:      fcb 5                   ; DATA XREF: sub_BCC3+21↓r
                                        ; sub_C3AC+21↓r
byte_8B0A:      fcb $1E                 ; DATA XREF: sub_BCC3:loc_BD0C↓r
                                        ; sub_C3AC:loc_C3F5↓r
byte_8B0B:      fcb 5                   ; DATA XREF: sub_BCC3+46↓r
                                        ; sub_C3AC+46↓r
byte_8B0C:      fcb $1E                 ; DATA XREF: sub_BCC3:loc_BD31↓r
                                        ; sub_C3AC:loc_C41A↓r
byte_8B0D:      fcb 5                   ; DATA XREF: sub_BCC3+6B↓r
                                        ; sub_C3AC+6B↓r
byte_8B0E:      fcb $1E                 ; DATA XREF: sub_BCC3:loc_BD56↓r
                                        ; sub_C3AC:loc_C43F↓r
byte_8B0F:      fcb 5                   ; DATA XREF: sub_BCC3+90↓r
                                        ; sub_C3AC+90↓r
byte_8B10:      fcb $58                 ; DATA XREF: __RESET+42E↓r
byte_8B11:      fcb $D0                 ; DATA XREF: __RESET+355↓r
                                        ; __RESET+36C↓r
byte_8B12:      fcb 7                   ; DATA XREF: sub_BE83+E1↓r
                                        ; sub_C574+DE↓r
byte_8B13:      fcb $11                 ; DATA XREF: sub_D61C+12↓o
                fcb $11
byte_8B15:      fcb $BC                 ; DATA XREF: sub_D61C+2↓o
byte_8B16:      fcb $BD                 ; DATA XREF: sub_BBCE+13↓r
                                        ; sub_BD64+E9↓r ...
byte_8B17:      fcb $58                 ; DATA XREF: sub_CC8F+2↓r
byte_8B18:      fcb 5                   ; DATA XREF: sub_CC8F+12↓r
byte_8B19:      fcb 2                   ; DATA XREF: sub_CC8F:loc_CCCD↓o
                fcb $5E, $F3, 0, 0
                fcb $8D, $F3
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
byte_8B3C:      fcb 6                   ; DATA XREF: sub_CC8F+29↓o
                fcb $13, 0, 0, 0
                fcb $45, 0, 2, $AB
                fcb $51, $20, 5, $10
                fcb $61, $71, 1, $55
                fcb $6D, $81, 1, $BD
                fcb $80, $A2
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
byte_8B5F:      fcb 6                   ; DATA XREF: sub_CC8F+B↓o
                                        ; sub_CC8F:loc_CCA7↓o ...
                fcb $13, $1F, 0, 0
                fcb $58, $1F, 1, $4F
                fcb $65, $30, 0, $D5
                fcb $71, $3A, 0, 0
                fcb $89, $3A, 0, $9E
                fcb $96, $42
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
byte_8B82:      fcb $11                 ; DATA XREF: sub_CC8F:loc_CCDD↓o
                fcb 9
                fcb 0
                fcb 0, 0, 0, 0, 0, 0, 0, 0, 0
                fcb 0, 0, 0, 0, 0, 0, 0, 0, 0
                fcb 0, 0, 0, 0, 0, 0, 0, 0, 0
                fcb 0, 0, 0, 0, 0, 0, 0, 0, 0
                fcb 0, 0, 0, 0, 0, 0, 0, 0, 0
                fcb 0, 0, 0, 0, 0, 0, 0, 0, 0
                fcb 0, 0, 0, 0, 0, 0, 0, 0, 0
                fcb 0, 0, 0, 0, 0, 0, 0, 0, 0
                fcb 0, 0, 0, 0, 0, 0, 0, 0, 0
                fcb $A, $A, $A, $A, $A, $A, $A, $10, $10
                fcb $A, $A, $A, $A, $A, $A, $10, $19, $19
                fcb $10, $10, $10, $10, $10, $14, $19, $1A, $1A
                fcb $10, $10, $10, $10, $10, $18, $1D, $35, $35
                fcb $10, $10, $10, $10, $1B, $27, $40, $43, $48
                fcb $10, $10, $10, $20, $22, $34, $3C, $48, $48
                fcb $10, $10, $10, $20, $2A, $34, $41, $48, $48
                fcb $10, $10, $10, $20, $2A, $38, $46, $48, $48
byte_8C1E:      fcb $80                 ; DATA XREF: sub_D381+6E↓r
byte_8C1F:      fcb 3                   ; DATA XREF: sub_D381+39↓r
                                        ; sub_D381+48↓r ...
                fcb $84
byte_8C21:      fcb 2                   ; DATA XREF: sub_D381:loc_D3B5↓r
byte_8C22:      fcb $BF                 ; DATA XREF: sub_D381:loc_D395↓r
byte_8C23:      fcb $DB                 ; DATA XREF: sub_CB52+1C↓r
byte_8C24:      fcb 5                   ; DATA XREF: sub_CB52:loc_CBD0↓r
byte_8C25:      fcb 1                   ; DATA XREF: sub_CC29+23↓r
byte_8C26:      fcb $10                 ; DATA XREF: sub_CB52+2↓r
byte_8C27:      fcb $1E                 ; DATA XREF: sub_CB52+9↓r
byte_8C28:      fcb $94                 ; DATA XREF: sub_CB52+10↓r
byte_8C29:      fcb 0                   ; DATA XREF: sub_CC29+D↓r
                                        ; sub_CC29+1B↓r
                fcb 0
byte_8C2B:      fcb 0                   ; DATA XREF: sub_CC29+32↓r
                                        ; sub_CC29+3F↓r ...
                fcb 0
byte_8C2D:      fcb $22                 ; DATA XREF: sub_CB52+17↓r
byte_8C2E:      fcb 2                   ; DATA XREF: sub_CB52:loc_CB8B↓r
byte_8C2F:      fcb 2                   ; DATA XREF: sub_CB52+4A↓r
                                        ; sub_CB52+58↓r ...
                fcb $EE
byte_8C31:      fcb $61                 ; DATA XREF: sub_CB52:loc_CBDE↓r
                fcb $F0
byte_8C33:      fcb $C                  ; DATA XREF: sub_CB52+93↓r
                fcb $80
byte_8C35:      fcb $E0                 ; DATA XREF: sub_CB52+A0↓r
byte_8C36:      fcb 6                   ; DATA XREF: sub_CB52+A7↓r
byte_8C37:      fcb $A5                 ; DATA XREF: sub_CB52:loc_CC0C↓r
                fcb $A0
byte_8C39:      fcb $C                  ; DATA XREF: sub_CB52+C1↓r
                fcb $80
byte_8C3B:      fcb $58                 ; DATA XREF: sub_B800+19D↓r
byte_8C3C:      fcb 1                   ; DATA XREF: IC1I+27C↓r
byte_8C3D:      fcb 0                   ; DATA XREF: sub_B800+1A4↓r
                fcb 0
byte_8C3F:      fcb $C                  ; DATA XREF: sub_B800+190↓r
byte_8C40:      fcb $14                 ; DATA XREF: sub_B800:loc_B9F4↓r
byte_8C41:      fcb 2                   ; DATA XREF: sub_B800+1B2↓o
                fcb 5, 0, 4, 0
                fcb 7, 8
                fcb $FF, $FF, $FF, $FF
byte_8C4C:      fcb 2                   ; DATA XREF: sub_B800+1A9↓o
                fcb 5, 0, $FE, 0
                fcb $F, $EC
                fcb $FF, $FF, $FF, $FF
byte_8C57:      fcb $71                 ; DATA XREF: sub_DB67+25↓r
byte_8C58:      fcb 5                   ; DATA XREF: sub_D6A4+C2↓o
                fcb $6C, $B4, $FC, $4D
                fcb $80, $6A, $FF, $73
                fcb $94, $5F, $FE, $FC
                fcb $D0, $22, 0, 0
                fcb $E4, $22
byte_8C6B:      fcb 3                   ; DATA XREF: sub_D6A4+CB↓o
                fcb $9F, $20, $FF, $BC
                fcb $CC, $14, $FF, $21
                fcb $E3, 0
byte_8C76:      fcb $10                 ; DATA XREF: sub_D6A4+1EC↓r
byte_8C77:      fcb $76                 ; DATA XREF: sub_D6A4+1F6↓r
byte_8C78:      fcb $C0                 ; DATA XREF: sub_D6A4+207↓r
byte_8C79:      fcb $DA                 ; DATA XREF: sub_D92D+99↓r
byte_8C7A:      fcb 3                   ; DATA XREF: sub_D6A4+1FB↓o
                                        ; sub_D92D:loc_D9BE↓o
                fcb 4, 8, 0, 0
                fcb $28, 8, 0, $66
                fcb $3C, $10
                fcb $FF, $FF, $FF, $FF
byte_8C89:      fcb 0                   ; DATA XREF: sub_D6A4+228↓r
                                        ; sub_D6A4+22D↓r ...
byte_8C8A:      fcb 4                   ; DATA XREF: sub_D6A4+197↓o
                fcb $58, $5A, $FF, $C0
                fcb $80, $50, $FF, 6
                fcb $A9, $28, $FE, $F3
                fcb $CF, 0
byte_8C99:      fcb 3                   ; DATA XREF: sub_D6A4+1A2↓o
                fcb 0, 0, 0, 0
                fcb 3, 0, 0, 0
                fcb $1A, 0
byte_8CA4:      fcb 4                   ; DATA XREF: sub_D6A4+1DA↓o
                fcb 1, 0, 1, 0
                fcb 3, 2, 0, $76
                fcb $10, 8, 0, $52
                fcb $29, $10
byte_8CB3:      fcb 4                   ; DATA XREF: sub_D6A4+1C8↓o
                fcb $16, 0, 1, $1C
                fcb $1F, $A, 0, $30
                fcb $3F, $10, 1, 0
                fcb $75, $46
byte_8CC2:      fcb 3                   ; DATA XREF: sub_D6A4+1B5↓o
                fcb $B2, $54, $FF, $9E
                fcb $CC, $4A, $FF, $91
                fcb $E3, $40
byte_8CCD:      fcb 2                   ; DATA XREF: sub_D6A4+74↓o
                fcb $58, $83, $FF, $95
                fcb $D0, $51
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
byte_8CE0:      fcb 2                   ; DATA XREF: sub_D6A4:loc_D6C5↓o
                fcb $58, $83, $FF, $95
                fcb $D0, $51
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
byte_8CF3:      fcb 3                   ; DATA XREF: sub_D6A4+83↓o
                fcb 0, 0, 0, 0
                fcb 4, 0, 0, 0
                fcb 7, 0
byte_8CFE:      fcb 0                   ; DATA XREF: sub_D6A4+93↓r
byte_8CFF:      fcb $64                 ; DATA XREF: sub_D6A4:loc_D706↓r
byte_8D00:      fcb 5                   ; DATA XREF: sub_D6A4+162↓o
                fcb $1E, 1, 0, 0
                fcb $50, 2, 0, 0
                fcb $78, 3, 0, 0
                fcb $A0, 5, 0, 0
                fcb $B4, 8
byte_8D13:      fcb 4                   ; DATA XREF: sub_D6A4+16B↓o
                fcb $28, $FF, 0, 0
                fcb $64, $FE, 0, 0
                fcb $A0, $FD, 0, 0
                fcb $FE, $FB
                fcb $FF, $FF, $FF, $FF
byte_8D26:      fcb $A                  ; DATA XREF: sub_D92D+5F↓r
byte_8D27:      fcb 3                   ; DATA XREF: sub_D92D+2B↓r
byte_8D28:      fcb $1A                 ; DATA XREF: sub_D92D+55↓r
byte_8D29:      fcb $F8                 ; DATA XREF: sub_D92D+88↓r
byte_8D2A:      fcb $FD                 ; DATA XREF: sub_D92D+39↓r
byte_8D2B:      fcb $1B                 ; DATA XREF: sub_D92D:loc_D9AB↓r
                fcb 2
                fcb $20, 0, 0, 0
                fcb $FF, 0
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $2F
                fcb 2
                fcb $20, 0, 0, 0
                fcb $FF, 0
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
byte_8D53:      fcb $40                 ; DATA XREF: sub_D6A4:loc_D7FE↓r
                                        ; sub_D9D7+109↓r
byte_8D54:      fcb $B4                 ; DATA XREF: sub_D6A4:loc_D8E9↓r
                                        ; sub_D6A4:loc_D8EE↓r ...
byte_8D55:      fcb $60                 ; DATA XREF: sub_EBC9+154↓r
byte_8D56:      fcb $1F                 ; DATA XREF: sub_D6A4+258↓r
byte_8D57:      fcb 2                   ; DATA XREF: sub_EBC9+15E↓o
                fcb $2F, $5B, 1, $2B
                fcb $7D, $B6
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
byte_8D6A:      fcb $13                 ; DATA XREF: sub_D6A4+21F↓r
                                        ; sub_D6A4+240↓r ...
byte_8D6B:      fcb 0                   ; DATA XREF: sub_D6A4+216↓r
                                        ; sub_D9D7+11C↓r
byte_8D6C:      fcb $19                 ; DATA XREF: sub_D6A4+13F↓r
byte_8D6D:      fcb 3                   ; DATA XREF: sub_D6A4+123↓o
                fcb $6C, 0, 0, 0
                fcb $94, 0, 0, 0
                fcb $D0, 0
byte_8D78:      fcb 3                   ; DATA XREF: sub_D6A4+12A↓o
                fcb $6C, $20, $FF, $CD
                fcb $94, $18, $FF, $B7
                fcb $D0, 7
byte_8D83:      fcb 4                   ; DATA XREF: sub_D9D7+38↓o
                fcb $9F, $D2, 0, $AF
                fcb $B2, $DF, 0, $6C
                fcb $CC, $EA, 0, $F5
                fcb $E3, 0
                fcb $FF, $FF, $FF, $FF
byte_8D96:      fcb 2                   ; DATA XREF: sub_D9D7+4B↓o
                fcb $B, 0, 0, 0
                fcb $1B, 0
                fcb $FF, $FF, $FF, $FF
byte_8DA1:      fcb 5                   ; DATA XREF: sub_D9D7+58↓o
                fcb $63, $6E, $FE, $CB
                fcb $80, $4B, $FE, $9C
                fcb $92, $32, $FF, $C6
                fcb $A8, $2D, $FF, $26
                fcb $D0, $B
byte_8DB4:      fcb 4                   ; DATA XREF: sub_D9D7+8C↓o
                fcb $36, 0, 0, $95
                fcb $42, 7, 0, $52
                fcb $5E, $10, 0, $2E
                fcb $8B, $18
byte_8DC3:      fcb 3                   ; DATA XREF: sub_D9D7+A7↓o
                fcb $9F, 7, $FF, $E9
                fcb $CC, 3, $FF, $DF
                fcb $E3, 0
byte_8DCE:      fcb 2                   ; DATA XREF: sub_D9D7+95↓o
                fcb $80, $80, 1, $CA
                fcb $C7, $FF
                fcb $FF, $FF, $FF, $FF
byte_8DD9:      fcb 4                   ; DATA XREF: sub_D9D7+146↓o
                fcb 2, 0, 0, $66
                fcb 7, 2, 0, $80
                fcb $D, 5, 0, $66
                fcb $12, 7
byte_8DE8:      fcb 4                   ; DATA XREF: sub_D9D7+14E↓o
                fcb 2, 0, $FF, $9A
                fcb 7, $FE, $FF, $AB
                fcb $D, $FC, $FF, $9A
                fcb $12, $FA
byte_8DF7:      fcb $28                 ; DATA XREF: sub_D9D7+141↓r
byte_8DF8:      fcb $CE                 ; DATA XREF: sub_D9D7+DE↓r
byte_8DF9:      fcb 2                   ; DATA XREF: sub_D9D7:loc_DAC1↓r
byte_8DFA:      fcb $16                 ; DATA XREF: sub_D9D7+68↓r
byte_8DFB:      fcb $75                 ; DATA XREF: sub_D9D7:loc_DA09↓r
byte_8DFC:      fcb 0                   ; DATA XREF: sub_D9D7+20↓r
                                        ; sub_D9D7+25↓r ...
byte_8DFD:      fcb $40                 ; DATA XREF: sub_D9D7+CE↓r
byte_8DFE:      fcb $7F                 ; DATA XREF: sub_D9D7+C7↓r
byte_8DFF:      fcb $C                  ; DATA XREF: sub_D457+77↓r
                fcb $80
byte_8E01:      fcb $39                 ; DATA XREF: sub_D457+7C↓r
byte_8E02:      fcb $FF                 ; DATA XREF: sub_D457↓r
byte_8E03:      fcb 0                   ; DATA XREF: sub_D457+16↓r
byte_8E04:      fcb $FD                 ; DATA XREF: sub_D457+55↓r
byte_8E05:      fcb $AB                 ; DATA XREF: sub_D457+6D↓r
                fcb $E0
byte_8E07:      fcb $AB                 ; DATA XREF: sub_D457+72↓r
                fcb $E0
byte_8E09:      fcb 2                   ; DATA XREF: sub_D457+32↓r
                                        ; sub_D92D+45↓r
byte_8E0A:      fcb $B6                 ; DATA XREF: sub_D4F8+15↓r
byte_8E0B:      fcb 7                   ; DATA XREF: sub_D564+1E↓r
byte_8E0C:      fcb 4                   ; DATA XREF: sub_DC08+191↓r
byte_8E0D:      fcb $71                 ; DATA XREF: sub_DC08:loc_DD9F↓r
byte_8E0E:      fcb $B4                 ; DATA XREF: sub_DC08+186↓r
byte_8E0F:      fcb $1B                 ; DATA XREF: sub_DC08+19E↓r
byte_8E10:      fcb $24                 ; DATA XREF: sub_DC08+1BB↓r
                                        ; sub_DC08+1CC↓r
byte_8E11:      fcb $18                 ; DATA XREF: sub_DC08+1AA↓r
byte_8E12:      fcb $6A                 ; DATA XREF: sub_DC08+172↓r
byte_8E13:      fcb 3                   ; DATA XREF: sub_DC08+179↓r
                fcb $FF
byte_8E15:      fcb $92                 ; DATA XREF: sub_DEE3+3D↓r
byte_8E16:      fcb 0                   ; DATA XREF: sub_DEE3:loc_DF76↓r
byte_8E17:      fcb $1C                 ; DATA XREF: sub_DEE3+56↓r
byte_8E18:      fcb $28                 ; DATA XREF: sub_DEE3:loc_DF0D↓r
byte_8E19:      fcb 8                   ; DATA XREF: sub_DEE3+31↓r
byte_8E1A:      fcb 1                   ; DATA XREF: sub_DEE3:loc_DF84↓r
byte_8E1B:      fcb $38                 ; DATA XREF: sub_DEE3+42↓r
byte_8E1C:      fcb $22                 ; DATA XREF: sub_DEE3+DA↓r
byte_8E1D:      fcb 4                   ; DATA XREF: sub_DEE3+80↓o
                fcb $26, $4D, 1, $86
                fcb $3D, $70, 0, 0
                fcb $5B, $70, 0, 0
                fcb $5B, $CC
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
byte_8E34:      fcb 6                   ; DATA XREF: sub_DEE3:loc_DF53↓o
                fcb $1F, 0, 0, 0
                fcb $1F, $A, 1, $1C
                fcb $44, $33, 0, $F9
                fcb $6B, $59, 0, $62
                fcb $8D, $66, 0, 0
                fcb $8D, $CC
byte_8E4B:      fcb 6                   ; DATA XREF: sub_DEE3:loc_DF4E↓o
                fcb $1F, 0, 0, 0
                fcb $1F, $A, 1, $1C
                fcb $44, $33, 0, $F9
                fcb $6B, $59, 0, $62
                fcb $8D, $66, 0, 0
                fcb $8D, $CC
byte_8E62:      fcb $B7                 ; DATA XREF: sub_DEE3+156↓r
byte_8E63:      fcb $7F                 ; DATA XREF: sub_DEE3+133↓r
                                        ; sub_DEE3+1DF↓r
byte_8E64:      fcb 7                   ; DATA XREF: sub_DEE3+114↓o
                fcb $82
                fcb $FF
                fcb $2D
                fcb $FF
                fcb $FF
                fcb 1
                fcb 1
                fcb 3
                fcb $52, $23, 0, $B1
                fcb $86, $47, 0, 0
                fcb $86, $CC
                fcb $FF, $FF, $FF, $FF
                fcb 3
                fcb $52, $23, 0, 0
                fcb $52, 3, 0, 0
                fcb $82, 3
                fcb $FF, $FF, $FF, $FF
                fcb 3
                fcb $4C, $38, 0, $BE
                fcb $82, $60, 0, 0
                fcb $82, $CC
                fcb $FF, $FF, $FF, $FF
                fcb 3
                fcb $4C, $38, 0, 0
                fcb $4C, 2, 0, 0
                fcb $82, 2
                fcb $FF, $FF, $FF, $FF
byte_8EA8:      fcb 7                   ; DATA XREF: sub_DEE3:loc_DFEC↓o
                fcb $4C ; L
                fcb $FF
                fcb $66 ; f
                fcb $FF
                fcb $FF
                fcb   1
                fcb   1
                fcb   4
                fcb $52 ; R
                fcb   3
                fcb   0
                fcb   0
                fcb $52 ; R
                fcb $33 ; 3
                fcb   0
                fcb $AF
                fcb $78 ; x
                fcb $4D ; M
                fcb   0
                fcb   0
                fcb $78 ; x
                fcb $75 ; u
                fcb   2
                fcb $52 ; R
                fcb   3
                fcb   0
                fcb   0
                fcb $78 ; x
                fcb   3
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb 4
                fcb $4C, 2, 0, 0
                fcb $4C, $3C, 1, $1E
                fcb $6E, $62, 0, 0
                fcb $6E, $80
                fcb 2
                fcb $4C, 2, 0, 0
                fcb $78, 2
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
byte_8EEC:      fcb $50                 ; DATA XREF: sub_DDDE+19↓r
byte_8EED:      fcb $3C                 ; DATA XREF: __RESET+E4↓r
                                        ; sub_DDDE+25↓r
byte_8EEE:      fcb $14                 ; DATA XREF: sub_DDDE+2A↓r
byte_8EEF:      fcb 5                   ; DATA XREF: sub_DDDE+3C↓r
byte_8EF0:      fcb $A                  ; DATA XREF: sub_DDDE:loc_DE37↓r
byte_8EF1:      fcb 5                   ; DATA XREF: sub_DDDE+6A↓r
byte_8EF2:      fcb $10                 ; DATA XREF: sub_DDDE+78↓r
byte_8EF3:      fcb $F                  ; DATA XREF: sub_DDDE+87↓r
byte_8EF4:      fcb $5E                 ; DATA XREF: sub_DDDE+A6↓r
byte_8EF5:      fcb $A                  ; DATA XREF: sub_DDDE+B2↓r
byte_8EF6:      fcb 2                   ; DATA XREF: sub_DDDE+B7↓o
                fcb $81, $9C, 0, 0
                fcb $E3, $9C
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
byte_8F19:      fcb 8                   ; DATA XREF: sub_DDDE+C8↓r
byte_8F1A:      fcb $2D                 ; DATA XREF: sub_DDDE+DD↓r
byte_8F1B:      fcb $B6                 ; DATA XREF: sub_DDDE+EB↓r
byte_8F1C:      fcb $FE                 ; DATA XREF: sub_E0ED+51C↓r
byte_8F1D:      fcb $F0                 ; DATA XREF: sub_E0ED+525↓r
byte_8F1E:      fcb 0                   ; DATA XREF: sub_E0ED:loc_E242↓r
byte_8F1F:      fcb $2E                 ; DATA XREF: sub_E0ED+2A5↓r
byte_8F20:      fcb $1A                 ; DATA XREF: sub_E0ED:loc_E636↓r
byte_8F21:      fcb 3                   ; DATA XREF: sub_E0ED+60C↓r
byte_8F22:      fcb $70                 ; DATA XREF: sub_E0ED:loc_E713↓r
byte_8F23:      fcb $AA                 ; DATA XREF: sub_E0ED+266↓r
                                        ; sub_E0ED+27F↓r ...
byte_8F24:      fcb $46                 ; DATA XREF: sub_E0ED:loc_E379↓r
byte_8F25:      fcb $4F                 ; DATA XREF: sub_E0ED+5B↓r
byte_8F26:      fcb 0                   ; DATA XREF: sub_E0ED+60↓r
byte_8F27:      fcb $3C                 ; DATA XREF: sub_E0ED+1A↓r
byte_8F28:      fcb $9C                 ; DATA XREF: sub_E0ED+24↓r
byte_8F29:      fcb 1                   ; DATA XREF: sub_E0ED+26B↓r
byte_8F2A:      fcb $A                  ; DATA XREF: sub_E0ED:loc_E68C↓r
byte_8F2B:      fcb $40                 ; DATA XREF: sub_E0ED+5B6↓r
byte_8F2C:      fcb 0                   ; DATA XREF: sub_E0ED+356↓r
byte_8F2D:      fcb 1                   ; DATA XREF: sub_E0ED+62B↓r
byte_8F2E:      fcb 1                   ; DATA XREF: sub_E0ED+5FC↓r
byte_8F2F:      fcb 1                   ; DATA XREF: sub_E0ED+632↓r
byte_8F30:      fcb 3                   ; DATA XREF: sub_E0ED+603↓r
byte_8F31:      fcb $4D                 ; DATA XREF: sub_E0ED+19C↓r
byte_8F32:      fcb 4                   ; DATA XREF: sub_E0ED+16F↓r
byte_8F33:      fcb 1                   ; DATA XREF: sub_E0ED+2D6↓r
byte_8F34:      fcb $20                 ; DATA XREF: sub_E0ED+2B3↓r
byte_8F35:      fcb $C                  ; DATA XREF: sub_E0ED+2E1↓r
byte_8F36:      fcb $8C                 ; DATA XREF: sub_E451+2C↓r
                                        ; sub_E0ED+436↓r
byte_8F37:      fcb 1                   ; DATA XREF: sub_E0ED+487↓r
byte_8F38:      fcb 6                   ; DATA XREF: sub_E0ED:loc_E519↓r
byte_8F39:      fcb 9                   ; DATA XREF: sub_E0ED+449↓r
byte_8F3A:      fcb $F2                 ; DATA XREF: sub_E0ED+44E↓r
byte_8F3B:      fcb 1                   ; DATA XREF: sub_E0ED:loc_E54D↓r
byte_8F3C:      fcb 2                   ; DATA XREF: sub_E0ED+453↓r
byte_8F3D:      fcb $20                 ; DATA XREF: sub_E0ED+463↓r
                                        ; sub_E0ED+468↓r
byte_8F3E:      fcb $D3                 ; DATA XREF: sub_E0ED+456↓r
                                        ; sub_E0ED+45B↓r
byte_8F3F:      fcb $F                  ; DATA XREF: sub_E0ED:loc_E50D↓r
byte_8F40:      fcb $F                  ; DATA XREF: sub_E0ED+40E↓r
byte_8F41:      fcb 4                   ; DATA XREF: sub_E0ED+4F4↓o
                fcb 0, 0, $FF, $DC
                fcb $40, $F7, $FF, $D4
                fcb $80, $EC, $FF, $EC
                fcb $C0, $E7
byte_8F50:      fcb 5                   ; DATA XREF: sub_E0ED+4DD↓o
                fcb 0, 0, 0, $50
                fcb $10, 5, 0, $15
                fcb $40, 9, 0, $2C
                fcb $80, $14, 0, 8
                fcb $FF, $18
                fcb $FF, $FF, $FF, $FF
byte_8F67:      fcb 4                   ; DATA XREF: sub_E0ED+53F↓o
                fcb $10, $18, 1, $40
                fcb $20, $2C, 0, $A0
                fcb $40, $40, 0, $16
                fcb $FD, $50
byte_8F76:      fcb 4                   ; DATA XREF: sub_E451+2↓o
                fcb $46, $1E, 0, 9
                fcb $64, $1F, 0, $2B
                fcb $82, $24, 0, $1A
                fcb $96, $26
byte_8F85:      fcb 4                   ; DATA XREF: sub_E451:loc_E467↓o
                fcb $20, $8D, $FF, $D8
                fcb $79, $7F, 0, 0
                fcb $A2, $7F, 0, $20
                fcb $E3, $87
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
byte_8F9C:      fcb 5                   ; DATA XREF: sub_E0ED+242↓o
                fcb $58, $7D, 0, $D
                fcb $6C, $7E, 0, $1A
                fcb $80, $80, 0, $1A
                fcb $94, $82, 0, $D
                fcb $BC, $84
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
                fcb $FF, $FF, $FF, $FF
byte_8FBB:      fcb 4                   ; DATA XREF: sub_E0ED+568↓o
                fcb $3C, $16, $FF, $8D
                fcb $50, $D, $FF, $F3
                fcb $78, $B, $FF, $F3
                fcb $8C, $A
byte_8FCA:      fcb 4                   ; DATA XREF: sub_E0ED+55D↓o
                fcb 0, $11, 0, $C
                fcb $16, $12, 1, $40
                fcb $1A, $17, 1, $80
                fcb $20, $20
byte_8FD9:      fcb 3                   ; DATA XREF: sub_E0ED:loc_E40E↓o
                fcb 0, 5, 0, $33
                fcb $A, 7, 0, $66
                fcb $14, $B
byte_8FE4:      fcb 4                   ; DATA XREF: sub_E0ED+50F↓o
                fcb $10, $E0, $FF, 0
                fcb $20, $D0, $FF, 0
                fcb $30, $C0, $FF, $EC
                fcb $FB, $B0
byte_8FF3:      fcb 3                   ; DATA XREF: sub_E0ED+63E↓o
                fcb $98, 1, 0, $30
                fcb $A8, 4, 0, 8
                fcb $E8, 6
byte_8FFE:      fcb 3                   ; DATA XREF: sub_E0ED+644↓o
                fcb $60, 0, 5, $D8
                fcb $80, $BB, 4, $40
                fcb $90, $FF
byte_9009:      fcb 2                   ; DATA XREF: sub_E0ED+611↓o
                fcb $47, 3, $FF, $F0
                fcb $68, 1
                fcb $FF, $FF, $FF, $FF
byte_9014:      fcb 3                   ; DATA XREF: sub_E0ED+617↓o
                fcb $6C, 0, 6, $66
                fcb $80, $80, 5, $4B
                fcb $98, $FF
byte_901F:      fcb 2                   ; DATA XREF: sub_E776+4↓o
                fcb $3F, $FD, $FD, $53
                fcb $64, $9A
byte_9026:      fcb 4                   ; DATA XREF: sub_E7DE:loc_E7E5↓r
byte_9027:      fcb $20                 ; DATA XREF: sub_E7DE+D↓o
                fcb $C0
word_9029:      fdb $1FF                ; DATA XREF: sub_E7DE+30↓r
word_902B:      fdb $2580               ; DATA XREF: sub_E7DE+5A↓r
byte_902D:      fcb 1                   ; DATA XREF: sub_E7DE+39↓r
                                        ; sub_E7DE+65↓r
byte_902E:      fcb 5                   ; DATA XREF: sub_E7DE+76↓r
byte_902F:      fcb $20                 ; DATA XREF: sub_E7DE+44↓r
byte_9030:      fcb 0                   ; DATA XREF: sub_AE82↓o
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
byte_9036:      fcb $34                 ; DATA XREF: sub_A35F+A7↓r
byte_9037:      fcb $33                 ; DATA XREF: sub_A2BC+3A↓r
byte_9038:      fcb $EB                 ; DATA XREF: sub_AF7A+B0↓r
byte_9039:      fcb $BB                 ; DATA XREF: sub_AF7A+38↓r
                                        ; sub_AF7A+53↓r ...
byte_903A:      fcb $7E                 ; DATA XREF: sub_AF7A+BE↓r
byte_903B:      fcb 0                   ; DATA XREF: sub_AF7A+77↓r
                                        ; sub_AF7A+92↓r ...
byte_903C:      fcb 0                   ; DATA XREF: sub_AF7A+CC↓r
byte_903D:      fcb $63                 ; DATA XREF: __RESET+4A3↓r
byte_903E:      fcb $E4                 ; DATA XREF: __RESET+4A8↓r
byte_903F:      fcb $CF                 ; DATA XREF: sub_A825+6↓r
byte_9040:      fcb $32                 ; DATA XREF: sub_A825+20↓r
byte_9041:      fcb $AA                 ; DATA XREF: sub_A825+28↓r
byte_9042:      fcb 3                   ; DATA XREF: sub_A49B+18↓r
byte_9043:      fcb $BA                 ; DATA XREF: sub_A49B+B↓r
byte_9044:      fcb $79                 ; DATA XREF: sub_A49B+6↓r
byte_9045:      fcb $1A                 ; DATA XREF: __RESET+332↓r
                                        ; sub_EA4A+3F↓r
byte_9046:      fcb $FD                 ; DATA XREF: __RESET+32D↓r
                                        ; sub_EA4A+3A↓r
byte_9047:      fcb $A8                 ; DATA XREF: __RESET:loc_9469↓r
                                        ; sub_EA4A+77↓r
byte_9048:      fcb $1A                 ; DATA XREF: __RESET+47A↓r
                                        ; sub_EACA+42↓r
byte_9049:      fcb $FD                 ; DATA XREF: __RESET+475↓r
                                        ; sub_EACA:loc_EB07↓r
byte_904A:      fcb $A8                 ; DATA XREF: __RESET:loc_95B1↓r
                                        ; sub_EACA+7A↓r
byte_904B:      fcb $10                 ; DATA XREF: sub_A867+10↓r
word_904C:      fdb $2EE0               ; DATA XREF: sub_A867+17↓r
byte_904E:      fcb $8E                 ; DATA XREF: sub_A867+35↓r
byte_904F:      fcb $7F                 ; DATA XREF: sub_A867+46↓r
byte_9050:      fcb 4                   ; DATA XREF: sub_E8C6+59↓r
byte_9051:      fcb 6                   ; DATA XREF: sub_A867:loc_A8BA↓r
byte_9052:      fcb $22                 ; DATA XREF: sub_9E01+29D↓r
                                        ; RESERVED:A0E0↓r ...
byte_9053:      fcb $14                 ; DATA XREF: sub_9E01+2A2↓r
                                        ; RESERVED:A0E5↓r ...
byte_9054:      fcb $2B                 ; DATA XREF: sub_BE83+206↓r
                                        ; sub_BE83:loc_C099↓r ...
byte_9055:      fcb $38                 ; DATA XREF: sub_A4F6+27↓r
byte_9056:      fcb $70                 ; DATA XREF: sub_A4F6:loc_A529↓r
byte_9057:      fcb $B1                 ; DATA XREF: sub_A4F6+C↓r
byte_9058:      fcb 8                   ; DATA XREF: sub_D14D+A↓r
                                        ; sub_EBC9+7B↓r ...
byte_9059:      fcb $F0                 ; DATA XREF: sub_D14D+F↓r
                                        ; sub_EBC9+80↓r ...
byte_905A:      fcb $D1                 ; DATA XREF: sub_EBC9+C1↓r
byte_905B:      fcb $20                 ; DATA XREF: sub_EBC9+6E↓r
byte_905C:      fcb $28                 ; DATA XREF: sub_EBC9+58↓r
byte_905D:      fcb $2F                 ; DATA XREF: sub_EBC9+2D↓r
                                        ; sub_EBC9+5F↓r
byte_905E:      fcb $24                 ; DATA XREF: sub_EBC9+67↓r
byte_905F:      fcb $FF                 ; DATA XREF: sub_EBC9+16↓r
                                        ; sub_EBC9+48↓r
byte_9060:      fcb $7D                 ; DATA XREF: sub_EBC9:loc_EC07↓r
byte_9061:      fcb $59                 ; DATA XREF: sub_EBC9+39↓r
byte_9062:      fcb $D1                 ; DATA XREF: sub_EBC9+34↓r
byte_9063:      fcb $AB                 ; DATA XREF: RESERVED:loc_A0C6↓r
byte_9064:      fcb 2                   ; DATA XREF: sub_A730+21↓r
                                        ; sub_A730+A1↓r ...
byte_9065:      fcb $FD                 ; DATA XREF: sub_A730+1C↓r
                                        ; sub_A730+80↓r ...
byte_9066:      fcb $66                 ; DATA XREF: __RESET+244↓r
                                        ; __RESET+258↓r ...
byte_9067:      fcb 2                   ; DATA XREF: sub_A730:loc_A76E↓r
                fcb 0
byte_9069:      fcb $CE                 ; DATA XREF: sub_A730+50↓r
byte_906A:      fcb $21                 ; DATA XREF: sub_A730+4D↓o
                fcb $10
byte_906C:      fcb 5                   ; DATA XREF: sub_B0E1:loc_B0FF↓o
                fcb $14, $34, 1, $DB
                fcb $1B, $41, 3, $E9
                fcb $3C, $C2, 1, $EF
                fcb $4B, $DF, 0, $55
                fcb $78, $EE
byte_907F:      fcb 0                   ; DATA XREF: sub_B0E1+24↓r
byte_9080:      fcb $23                 ; DATA XREF: sub_B0E1+17↓r
byte_9081:      fcb $20                 ; DATA XREF: sub_D6A4+DF↓r
byte_9082:      fcb $14                 ; DATA XREF: sub_B800:loc_B9E5↓r
byte_9083:      fcb $F                  ; DATA XREF: IC1I+3BC↓r
                                        ; IC1I+3C9↓r
byte_9084:      fcb 8                   ; DATA XREF: sub_DC08+155↓r
byte_9085:      fcb $D0                 ; DATA XREF: sub_DC08+10↓r
byte_9086:      fcb $80                 ; DATA XREF: sub_DC08+1C↓r
byte_9087:      fcb $1F                 ; DATA XREF: sub_DC08:loc_DC4B↓r
byte_9088:      fcb $20                 ; DATA XREF: sub_DC08+67↓r
byte_9089:      fcb 9                   ; DATA XREF: sub_DC08+62↓r
byte_908A:      fcb $AB                 ; DATA XREF: sub_DC08+5B↓r
byte_908B:      fcb $75                 ; DATA XREF: sub_DC08+56↓r
byte_908C:      fcb $41                 ; DATA XREF: sub_DC08+73↓r
byte_908D:      fcb $2A                 ; DATA XREF: sub_DC08+6E↓r
byte_908E:      fcb $40                 ; DATA XREF: sub_DC08+7A↓r
byte_908F:      fcb $72                 ; DATA XREF: sub_DC08+4F↓r
byte_9090:      fcb $2A                 ; DATA XREF: sub_DC08+F7↓r
byte_9091:      fcb $41                 ; DATA XREF: sub_DC08+FC↓r
byte_9092:      fcb 9                   ; DATA XREF: sub_DC08+EB↓r
byte_9093:      fcb $20                 ; DATA XREF: sub_DC08+F0↓r
byte_9094:      fcb $75                 ; DATA XREF: sub_DC08+DF↓r
byte_9095:      fcb $AB                 ; DATA XREF: sub_DC08+E4↓r
byte_9096:      fcb 6                   ; DATA XREF: sub_DC08+8C↓r
byte_9097:      fcb $15                 ; DATA XREF: sub_DC08+111↓r
byte_9098:      fcb $5B                 ; DATA XREF: sub_DC08:loc_DCD6↓r
byte_9099:      fcb $80                 ; DATA XREF: sub_DC08+138↓r
byte_909A:      fcb 8                   ; DATA XREF: sub_C1F5+39↓r
                                        ; sub_C8E3+39↓r
byte_909B:      fcb $B                  ; DATA XREF: sub_BE83+1A7↓r
                                        ; sub_C574+1A4↓r
word_909C:      fdb $1C9C               ; DATA XREF: sub_ED93+42↓r
word_909E:      fdb $2757               ; DATA XREF: sub_ED93+48↓r
word_90A0:      fdb $3938               ; DATA XREF: sub_ED93+4E↓r
byte_90A2:      fcb $B7                 ; DATA XREF: sub_AF7A+29↓r
                                        ; sub_AF7A+68↓r
byte_90A3:      fcb $49                 ; DATA XREF: sub_AF7A:loc_AFBE↓r
                                        ; sub_AF7A:loc_AFFD↓r
byte_90A4:      fcb $2D                 ; DATA XREF: sub_A0F1+18↓r
byte_90A5:      fcb $30                 ; DATA XREF: sub_A0F1+1F↓r
byte_90A6:      fcb $7D                 ; DATA XREF: sub_D6A4+6D↓r
