byte_0:         fcb 0                   ; DATA XREF: SCISS+17↓w
                                        ; CME+2B↓w ...
byte_1:         fcb 0                   ; DATA XREF: SCISS+1A↓w
byte_2:         fcb 0                   ; DATA XREF: __RESET+2B↓r
                                        ; __RESET:loc_9208↓w ...
byte_3:         fcb 0                   ; DATA XREF: __RESET+DE↓w
                                        ; __RESET+48C↓r ...
byte_4:         fcb 0                   ; DATA XREF: __RESET+EC↓w
                                        ; __RESET+2B8↓r ...
byte_5:         fcb 0                   ; DATA XREF: __RESET+EE↓w
                                        ; RESERVED:9BA3↓w ...
byte_6:         fcb 0                   ; DATA XREF: __RESET+E2↓w
                                        ; sub_D9D7:loc_D9EF↓r ...
byte_7:         fcb 0                   ; DATA XREF: __RESET+E7↓w
                                        ; sub_DDDE:loc_DE1F↓r ...
byte_8:         fcb 0                   ; DATA XREF: __RESET+D6↓w
                                        ; __RESET+2DA↓r ...
byte_9:         fcb 0                   ; DATA XREF: CME:loc_9126↓r
                                        ; __RESET+16↓r ...
                fcb 0
byte_B:         fcb 0                   ; DATA XREF: __RESET+4F5↓r
                                        ; sub_DB67+70↓r ...
                fcb 0
                fcb 0
byte_E:         fcb 0
                fcb 0
byte_10:        fcb 0
                fcb 0
                fcb 0
byte_13:        fcb 0
byte_14:        fcb 0
byte_15:        fcb 0
byte_16:        fcb 0
byte_17:        fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
byte_1C:        fcb 0                   ; DATA XREF: sub_AF7A:loc_AF9F↓r
                                        ; sub_BBCE:loc_BC55↓r ...
byte_1D:        fcb 0                   ; DATA XREF: __RESET+3B5↓r
                                        ; sub_BCC3+17↓r
byte_1E:        fcb 0                   ; DATA XREF: __RESET:loc_94B2↓r
                                        ; __RESET+3BD↓r ...
byte_1F:        fcb 0                   ; DATA XREF: __RESET+386↓r
                                        ; __RESET+3C5↓r ...
byte_20:        fcb 0                   ; DATA XREF: __RESET:loc_94BA↓r
                                        ; __RESET+3CD↓r ...
byte_21:        fcb 0                   ; DATA XREF: __RESET+34D↓r
                                        ; __RESET+364↓r ...
byte_22:        fcb 0                   ; DATA XREF: sub_BBCE+3↓r
                                        ; sub_BBCE+1C↓r ...
                fcb 0
                fcb 0
                fcb 0
byte_26:        fcb 0
                fcb 0
byte_28:        fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
byte_2F:        fcb 0
                fcb 0
                fcb 0
                fcb 0
byte_33:        fcb 0                   ; DATA XREF: sub_AF7A+64↓r
                                        ; sub_C2B7:loc_C33E↓r ...
byte_34:        fcb 0                   ; DATA XREF: __RESET+409↓r
                                        ; sub_C3AC+17↓r
byte_35:        fcb 0                   ; DATA XREF: __RESET+3D8↓r
                                        ; __RESET+411↓r ...
byte_36:        fcb 0                   ; DATA XREF: __RESET+3DA↓r
                                        ; __RESET+419↓r ...
byte_37:        fcb 0                   ; DATA XREF: __RESET:loc_950E↓r
                                        ; __RESET+421↓r ...
byte_38:        fcb 0                   ; DATA XREF: __RESET+429↓r
                                        ; sub_C3AC+C↓r ...
                fcb 0
                fcb 0
                fcb 0
byte_3C:        fcb 0
byte_3D:        fcb 0                   ; DATA XREF: sub_9BB0+2↓w
                                        ; sub_AE82:loc_AEDF↓r
                fcb 0
byte_3F:        fcb 0                   ; DATA XREF: sub_9BB0+4↓w
                fcb 0
byte_41:        fcb 0                   ; DATA XREF: sub_9BB0+6↓w
byte_42:        fcb 0                   ; DATA XREF: sub_B07D:loc_B099↓r
byte_43:        fcb 0                   ; DATA XREF: sub_9BB0+8↓w
                                        ; sub_AE82+15↓r ...
byte_44:        fcb 0                   ; DATA XREF: sub_AE82+11↓r
                                        ; sub_AE82+4F↓w ...
byte_45:        fcb 0                   ; DATA XREF: sub_9BB0+A↓w
                                        ; sub_AF7A-19D↓r ...
byte_46:        fcb 0                   ; DATA XREF: sub_AE82+55↓w
                                        ; sub_B07D+2B↓r ...
byte_47:        fcb 0                   ; DATA XREF: sub_9BB0+C↓w
                                        ; sub_B07D+20↓r ...
byte_48:        fcb 0                   ; DATA XREF: sub_96AC+83↓r
                                        ; sub_A4F6↓r ...
byte_49:        fcb 0                   ; DATA XREF: __RESET+2A4↓r
                                        ; RESERVED:9AE3↓r ...
byte_4A:        fcb 0                   ; DATA XREF: __RESET+2B2↓r
                                        ; sub_96AC+130↓r ...
byte_4B:        fcb 0                   ; DATA XREF: sub_96AC+EC↓r
                                        ; sub_96AC:loc_979D↓r ...
byte_4C:        fcb 0                   ; DATA XREF: __RESET+2AC↓r
                                        ; sub_A6C6+20↓r ...
byte_4D:        fcb 0                   ; DATA XREF: __RESET+2B5↓r
                                        ; sub_9981+A4↓r ...
byte_4E:        fcb 0                   ; DATA XREF: sub_96AC+1A↓r
                                        ; __RESET+80C↓r ...
byte_4F:        fcb 0                   ; DATA XREF: __RESET+108↓w
                                        ; __RESET+27D↓r ...
byte_50:        fcb 0                   ; DATA XREF: __RESET:loc_95DB↓r
                                        ; sub_9981+51↓r ...
byte_51:        fcb 0                   ; DATA XREF: __RESET+2F6↓r
                                        ; sub_96AC+86↓r ...
byte_52:        fcb 0                   ; DATA XREF: __RESET+4DE↓r
                                        ; __RESET:loc_989B↓r ...
byte_53:        fcb 0                   ; DATA XREF: sub_96AC+53↓r
                                        ; IRQ+79↓r ...
byte_54:        fcb 0                   ; DATA XREF: sub_B800+30B↓r
                                        ; sub_B800+310↓r ...
byte_55:        fcb 0                   ; DATA XREF: __RESET+317↓r
                                        ; sub_9E01:loc_9ECA↓r ...
byte_56:        fcb 0                   ; DATA XREF: __RESET+263↓r
                                        ; sub_96AC+3A↓r ...
byte_57:        fcb 0                   ; DATA XREF: sub_BBCE+97↓r
                                        ; sub_BBCE:loc_BC75↓r ...
byte_58:        fcb 0                   ; DATA XREF: sub_C2B7+97↓r
                                        ; sub_C2B7:loc_C35E↓r ...
byte_59:        fcb 0                   ; DATA XREF: sub_A35F:loc_A3A0↓r
                                        ; sub_A35F:loc_A455↓r ...
byte_5A:        fcb 0                   ; DATA XREF: sub_A35F+30↓r
                                        ; sub_A35F+34↓r ...
byte_5B:        fcb 0                   ; DATA XREF: RESERVED:9D17↓r
                                        ; RESERVED:9D4A↓r ...
byte_5C:        fcb 0                   ; DATA XREF: __RESET+2F9↓r
                                        ; sub_CA13:loc_CA7D↓r ...
byte_5D:        fcb 0                   ; DATA XREF: sub_96AC+89↓r
                                        ; __RESET+711↓r ...
byte_5E:        fcb 0                   ; DATA XREF: sub_A12C+21↓r
                                        ; sub_A12C+2A↓r ...
byte_5F:        fcb 0                   ; DATA XREF: __RESET+2BE↓r
                                        ; RESERVED:B42A↓r ...
byte_60:        fcb 0                   ; DATA XREF: sub_E0ED+9F↓r
                                        ; sub_E0ED+13B↓r ...
byte_61:        fcb 0                   ; DATA XREF: __RESET+2C3↓w
                                        ; sub_E0ED↓r ...
byte_62:        fcb 0                   ; DATA XREF: sub_A35F+A↓r
                                        ; sub_A49B:loc_A4D9↓r ...
byte_63:        fcb 0                   ; DATA XREF: sub_F644+45↓r
                                        ; ROM_EPROM:F6C6↓r ...
byte_64:        fcb 0                   ; DATA XREF: sub_96AC+1D↓r
                                        ; sub_96AC+22↓w ...
byte_65:        fcb 0                   ; DATA XREF: sub_96AC+12↓w
                                        ; sub_96AC+60↓r ...
byte_66:        fcb 0                   ; DATA XREF: sub_B800:loc_BB73↓w
                                        ; IC1I:loc_FA10↓r ...
byte_67:        fcb 0                   ; DATA XREF: sub_B10D:loc_B13D↓w
                                        ; sub_B800+35C↓r
byte_68:        fcb 0                   ; DATA XREF: __RESET+2D4↓w
                                        ; sub_B800+31A↓r ...
byte_69:        fcb 0                   ; DATA XREF: IC1I+1B3↓w
                                        ; IC1I+1BD↓r ...
byte_6A:        fcb 0                   ; DATA XREF: RESERVED:loc_A0D7↓r
                                        ; IC1I+1B5↓w ...
byte_6B:        fcb 0                   ; DATA XREF: __RESET+7C9↓r
                                        ; RESERVED:loc_9B3A↓r ...
byte_6C:        fcb 0
byte_6D:        fcb 0                   ; DATA XREF: __RESET+22B↓w
                                        ; __RESET:loc_942A↓r ...
byte_6E:        fcb 0                   ; DATA XREF: __RESET+48A↓w
                                        ; RESERVED:loc_A0BF↓r ...
byte_6F:        fcb 0                   ; DATA XREF: __RESET+471↓w
                                        ; __RESET+47F↓r ...
byte_70:        fcb 0                   ; DATA XREF: sub_96AC+73↓w
                                        ; sub_9E01:loc_A09A↓r ...
byte_71:        fcb 0                   ; DATA XREF: sub_96AC+B2↓w
                                        ; RESERVED:loc_A0DC↓r ...
byte_72:        fcb 0                   ; DATA XREF: __RESET+329↓w
                                        ; __RESET+337↓r ...
byte_73:        fcb 0                   ; DATA XREF: __RESET+209↓w
                                        ; __RESET:loc_9590↓r ...
byte_74:        fcb 0                   ; DATA XREF: __RESET+1DA↓w
                                        ; __RESET:loc_9448↓r ...
byte_75:        fcb 0                   ; DATA XREF: __RESET+223↓w
                                        ; __RESET+303↓r ...
byte_76:        fcb 0                   ; DATA XREF: __RESET+21E↓w
                                        ; sub_96AC+6E↓w ...
byte_77:        fcb 0                   ; DATA XREF: sub_A730+93↓r
                                        ; sub_CA82+35↓r ...
byte_78:        fcb 0                   ; DATA XREF: RESERVED:B3D9↓r
                                        ; sub_E0ED+F↓r ...
byte_79:        fcb 0
byte_7A:        fcb 0                   ; DATA XREF: sub_9E01:loc_A096↓r
                                        ; sub_A4F6+38↓r ...
byte_7B:        fcb 0                   ; DATA XREF: sub_9E01:loc_A060↓r
                                        ; sub_A35F:loc_A38B↓r ...
byte_7C:        fcb 0                   ; DATA XREF: __RESET+2AF↓r
                                        ; sub_D4F8:loc_D515↓r ...
byte_7D:        fcb 0                   ; DATA XREF: sub_A7FD+C↓r
                                        ; sub_A867+A↓r ...
byte_7E:        fcb 0                   ; DATA XREF: sub_B10D:loc_B123↓w
                                        ; sub_F1F4↓r
byte_7F:        fcb 0                   ; DATA XREF: __RESET:loc_92BA↓w
                                        ; RESERVED:B3C0↓r ...
byte_80:        fcb 0                   ; DATA XREF: RESERVED:loc_9B42↓r
                                        ; sub_A730+35↓r ...
byte_81:        fcb 0
byte_82:        fcb 0                   ; DATA XREF: RESERVED:loc_9B3E↓r
                                        ; sub_D14D+1C8↓w ...
                fcb 0
byte_84:        fcb 0                   ; DATA XREF: RESERVED:9B36↓r
                                        ; sub_D14D+1CA↓w ...
                fcb 0
byte_86:        fcb 0                   ; DATA XREF: sub_C97D:loc_CA10↓w
                                        ; sub_D14D:loc_D340↓r ...
byte_87:        fcb 0
byte_88:        fcb 0                   ; DATA XREF: sub_BE83↓r
                                        ; sub_CB52+48↓r ...
                fcb 0
byte_8A:        fcb 0                   ; DATA XREF: sub_C574↓r
                                        ; sub_CB52+56↓r ...
                fcb 0
byte_8C:        fcb 0                   ; DATA XREF: sub_D0F1+56↓w
byte_8D:        fcb 0
byte_8E:        fcb 0                   ; DATA XREF: sub_D0F1:loc_D14A↓w
                fcb 0
byte_90:        fcb 0                   ; DATA XREF: sub_BE83+2C↓r
                                        ; sub_BE83+33↓w ...
byte_91:        fcb 0                   ; DATA XREF: sub_C574+2C↓r
                                        ; sub_C574+33↓w ...
byte_92:        fcb 0                   ; DATA XREF: sub_BE83+59↓r
                                        ; sub_BE83+64↓w ...
byte_93:        fcb 0                   ; DATA XREF: sub_C574+59↓r
                                        ; sub_C574+64↓w ...
byte_94:        fcb 0                   ; DATA XREF: sub_BE83+90↓w
                                        ; sub_BE83+13F↓r ...
byte_95:        fcb 0                   ; DATA XREF: sub_C574+8D↓w
                                        ; sub_C574+13C↓r ...
byte_96:        fcb 0                   ; DATA XREF: sub_BE83+7E↓r
byte_97:        fcb 0                   ; DATA XREF: sub_A0F1+33↓w
byte_98:        fcb 0                   ; DATA XREF: sub_BD64+F↓r
                                        ; sub_BD64:loc_BD78↓w ...
byte_99:        fcb 0                   ; DATA XREF: sub_C455+F↓r
                                        ; sub_C455:loc_C469↓w ...
byte_9A:        fcb 0                   ; DATA XREF: sub_BBCE+BD↓r
                                        ; sub_BBCE+C2↓w ...
byte_9B:        fcb 0                   ; DATA XREF: sub_C2B7+BD↓r
                                        ; sub_C2B7+C2↓w ...
byte_9C:        fcb 0                   ; DATA XREF: RESERVED:9B8C↓w
                                        ; sub_BBCE+B6↓w ...
byte_9D:        fcb 0                   ; DATA XREF: RESERVED:9B8E↓w
                                        ; sub_C2B7+B6↓w ...
byte_9E:        fcb 0                   ; DATA XREF: sub_BBCE+80↓r
                                        ; sub_BC93+C↓r ...
byte_9F:        fcb 0                   ; DATA XREF: sub_C2B7+80↓r
                                        ; sub_C37C+C↓r ...
byte_A0:        fcb 0                   ; DATA XREF: sub_C0E4+9↓r
                                        ; sub_C0E4+18↓w ...
byte_A1:        fcb 0                   ; DATA XREF: sub_BE83+145↓w
                                        ; sub_BE83+18A↓w ...
byte_A2:        fcb 0                   ; DATA XREF: sub_C574+142↓w
                                        ; sub_C574+187↓w ...
byte_A3:        fcb 0                   ; DATA XREF: sub_BE83+154↓r
                                        ; sub_BE83+15F↓w ...
byte_A4:        fcb 0                   ; DATA XREF: sub_C574+151↓r
                                        ; sub_C574+15C↓w ...
byte_A5:        fcb 0                   ; DATA XREF: sub_CD20↓r
                                        ; sub_CD20+5↓w
byte_A6:        fcb 0                   ; DATA XREF: sub_CD20:loc_CD27↓r
                                        ; sub_CD20+C↓w ...
byte_A7:        fcb 0                   ; DATA XREF: sub_CD20:loc_CD2E↓r
                                        ; sub_CD20+13↓w ...
byte_A8:        fcb 0                   ; DATA XREF: sub_CD20:loc_CD56↓r
                                        ; sub_CD20+3B↓w
byte_A9:        fcb 0                   ; DATA XREF: sub_CB52+81↓w
                                        ; sub_CB52:loc_CBD7↓r ...
byte_AA:        fcb 0                   ; DATA XREF: sub_B554+86↓r
                                        ; sub_D14D+1DC↓r ...
byte_AB:        fcb 0                   ; DATA XREF: sub_CDF1+8↓w
                                        ; sub_D0F1+5↓r
byte_AC:        fcb 0                   ; DATA XREF: sub_CC8F+59↓w
                                        ; sub_CC8F:loc_CCEF↓w ...
byte_AD:        fcb 0                   ; DATA XREF: sub_BE83+110↓r
                                        ; sub_C164↓r ...
byte_AE:        fcb 0                   ; DATA XREF: sub_C574+10D↓r
                                        ; sub_C852↓r ...
byte_AF:        fcb 0                   ; DATA XREF: sub_BE83+112↓r
                                        ; sub_C164+23↓r ...
byte_B0:        fcb 0                   ; DATA XREF: sub_BE83+8E↓w
                                        ; sub_BE83+143↓w ...
byte_B1:        fcb 0                   ; DATA XREF: sub_C574+8B↓w
                                        ; sub_C574+140↓w ...
byte_B2:        fcb 0                   ; DATA XREF: sub_BD64+DD↓w
                                        ; sub_BE83+DD↓r ...
byte_B3:        fcb 0                   ; DATA XREF: sub_BD64:loc_BE6B↓r
                                        ; sub_BD64+109↓w ...
byte_B4:        fcb 0                   ; DATA XREF: __RESET+34A↓r
                                        ; __RESET:loc_948F↓r ...
byte_B5:        fcb 0                   ; DATA XREF: sub_BE83+10E↓r
                                        ; sub_C164+B↓r ...
byte_B6:        fcb 0                   ; DATA XREF: sub_C574+10B↓r
                                        ; sub_C852+B↓r ...
byte_B7:        fcb 0                   ; DATA XREF: ROM_EPROM:loc_D016↓w
                                        ; sub_D0F1+3C↓r
byte_B8:        fcb 0                   ; DATA XREF: sub_CFA0:loc_CFBB↓w
                                        ; sub_D14D+AC↓r
byte_B9:        fcb 0                   ; DATA XREF: sub_CFA0+25↓w
                                        ; sub_D14D+CC↓r
byte_BA:        fcb 0                   ; DATA XREF: sub_CC29+7↓r
                                        ; sub_D381:loc_D3A2↓w
byte_BB:        fcb 0                   ; DATA XREF: sub_B800+32A↓r
                                        ; sub_CC8F+10↓r ...
                fcb 0
byte_BD:        fcb 0                   ; DATA XREF: __RESET+2FF↓w
                                        ; sub_CF6B+3↓r ...
                fcb 0
byte_BF:        fcb 0                   ; DATA XREF: __RESET+301↓w
                                        ; sub_CEF4+24↓w ...
                fcb 0
byte_C1:        fcb 0                   ; DATA XREF: __RESET+22E↓w
                                        ; sub_B800+47↓r ...
                fcb 0
byte_C3:        fcb 0                   ; DATA XREF: sub_CE79+49↓w
                                        ; sub_CE79+68↓w
byte_C4:        fcb 0                   ; DATA XREF: sub_CD65+4B↓w
byte_C5:        fcb 0                   ; DATA XREF: sub_CD65+55↓w
byte_C6:        fcb 0                   ; DATA XREF: __RESET+305↓w
                                        ; sub_CF6B+19↓r ...
                fcb 0
byte_C8:        fcb 0                   ; DATA XREF: __RESET+307↓w
                                        ; sub_CEF4+2C↓w ...
                fcb 0
byte_CA:        fcb 0                   ; DATA XREF: sub_CE79:loc_CECC↓w
                                        ; sub_CE79+5E↓w ...
byte_CB:        fcb 0                   ; DATA XREF: sub_D019+6↓r
                                        ; sub_D019:loc_D04C↓w ...
byte_CC:        fcb 0
byte_CD:        fcb 0                   ; DATA XREF: sub_CD65+37↓w
                                        ; sub_D019:loc_D06E↓r
byte_CE:        fcb 0                   ; DATA XREF: sub_D019+58↓w
                                        ; sub_D14D+137↓r
                fcb 0
byte_D0:        fcb 0                   ; DATA XREF: sub_CD65+41↓w
                                        ; sub_D074:loc_D09A↓r
byte_D1:        fcb 0                   ; DATA XREF: sub_BE83+10A↓r
                                        ; sub_C164+60↓r ...
                fcb 0
byte_D3:        fcb 0                   ; DATA XREF: sub_CD65+5F↓w
                                        ; sub_D074:loc_D0CC↓r
byte_D4:        fcb 0                   ; DATA XREF: sub_BE83+10C↓r
                                        ; sub_C574+109↓r ...
                fcb 0
byte_D6:        fcb 0                   ; DATA XREF: sub_CDF1+27↓w
                                        ; sub_D0F1+4D↓r
                fcb 0
byte_D8:        fcb 0                   ; DATA XREF: sub_C97D+87↓r
                                        ; sub_CA82+A3↓r ...
byte_D9:        fcb 0                   ; DATA XREF: sub_C97D+4E↓r
                                        ; IC1I+172↓w ...
byte_DA:        fcb 0                   ; DATA XREF: sub_CC29↓r
                                        ; sub_D381+71↓w ...
                fcb 0
byte_DC:        fcb 0                   ; DATA XREF: sub_CD65+19↓w
                                        ; RESERVED:CFD8↓r ...
byte_DD:        fcb 0                   ; DATA XREF: sub_CE39:loc_CE76↓w
                                        ; RESERVED:CFEB↓r
byte_DE:        fcb 0                   ; DATA XREF: sub_CE39:loc_CE51↓r
                                        ; sub_CE39+22↓r ...
byte_DF:        fcb 0                   ; DATA XREF: sub_CD65+23↓w
                                        ; RESERVED:loc_CFC8↓r
byte_E0:        fcb 0                   ; DATA XREF: sub_CD14+4↓r
                                        ; sub_CD14+9↓w ...
byte_E1:        fcb 0                   ; DATA XREF: sub_CD20+1D↓r
                                        ; sub_CD20+22↓w ...
byte_E2:        fcb 0                   ; DATA XREF: sub_D14D:loc_D273↓w
                                        ; sub_D14D+16A↓r ...
                fcb 0
byte_E4:        fcb 0                   ; DATA XREF: sub_D14D+132↓w
                                        ; sub_D14D+158↓r
byte_E5:        fcb 0                   ; DATA XREF: sub_CA82+A↓r
                                        ; sub_CA82+C↓w
byte_E6:        fcb 0                   ; DATA XREF: sub_CA82+6F↓r
                                        ; sub_F126+3C↓w
byte_E7:        fcb 0                   ; DATA XREF: sub_CD65+69↓w
byte_E8:        fcb 0                   ; DATA XREF: sub_CD65+73↓w
                                        ; sub_D019:loc_D068↓r ...
byte_E9:        fcb 0                   ; DATA XREF: sub_CE79+39↓w
                                        ; sub_CE79+78↓w ...
byte_EA:        fcb 0                   ; DATA XREF: sub_BE83+E↓w
                                        ; sub_BE83:loc_BE98↓r ...
byte_EB:        fcb 0                   ; DATA XREF: sub_C574+E↓w
                                        ; sub_C574:loc_C589↓r ...
byte_EC:        fcb 0                   ; DATA XREF: sub_CD65+2D↓w
                                        ; sub_D0D2+9↓r
byte_ED:        fcb 0                   ; DATA XREF: sub_D0D2:loc_D0EE↓w
                                        ; sub_D14D+13B↓r
                fcb 0
byte_EF:        fcb 0                   ; DATA XREF: __RESET:loc_95FC↓w
                                        ; sub_9E01:loc_9E8D↓r ...
byte_F0:        fcb 0                   ; DATA XREF: __RESET:loc_93CD↓w
                                        ; __RESET+52F↓r ...
byte_F1:        fcb 0                   ; DATA XREF: __RESET+65↓w
                                        ; __RESET+119↓w ...
byte_F2:        fcb 0                   ; DATA XREF: __RESET+260↓r
                                        ; sub_9BB0+E↓w ...
byte_F3:        fcb 0                   ; DATA XREF: sub_A2BC:loc_A32E↓r
                                        ; sub_A2BC+7B↓r ...
byte_F4:        fcb 0                   ; DATA XREF: sub_9BB0+10↓w
                                        ; sub_AF7A+C3↓r ...
byte_F5:        fcb 0                   ; DATA XREF: sub_A35F:loc_A441↓r
                                        ; sub_A35F+EB↓r ...
byte_F6:        fcb 0                   ; DATA XREF: sub_9BB0+12↓w
                                        ; sub_A605+3D↓r ...
byte_F7:        fcb 0                   ; DATA XREF: __RESET+274↓w
                                        ; sub_9981+39↓w ...
byte_F8:        fcb 0                   ; DATA XREF: sub_9981:loc_99D5↓w
                                        ; sub_9981+86↓r ...
byte_F9:        fcb 0                   ; DATA XREF: sub_9981+57↓w
                                        ; sub_9981:loc_99FB↓w ...
byte_FA:        fcb 0                   ; DATA XREF: sub_9981+6↓r
                                        ; sub_9981+2A↓r ...
byte_FB:        fcb 0                   ; DATA XREF: sub_B14E+D4↓r
                                        ; sub_B22F+6C↓r ...
byte_FC:        fcb 0                   ; DATA XREF: sub_B14E+D7↓r
                                        ; sub_B22F+94↓r ...
byte_FD:        fcb 0                   ; DATA XREF: sub_B22F+4F↓r
                                        ; sub_B22F+56↓w
byte_FE:        fcb 0                   ; DATA XREF: sub_B14E+DB↓r
                                        ; sub_B22F+6↓r ...
byte_FF:        fcb 0                   ; DATA XREF: sub_E0ED+8↓w
                                        ; sub_E0ED+77↓w ...
byte_100:       fcb 0                   ; DATA XREF: sub_96AC+B7↓w
byte_101:       fcb 0                   ; DATA XREF: sub_B800+20B↓w
                                        ; sub_B800:loc_BA10↓r
byte_102:       fcb 0                   ; DATA XREF: sub_B800+86↓w
                                        ; sub_B800+96↓w ...
byte_103:       fcb 0                   ; DATA XREF: IC1I+2AF↓r
                                        ; IC1I:loc_FAFE↓w
byte_104:       fcb 0                   ; DATA XREF: sub_B800+2D5↓w
                                        ; IC1I:loc_FB6B↓w ...
byte_105:       fcb 0                   ; DATA XREF: sub_B800+284↓r
                                        ; sub_B800+2D2↓w ...
byte_106:       fcb 0                   ; DATA XREF: sub_B800+28D↓r
                                        ; sub_B800:loc_BAE6↓w
byte_107:       fcb 0                   ; DATA XREF: sub_B800+2B9↓w
                                        ; sub_B800+2D8↓r
byte_108:       fcb 0                   ; DATA XREF: __RESET+2CE↓w
                                        ; sub_96AC+A0↓o ...
byte_109:       fcb 0                   ; DATA XREF: sub_E0ED+3DB↓r
                                        ; sub_E0ED+3E6↓r ...
byte_10A:       fcb 0                   ; DATA XREF: __RESET+2D1↓w
                                        ; sub_E0ED:loc_E4BE↓o ...
                fcb 0
byte_10C:       fcb 0                   ; DATA XREF: IC2I+458B↓r
                                        ; IC2I+4593↓r ...
                fcb 0
byte_10E:       fcb 0                   ; DATA XREF: IC1I+2C7↓r
                                        ; IC1I:loc_FB0C↓w ...
byte_10F:       fcb 0                   ; DATA XREF: sub_B800+337↓r
                                        ; sub_B800:loc_BB54↓w ...
byte_110:       fcb 0                   ; DATA XREF: sub_D6A4+4↓r
                                        ; sub_D6A4+A↓w ...
byte_111:       fcb 0                   ; DATA XREF: sub_9E01:loc_9EB0↓w
                                        ; sub_D6A4:loc_D756↓r ...
byte_112:       fcb 0                   ; DATA XREF: sub_B800+184↓r
                                        ; sub_D6A4+110↓r ...
byte_113:       fcb 0                   ; DATA XREF: sub_D9D7:loc_DA8D↓w
                                        ; sub_EBC9+140↓w ...
byte_114:       fcb 0                   ; DATA XREF: sub_D92D+14↓r
                                        ; sub_D92D+58↓w ...
byte_115:       fcb 0                   ; DATA XREF: __RESET+2CB↓w
                                        ; sub_96AC+2C↓o ...
byte_116:       fcb 0                   ; DATA XREF: sub_96AC+7E↓r
                                        ; RESERVED:9B56↓r ...
word_117:       fdb 0                   ; DATA XREF: __RESET+2C8↓w
                                        ; sub_A703+15↓r ...
word_119:       fdb 0                   ; DATA XREF: __RESET+278↓w
                                        ; sub_AF7A-200↓r ...
byte_11B:       fcb 0                   ; DATA XREF: sub_E0ED+90↓w
                                        ; sub_E0ED+1E2↓w ...
byte_11C:       fcb 0                   ; DATA XREF: sub_E0ED+87↓w
                                        ; sub_E0ED+A2↓r ...
byte_11D:       fcb 0                   ; DATA XREF: sub_E0ED+96↓w
                                        ; sub_E0ED+5BC↓r ...
byte_11E:       fcb 0                   ; DATA XREF: sub_E0ED+261↓r
                                        ; sub_E0ED+26E↓r ...
byte_11F:       fcb 0                   ; DATA XREF: sub_E0ED+4AF↓w
                                        ; sub_E0ED+4B6↓r ...
byte_120:       fcb 0                   ; DATA XREF: sub_E0ED+93↓w
                                        ; sub_E0ED+1BA↓w ...
byte_121:       fcb 0                   ; DATA XREF: sub_E0ED+8A↓w
                                        ; sub_E0ED+13F↓w ...
byte_122:       fcb 0                   ; DATA XREF: sub_E0ED+8D↓w
                                        ; sub_E0ED+142↓w ...
byte_123:       fcb 0                   ; DATA XREF: sub_B800:loc_B819↓r
                                        ; sub_CFA0+8↓r ...
byte_124:       fcb 0                   ; DATA XREF: RESERVED:loc_9CD6↓r
                                        ; sub_B054↓r ...
byte_125:       fcb 0                   ; DATA XREF: RESERVED:9CDD↓r
                                        ; sub_B054+16↓w
byte_126:       fcb 0                   ; DATA XREF: sub_B054+6↓w
                                        ; sub_F351+41↓w
byte_127:       fcb 0                   ; DATA XREF: sub_B054+11↓w
byte_128:       fcb 0                   ; DATA XREF: RESERVED:loc_9C95↓r
                                        ; RESERVED:9C9A↓w ...
byte_129:       fcb 0                   ; DATA XREF: sub_E8C6+18↓w
                                        ; sub_E8C6+38↓r ...
byte_12A:       fcb 0                   ; DATA XREF: sub_B22F+1C↓r
                                        ; sub_B22F+20↓w ...
byte_12B:       fcb 0                   ; DATA XREF: IC1I+36↓r
                                        ; IC1I:loc_F884↓w ...
byte_12C:       fcb 0                   ; DATA XREF: sub_E7DE+16↓r
                                        ; sub_E7DE+4C↓w
                fcb 0
byte_12E:       fcb 0                   ; DATA XREF: sub_E7DE↓w
                                        ; sub_E7DE+A↓w
                fcb 0
                fcb 0
byte_131:       fcb 0                   ; DATA XREF: sub_E7DE+3C↓w
                                        ; sub_E7DE+60↓w ...
byte_132:       fcb 0                   ; DATA XREF: sub_E7DE+41↓w
                                        ; sub_E7DE+6D↓r ...
byte_133:       fcb 0                   ; DATA XREF: sub_E7DE+47↓w
                                        ; sub_E7DE+53↓w
byte_134:       fcb 0                   ; DATA XREF: sub_DDDE+33↓r
                                        ; sub_DDDE+39↓w ...
byte_135:       fcb 0                   ; DATA XREF: sub_DDDE+61↓w
                                        ; sub_DDDE+6F↓r ...
byte_136:       fcb 0                   ; DATA XREF: sub_DDDE+53↓r
                                        ; sub_DDDE+8F↓w ...
byte_137:       fcb 0                   ; DATA XREF: sub_DDDE:loc_DEB2↓r
                                        ; sub_DDDE+DA↓w ...
byte_138:       fcb 0                   ; DATA XREF: sub_DDDE:loc_DEC0↓r
                                        ; sub_DDDE+E8↓w ...
byte_139:       fcb 0                   ; DATA XREF: sub_DEE3+DD↓w
                                        ; sub_DFC9+A↓r ...
byte_13A:       fcb 0                   ; DATA XREF: __RESET+340↓w
                                        ; sub_C97D+18↓r ...
byte_13B:       fcb 0                   ; DATA XREF: sub_DDDE+22↓r
                                        ; sub_DDDE+50↓r ...
byte_13C:       fcb 0                   ; DATA XREF: __RESET+2D7↓w
                                        ; sub_E9A1+29↓r ...
byte_13D:       fcb 0                   ; DATA XREF: sub_96AC+8↓w
                                        ; sub_96AC+C6↓r ...
byte_13E:       fcb 0                   ; DATA XREF: sub_B800:loc_B844↓r
                                        ; sub_B800+5A↓r ...
byte_13F:       fcb 0                   ; DATA XREF: sub_CDF1+31↓w
                                        ; sub_D019+22↓r
byte_140:       fcb 0                   ; DATA XREF: sub_CD65+7D↓w
                                        ; sub_D074:loc_D0C4↓r ...
byte_141:       fcb 0                   ; DATA XREF: sub_CD65+88↓w
                                        ; sub_D074+1E↓r ...
                fcb 0
                fcb 0
                fcb 0
                fcb 0
word_146:       fdb 0                   ; DATA XREF: IC1I+FE↓w
                                        ; IC1I:loc_F966↓r ...
byte_148:       fcb 0                   ; DATA XREF: IC2I+451D↓w
                                        ; IC2I+4555↓r ...
byte_149:       fcb 0                   ; DATA XREF: IC2I+451A↓w
                                        ; IC2I+4540↓r ...
word_14A:       fdb 0                   ; DATA XREF: sub_CA82+2D61↓r
                                        ; sub_CA82+2D87↓w
word_14C:       fdb 0                   ; DATA XREF: __RESET+568↓w
                                        ; __RESET+82D↓r ...
word_14E:       fdb 0                   ; DATA XREF: sub_EFEC+8↓r
                                        ; sub_EFEC+13↓w
byte_150:       fcb 0                   ; DATA XREF: sub_CDF1+1C↓w
                                        ; IC1I:loc_F936↓r
byte_151:       fcb 0                   ; DATA XREF: OC1I+38↓w
                                        ; sub_DB67↓r ...
byte_152:       fcb 0                   ; DATA XREF: sub_C574+88↓w
                                        ; sub_C574+16F↓w ...
byte_153:       fcb 0                   ; DATA XREF: __RESET+2A9↓w
                                        ; sub_EBC9+101↓r ...
byte_154:       fcb 0                   ; DATA XREF: __RESET+15A↓w
                                        ; __RESET+15D↓r ...
byte_155:       fcb 0                   ; DATA XREF: __RESET+230↓w
                                        ; sub_D14D+3C↓r ...
byte_156:       fcb 0                   ; DATA XREF: __RESET+136↓w
                                        ; __RESET+160↓r ...
byte_157:       fcb 0                   ; DATA XREF: sub_96AC:loc_973F↓w
word_158:       fdb 0                   ; DATA XREF: RESERVED:B393↓r
                                        ; RESERVED:B399↓w ...
byte_15A:       fcb 0                   ; DATA XREF: RESERVED:B396↓r
                                        ; RESERVED:B39C↓w ...
byte_15B:       fcb 0                   ; DATA XREF: RESERVED:B3A7↓r
                                        ; RESERVED:B3AB↓w ...
byte_15C:       fcb 0                   ; DATA XREF: sub_B800+1DA↓w
                                        ; sub_B800+1E2↓w ...
byte_15D:       fcb 0                   ; DATA XREF: sub_B800+1C9↓w
                                        ; sub_B800:loc_B9D7↓w ...
byte_15E:       fcb 0                   ; DATA XREF: sub_D457+13↓r
                                        ; sub_D457+24↓w ...
byte_15F:       fcb 0                   ; DATA XREF: sub_D457+7F↓w
                                        ; sub_D457:loc_D4D9↓r ...
byte_160:       fcb 0                   ; DATA XREF: sub_D4F8+C↓r
                                        ; sub_D4F8+12↓w ...
byte_161:       fcb 0                   ; DATA XREF: RESERVED:9A53↓w
                                        ; sub_A35F+116↓w ...
byte_162:       fcb 0                   ; DATA XREF: RESERVED:9A4E↓w
                                        ; sub_A35F+119↓w ...
byte_163:       fcb 0                   ; DATA XREF: sub_A825+25↓r
                                        ; sub_A825+32↓w ...
byte_164:       fcb 0                   ; DATA XREF: sub_B054:loc_B06D↓r
                                        ; sub_B054:loc_B079↓w ...
byte_165:       fcb 0                   ; DATA XREF: sub_A2BC+2F↓w
                                        ; sub_BD64+CE↓r ...
byte_166:       fcb 0                   ; DATA XREF: sub_A2BC+37↓r
                                        ; sub_A2BC+9C↓w ...
                fcb 0
byte_168:       fcb 0                   ; DATA XREF: sub_96AC+4B↓r
                                        ; sub_96AC+50↓w ...
byte_169:       fcb 0                   ; DATA XREF: sub_DC08+91↓r
                                        ; sub_DC08:loc_DCAF↓r ...
byte_16A:       fcb 0                   ; DATA XREF: sub_DC08+48↓r
                                        ; sub_DC08+86↓w ...
byte_16B:       fcb 0                   ; DATA XREF: sub_DC08+C9↓w
                                        ; sub_DC08+103↓r ...
byte_16C:       fcb 0                   ; DATA XREF: sub_DC08+10E↓w
byte_16D:       fcb 0                   ; DATA XREF: sub_DC08:loc_DD1E↓r
                                        ; sub_DC08+11B↓w ...
byte_16E:       fcb 0                   ; DATA XREF: __RESET+236↓w
                                        ; sub_A12C+77↓r ...
byte_16F:       fcb 0                   ; DATA XREF: __RESET+239↓w
                                        ; sub_A12C:loc_A1AB↓r ...
byte_170:       fcb 0                   ; DATA XREF: sub_E8C6+49↓r
                                        ; sub_E8C6+51↓w ...
byte_171:       fcb 0                   ; DATA XREF: sub_A867+28↓r
                                        ; sub_A867+2E↓w ...
byte_172:       fcb 0                   ; DATA XREF: sub_A605+23↓r
                                        ; sub_A605+2D↓w ...
byte_173:       fcb 0                   ; DATA XREF: sub_A544+23↓r
                                        ; sub_A544+2D↓w ...
byte_174:       fcb 0                   ; DATA XREF: sub_CE79+16↓w
                                        ; sub_CE79+1C↓r ...
byte_175:       fcb 0                   ; DATA XREF: sub_CE79+3E↓w
                                        ; sub_CE79+6D↓w ...
byte_176:       fcb 0                   ; DATA XREF: sub_DB67+55↓r
                                        ; sub_DB67+5D↓w ...
byte_177:       fcb 0                   ; DATA XREF: __RESET+811↓r
                                        ; sub_A2BC+49↓r ...
byte_178:       fcb 0                   ; DATA XREF: sub_B800:loc_BB69↓r
byte_179:       fcb 0                   ; DATA XREF: sub_B800+370↓r
byte_17A:       fcb 0                   ; DATA XREF: sub_D381+9F↓r
byte_17B:       fcb 0                   ; DATA XREF: sub_D381+A7↓r
byte_17C:       fcb 0                   ; DATA XREF: sub_AA7C+46↓r
                                        ; sub_AA7C+4B↓w ...
byte_17D:       fcb 0                   ; DATA XREF: sub_AB71:loc_AB88↓o
                                        ; sub_AB71:loc_AD1D↓r ...
byte_17E:       fcb 0                   ; DATA XREF: sub_AB71:loc_ACCF↓w
                                        ; sub_AB71+187↓r ...
byte_17F:       fcb 0                   ; DATA XREF: sub_AB71+157↓w
byte_180:       fcb 0                   ; DATA XREF: sub_AB71:loc_AC1D↓w
                                        ; sub_AB71:loc_AC27↓r ...
byte_181:       fcb 0                   ; DATA XREF: sub_AB71+A5↓w
                                        ; sub_AB71:loc_ACD6↓w
byte_182:       fcb 0                   ; DATA XREF: sub_F1F4:loc_F204↓w
                                        ; sub_F1F4+14↓r
byte_183:       fcb 0                   ; DATA XREF: sub_A0F1:loc_A101↓r
                                        ; IRQ+14↓w
                fcb 0
byte_185:       fcb 0                   ; DATA XREF: sub_A0F1+13↓r
                                        ; IC1I+50F↓w
unk_186:        fcb   0                 ; DATA XREF: sub_CA82+50↓o
byte_187:       fcb 0                   ; DATA XREF: sub_CA82+74↓o
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
byte_19D:       fcb 0                   ; DATA XREF: sub_CA82+56↓o
                                        ; sub_CA82+71↓r ...
byte_19E:       fcb 0                   ; DATA XREF: sub_BE83+8B↓w
                                        ; sub_BE83+172↓w ...
word_19F:       fdb 0                   ; DATA XREF: ROM_EPROM:F76E↓w
                                        ; ROM_EPROM:F776↓w ...
byte_1A1:       fcb 0                   ; DATA XREF: sub_A12C+74↓w
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
                fcb 0
; end of 'RAM'

; ===========================================================================

 ORG $0400
SwitchPortAccessReg1:fcb $C             ; DATA XREF: __RESET+6D↓w
                                        ; __RESET+4D0↓r ...
SwitchPortAccessReg2:fcb 6              ; DATA XREF: sub_F54C+2↓r
                                        ; sub_F54C+10↓r ...
PIA_Ctrl_1:     fcb 0                   ; DATA XREF: __RESET+70↓w
                                        ; __RESET+73↓r ...
PIA_Ctrl_2:     fcb 0                   ; DATA XREF: __RESET+A0↓w
                                        ; sub_9E01+1EC↓r ...
PIA_Ctrl_3:     fcb 0                   ; DATA XREF: __RESET+9A↓w
                                        ; sub_F351+B8↓w ...
PIA_Ctrl_4:     fcb $F0                 ; DATA XREF: sub_F54C+28↓w
                                        ; sub_F644+3E↓r ...
PIA_Ctrl_5:     fcb 0                   ; DATA XREF: __RESET+93↓w
                                        ; sub_9E01+1FA↓r ...
                fcb   0
InjectorPulsewidth_HB_Cyl1:fcb $3E      ; DATA XREF: __RESET+A6↓w
                                        ; sub_9E01:loc_9FD2↓o ...
InjectorPulsewidth_LB_Cyl1:fcb $4C ; L
InjectorPulsewidth_HB_Cyl2:fcb $2F      ; DATA XREF: __RESET+A9↓w
                                        ; sub_9E01:loc_9FD7↓o ...
InjectorPulsewidth_LB_Cyl2:fcb $4F ; O
InjectorPulsewidth_HB_Cyl3:fcb $1E      ; DATA XREF: __RESET+AC↓w
                                        ; sub_9E01:loc_9FDC↓o ...
InjectorPulsewidth_LB_Cyl3:fcb $C7
InjectorPulsewidth_HB_Cyl4:fcb $E       ; DATA XREF: __RESET+AF↓w
                                        ; sub_9E01:loc_9FE1↓o ...
InjectorPulsewidth_LB_Cyl4:fcb $90
                fcb  $C
                fcb   6
                fcb   0
                fcb   0
                fcb   0
                fcb $F0
                fcb   0
                fcb   0
                fcb $BC
                fcb $4B ; K
                fcb $AD
                fcb $4E ; N
                fcb $9C
                fcb $CF
                fcb $8C
                fcb $8F
                fcb  $C
                fcb   6
                fcb   0
                fcb   0
                fcb   0
                fcb $F0
                fcb   0
                fcb   0
                fcb $3A ; :
                fcb $4A ; J
                fcb $2B ; +
                fcb $4D ; M
                fcb $1A
                fcb $CE
                fcb  $A
                fcb $97
                fcb  $C
                fcb   6
                fcb   0
                fcb   0
                fcb   0
                fcb $F0
                fcb   0
                fcb   0
                fcb $B8
                fcb $49 ; I
                fcb $A9
                fcb $4C ; L
                fcb $98
                fcb $CD
                fcb $88
                fcb $96
PIA3_Buffer_2_t3:fcb $C                 ; DATA XREF: __RESET+62↓w
                                        ; __RESET+11B↓w ...
                fcb   6
                fcb   0
                fcb   0
                fcb   0
                fcb $F0
                fcb   0
                fcb   0
                fcb $36 ; 6
                fcb $48 ; H
                fcb $27 ; '
                fcb $4B ; K
                fcb $16
                fcb $CC
                fcb   6
                fcb $95
                fcb  $C
                fcb   6
                fcb   0
                fcb   0
                fcb   0
                fcb $F0
                fcb   0
                fcb   0
                fcb $B4
                fcb $47 ; G
                fcb $A5
                fcb $4A ; J
                fcb $94
                fcb $CB
                fcb $84
                fcb $94
                fcb  $C
                fcb   6
                fcb   0
                fcb   0
                fcb   0
                fcb $F0
                fcb   0
                fcb   0
                fcb $32 ; 2
                fcb $46 ; F
                fcb $23 ; #
                fcb $49 ; I
                fcb $12
                fcb $CA
                fcb   2
                fcb $93
                fcb  $C
                fcb   6
                fcb   0
                fcb   0
                fcb   0
                fcb $F0
unk_476:        fcb   0                 ; DATA XREF: __RESET+145↓o
                fcb   0
                fcb $B0
                fcb $45 ; E
                fcb $A1
                fcb $48 ; H
                fcb $90
                fcb $C9
                fcb $80
                fcb $92
CountdownTimerFromKeyOn:fcb 0           ; DATA XREF: __RESET+10A↓o
                                        ; RESERVED:loc_9A62↓o ...
UNe_6481:       fcb $FF                 ; DATA XREF: sub_F081+7↓w
                                        ; sub_F081+10↓r ...
UNe_6482:       fcb 0                   ; DATA XREF: sub_D14D+E3↓w
                                        ; sub_D14D+134↓r ...
UNe_6483:       fcb $FF
UNe_6484:       fcb 0                   ; DATA XREF: sub_D0F1↓o
                                        ; sub_D0F1+7↓w ...
LDXi_6485:      fcb $FF                 ; DATA XREF: IC2I+4574↓o
                                        ; IC1I+BD↓o
FDRVar0:        fcb 0                   ; DATA XREF: SCISS+3↓w
                                        ; CME+13↓w ...
FDRVar1:        fcb $FF                 ; DATA XREF: __RESET+164↓w
                                        ; __RESET+171↓r ...
FDRVar2:        fcb 0                   ; DATA XREF: sub_A730+F↓w
                                        ; sub_A730+19↓r ...
FDRVar3:        fcb $FF                 ; DATA XREF: sub_A0F1+25↓w
                                        ; sub_A0F1:loc_A121↓r ...
STe_648A:       fcb 0                   ; DATA XREF: sub_A35F:loc_A3C6↓r
                                        ; sub_A35F:loc_A3E7↓r ...
Temp5_t3:       fcb $FF                 ; DATA XREF: sub_96AC+2F↓o
                                        ; sub_96AC+A3↓o ...
word_48C:       fdb $FF                 ; DATA XREF: sub_9E01+18A↓w
                                        ; sub_CA13+1F↓w ...
byte_48E:       fcb 0                   ; DATA XREF: RESERVED:loc_9A67↓o
                                        ; RESERVED:9A78↓w ...
                fcb $FF
unk_490:        fcb   0                 ; CODE XREF: RESERVED:9AC3↓J
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   1
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FB
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
unk_4D0:        fcb   0                 ; DATA XREF: RESERVED:9A71↓o
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
                fcb $FF
                fcb   0
TopOfStack:     fcb $FF                 ; DATA XREF: SCISS+14↓o

; ===========================================================================

; Segment type: Pure data
                ; segment FSR
                org $1000
PORTA:          fcb 0                   ; DATA XREF: sub_A8E3+B↓o
                                        ; sub_B14E+16↓o ...
                                        ; Port A data
RESERV01:       fcb $2E ; .             ; RESERVED
PIOC:           fcb $D8                 ; Parallel I_O Control Register
PORTC:          fcb $80                 ; Port C Data
PORTB:          fcb $BB                 ; Output Port B
PORTCL:         fcb   4                 ; Alternate Latched Port C
RESERV1006:     fcb $40 ; @             ; RESERVED06
DDRC:           fcb $90                 ; Data Direction for Port C
PORTD:          fcb 7                   ; DATA XREF: __RESET+67↓w
                                        ; __RESET+503↓o ...
                                        ; Port D Data
DDRD:           fcb 0                   ; DATA XREF: __RESET+84↓w
                                        ; Data Direction for Port D
PORTE:          fcb $3B ; ;             ; Port E Data
CFORC:          fcb 0                   ; DATA XREF: __RESET+5C↓w
                                        ; sub_96AC+48↓w ...
                                        ; Timer Compare Force Register
OC1M:           fcb 0                   ; DATA XREF: __RESET+42↓w
                                        ; sub_F351+D2↓w
                                        ; Output Compare 1 Mask Register
OC1D:           fcb 0                   ; DATA XREF: __RESET+45↓w
                                        ; Output Compare 1 Data Register
TCNTH:          fcb $F6                 ; DATA XREF: __RESET+51C↓r
                                        ; __RESET+565↓r ...
                                        ; Timer Counter Register
TCNTL:          fcb $79 ; y             ; Timer Counter Register
TIC1H:          fcb $FF                 ; DATA XREF: sub_A35F+17↓r
                                        ; IC1I+B7↓r ...
                                        ; Input Capture 1 Register
TIC1L:          fcb $FF                 ; Input Capture 1 Register
TIC2H:          fcb $FF                 ; DATA XREF: IC2I↓r
                                        ; Input Capture 2 Register
TIC2L:          fcb $FF                 ; Input Capture 2 Register
TIC3H:          fcb $FF                 ; DATA XREF: sub_9981+96↓o
                                        ; Input Capture 3 Register
TIC3L:          fcb $FF                 ; Input Capture 3 Register
TOC1H:          fcb  $D                 ; DATA XREF: __RESET+522↓w
                                        ; OC1I+A↓r ...
                                        ; Output Compare 1 Register
TOC1L:          fcb $B0                 ; Output Compare 1 Register
TOC2H:          fcb $FF                 ; DATA XREF: sub_9E01:loc_9F9E↓o
                                        ; sub_CA13+48↓w ...
                                        ; Output Compare 2 Register
TOC2L:          fcb $FF                 ; Output Compare 2 Register
TOC3H:          fcb $FF                 ; DATA XREF: sub_9E01:loc_9F72↓o
                                        ; sub_CA13+4B↓w ...
                                        ; Output Compare 3 Register
TOC3L:          fcb $FF                 ; Output Compare 3 Register
TOC4H:          fcb $FF                 ; DATA XREF: sub_9E01:loc_9F52↓o
                                        ; sub_CA13+52↓w ...
                                        ; Output Compare 4 Register
TOC4L:          fcb $FF                 ; Output Compare 4 Register
TCO5H:          fcb $FF                 ; DATA XREF: sub_9E01+132↓w
                                        ; IC1I+242↓w ...
                                        ; Output Compare 5 Register
TCO5L:          fcb $FF                 ; Output Compare 5 Register
TCTL1:          fcb 0                   ; DATA XREF: __RESET+59↓w
                                        ; sub_96AC+43↓w ...
                                        ; Timer Control Register 1
TCTL2:          fcb 0                   ; DATA XREF: __RESET+53↓w
                                        ; sub_EFE2↓r
                                        ; Timer Control Register 2
TMSK1:          fcb 0                   ; DATA XREF: __RESET+4B↓w
                                        ; sub_A12C+89↓r ...
                                        ; Timer Interrupt Mask Register 1
TFLG1:          fcb $F8                 ; DATA XREF: __RESET+4E↓w
                                        ; OC1I+2↓w ...
                                        ; Timer Interrupt Flag Register 1
TMSK2:          fcb 0                   ; DATA XREF: SCISS+9↓w CME+7↓w ...
                                        ; Timer Interrupt Mask Register 2
TFLG2:          fcb $C0                 ; DATA XREF: sub_F53B+B↓w
                                        ; PAII+15↓w
                                        ; Timer Interrupt Flag Register 2
PACTL:          fcb 0                   ; DATA XREF: __RESET+96↓w
                                        ; Pulse Accumulator Control Register
PACNT:          fcb 0                   ; DATA XREF: sub_F53B+E↓w
                                        ; Pulse Accumulator Count Register
SPCR:           fcb $24                 ; DATA XREF: __RESET+8A↓w
                                        ; __RESET+525↓r ...
                                        ; SPI Control Register
SPSR:           fcb 0                   ; DATA XREF: __RESET+87↓r
                                        ; __RESET+509↓r ...
                                        ; SPI Status Register
SPDR:           fcb 0                   ; DATA XREF: __RESET+50C↓w
                                        ; __RESET+53D↓w ...
                                        ; SPI Data Register
BAUD:           fcb $30                 ; DATA XREF: __RESET+B8↓w
                                        ; sub_9981+C↓r ...
                                        ; SCI Baud Rate Control 3
SCCR1:          fcb $40                 ; DATA XREF: __RESET+C1↓w
                                        ; SCI Control Register 1
SCCR2:          fcb $C                  ; DATA XREF: __RESET+B5↓w
                                        ; sub_F351+D5↓w
                                        ; Serial Communications Control Register 2
SCSR:           fcb $10                 ; DATA XREF: __RESET+BB↓r
                                        ; sub_9981:loc_999C↓r ...
                                        ; Serial Communications Status Register
SCDR:           fcb 0                   ; DATA XREF: sub_9981+22↓r
                                        ; sub_9981:loc_99BE↓r ...
                                        ; SCI Data (Read RDR, Write TDR)
ADCTL:          fcb $80                 ; DATA XREF: __RESET+12B↓w
                                        ; __RESET:loc_925C↓r ...
                                        ; A_D Control Register
ADR1:           fcb 0                   ; DATA XREF: __RESET+133↓r
                                        ; __RESET+157↓r ...
                                        ; A_D Result Register 1
ADR2:           fcb 0                   ; DATA XREF: __RESET+1E1↓r
                                        ; __RESET+206↓r ...
                                        ; A_D Result Register 2
ADR3:           fcb 0                   ; DATA XREF: sub_96AC:loc_971C↓r
                                        ; sub_96AC+B4↓r ...
                                        ; A_D Result Register 3
ADR4:           fcb 0                   ; DATA XREF: __RESET+220↓r
                                        ; sub_96AC+AF↓r ...
                                        ; A_D Result Register 4
BPROT:          fcb $1F                 ; DATA XREF: SCISS+11↓w
                                        ; CME+F↓w ...
                                        ; Block Protect Register
RESERV1036:     fcb $2E ; .             ; RESERVED
RESERV1037:     fcb $2E ; .             ; RESERVED
RESERV1038:     fcb $2E ; .             ; RESERVED
OPTION:         fcb $10                 ; DATA XREF: SCISS+C↓w CME+A↓w ...
                                        ; System Configuration Options
COPRST:         fcb $2E                 ; DATA XREF: sub_F32B+3↓w
                                        ; sub_F32B+6↓w ...
                                        ; Arm_Reset COP Timer Circuitry
PPROG:          fcb 0                   ; DATA XREF: __RESET+9D↓w
                                        ; sub_A35F+105↓r ...
                                        ; EEPROM Program Control Register
HPRIO:          fcb $60                 ; DATA XREF: __RESET:loc_916D↓w
                                        ; Highest Priority I-Bit Int and Misc
INIT:           fcb   1                 ; RAM and I_O Mapping Register
RESERV3E:       fcb   8                 ; RESERVED
CONFIG:         fcb   9                 ; System Configuration Register
; end of 'FSR'
